// THE JUICE CATALOGUE. Every piece of game feel the game has, has just got, or has been asked for,
// in one list: what sets it off, what it looks like, how big and how long, where it lives in this
// code, and how the same thing is built in Godot 4 — because the list is for whoever builds the
// next version as much as for this one. Read by the JUICE tab of the level tool (`drawJuiceTab`)
// and by `node tools/juice-md.js`, which writes JUICE.md from it, so it is written once.
//
// `status`: 'in' was already in the game, 'new' landed with this tab, 'backlog' is not built yet.
// `src` is where the idea comes from:
//   SCREENSHAKE — Jan Willem Nijman (Vlambeer), "The Art of Screenshake", INDIGO 2013
//   JUICE       — Martin Jonasson & Petri Purho, "Juice it or lose it", GDC Europe 2012
//   SWINK       — Steve Swink, "Game Feel" (2008)
//   GMTK        — Mark Brown, "Secrets of Game Feel and Juice" and "Celeste & forgiveness"
//   HITSTOP     — Masahiro Sakurai on hitstop / hit-lag (Smash Bros.), and the fighting-game canon
//   GOAT        — asked for by this game's own playtests (BACKLOG.md)
// Sizes are read off TUNING where a number exists, so the table cannot drift from the game.
const JUICE_SRC = {
  SCREENSHAKE: 'Vlambeer — The Art of Screenshake (2013)',
  JUICE: 'Jonasson & Purho — Juice it or lose it (2012)',
  SWINK: 'Steve Swink — Game Feel (2008)',
  GMTK: "Game Maker's Toolkit — Secrets of Game Feel / Celeste forgiveness",
  HITSTOP: 'Sakurai / fighting games — hitstop',
  GOAT: 'Goat Out playtests',
};

const JUICE = [
  // ---- the camera ----
  { name: 'Hitstop', cat: 'TIME', status: 'in', src: 'HITSTOP', code: 'game.hitstop · juice.hitstop',
    trigger: 'Every kill; smaller on door blows, parries, the pen', look: 'The whole simulation freezes for a few frames; the picture holds on the moment of contact',
    size: () => `${TUNING.juice.hitstop}s kill, +${TUNING.juice.comboHitstopMul}/combo to +${TUNING.juice.comboHitstopCap}s`,
    godot: 'Engine.time_scale = 0 then a timer that ignores time scale: await get_tree().create_timer(t, true, false, true).timeout; restore to 1. Keep UI tweens on TWEEN_PAUSE_PROCESS.' },
  { name: 'Screen shake', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.shake · juice.shakeKill/shakeHit/shakeDecay',
    trigger: 'Kills, hits taken, door blows, gunshots (tiny)', look: 'Random offset of the whole picture that decays; biggest on the Butcher',
    size: () => `${TUNING.juice.shakeKill}px kill · ${TUNING.juice.shakeHit}px hurt · decays ×${TUNING.juice.shakeDecay}/s`,
    godot: 'Trauma model: trauma += amt (clamp 0..1); Camera2D.offset = max_offset * trauma² * FastNoiseLite sample; trauma -= decay * delta. Noise, not randf, so it does not jitter.' },
  { name: 'Directional kick', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.kick · juice.kick/kickMax/kickDecay',
    trigger: 'Headbutt landing, kills, clubs taken', look: 'The picture is shoved along the blow and springs back — a punch, not a rattle',
    size: () => `${TUNING.juice.kick}px, capped ${TUNING.juice.kickMax}px, decay ×${TUNING.juice.kickDecay}/s`,
    godot: 'A second Camera2D.offset term: kick_vec += dir * amt; kick_vec = kick_vec.lerp(Vector2.ZERO, 1 - exp(-decay * delta)). Add to the shake offset.' },
  { name: 'Zoom punch', cat: 'CAMERA', status: 'in', src: 'JUICE', code: 'game.zoomPunch · juice.zoomKick/zoomDecay',
    trigger: 'Kills, the wraith unmade, bombs', look: 'The lens shoves in a few percent and settles back',
    size: () => `+${Math.round(TUNING.juice.zoomKick * 100)}% · settles ×${TUNING.juice.zoomDecay}/s`,
    godot: 'create_tween().tween_property(camera, "zoom", base * (1 + k), 0.04) then .tween_property(camera, "zoom", base, 0.25).set_trans(Tween.TRANS_EXPO).set_ease(Tween.EASE_OUT).' },
  { name: 'Camera lead', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.camLead · camera.lead/leadLerp',
    trigger: 'Always, toward the aim and scaled by run speed', look: 'The view looks ahead of the goat, not at him',
    size: () => `${TUNING.camera.lead}px ahead · lerp ${TUNING.camera.leadLerp}`,
    godot: 'Camera2D child of the player with its own script: target = player.global_position + aim * lead; position = position.lerp(target, 1 - exp(-rate * delta)).' },
  { name: 'Deadzone camera', cat: 'CAMERA', status: 'in', src: 'SWINK', code: 'game.camFollow · camera.deadzone/fitMargin',
    trigger: 'Standing still, or in a room that fits the screen', look: 'Small motion never re-centres the picture; a small room holds still',
    size: () => `${TUNING.camera.deadzone}px deadzone`,
    godot: 'Camera2D.drag_horizontal_enabled / drag_vertical_enabled with drag margins; a room-sized Area2D can set limit_* to lock a small room.' },
  { name: 'Slow motion on a kill', cat: 'TIME', status: 'in', src: 'SCREENSHAKE', code: 'game.slowTimer · juice.killSlow/comboSlow/deathSlow',
    trigger: 'The Butcher down, a third kill in a streak, death', look: 'Time eases to a third and back',
    size: () => `${TUNING.juice.killSlow}s boss · ${TUNING.juice.comboSlow}s combo · ${TUNING.juice.deathSlow}s death`,
    godot: 'Tween Engine.time_scale to 0.3 and back with a tween set to ignore time scale (set_ignore_time_scale(true)). Pitch music down with AudioServer bus effect, not the stream.' },
  // ---- the screen ----
  { name: 'Screen flash', cat: 'SCREEN', status: 'in', src: 'JUICE', code: 'game.flash · juice.flashDecay',
    trigger: 'Kills (blood), witchfire, a soul, reaching the stairs', look: 'An additive colour wash over the picture that fades fast',
    size: () => `0.1–0.4 alpha · fades ×${TUNING.juice.flashDecay}/s`,
    godot: 'CanvasLayer > ColorRect (full rect), material blend_mode ADD; tween modulate.a from amt to 0.' },
  { name: 'Hurt direction arc', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'game.hurtFlash · drawHurt',
    trigger: 'Taking a hit', look: 'A red arc at the edge of the screen pointing back at whoever hit you',
    size: () => '0.6s',
    godot: 'TextureRect arc on a CanvasLayer, rotation = angle to attacker; tween modulate.a.' },
  { name: 'Hurt vignette', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'drawHurtVignette · juice.hurtVignette',
    trigger: 'Taking a hit', look: 'Every corner reddens and fades',
    size: () => `${TUNING.juice.hurtVignette.life}s · ${TUNING.juice.hurtVignette.alpha} alpha`,
    godot: 'Full-screen ColorRect with a radial-gradient shader (smoothstep on distance from UV centre), uniform intensity tweened.' },
  { name: 'Last-heart heartbeat', cat: 'SCREEN', status: 'new', src: 'GMTK', code: 'drawHeartbeat · juice.heartbeat',
    trigger: 'Down to the last heart', look: 'The screen edge pulses red lub-dub, and the last heart on the HUD throbs with it',
    size: () => `${TUNING.juice.heartbeat.bpm} bpm · ${TUNING.juice.heartbeat.alpha} alpha · heart ±${Math.round(TUNING.juice.heartbeat.throb * 100)}%`,
    godot: 'Same vignette shader; drive intensity from an AnimationPlayer loop (two keys close together, then a rest). Pair with a low-pass on the music bus.' },
  { name: 'Rumble', cat: 'SCREEN', status: 'in', src: 'SWINK', code: 'game.vibe',
    trigger: 'Hits, kills, throws — touch devices only', look: 'The phone buzzes, scaled to the blow',
    size: () => '8–60 ms',
    godot: 'Input.start_joy_vibration(0, weak, strong, dur) for pads; Input.vibrate_handheld(ms) on mobile.' },
  // ---- bodies ----
  { name: 'Hit flash (white)', cat: 'BODY', status: 'new', src: 'SCREENSHAKE', code: 'enemy.flash · juice.hitFlash · drawEnemy',
    trigger: 'A headbutt lands on a man (and every Butcher blow)', look: 'He is repainted as a solid white silhouette for a few frames',
    size: () => `${TUNING.juice.hitFlash}s`,
    godot: 'CanvasItem shader: uniform float flash; COLOR.rgb = mix(texture(TEXTURE, UV).rgb, vec3(1.0), flash); keep alpha. Tween flash 1 → 0. Use a per-instance uniform (instance uniform float flash) so one material serves all.' },
  { name: 'Squash & stretch (poses)', cat: 'BODY', status: 'in', src: 'JUICE', code: 'drawGoat · painted-art drawGoat',
    trigger: 'Windup, lunge, roll, stun', look: 'Crouched before a headbutt, stretched through it, curled in a roll',
    size: () => 'windup 0.85×1.1 · lunge 1.15×0.92',
    godot: 'AnimationPlayer keys on Sprite2D.scale per state, or set scale in the state machine enter().' },
  { name: 'Squash spring', cat: 'BODY', status: 'new', src: 'JUICE', code: 'game.squashGoat · juice.squash',
    trigger: 'A headbutt landing, a blow taken, the end of a roll', look: 'The goat wobbles wide-and-flat then tall-and-thin and settles, like jelly',
    size: () => `hit ${TUNING.juice.squash.hit} · hurt ${TUNING.juice.squash.hurt} · ${TUNING.juice.squash.freq} rad/s, decay ${TUNING.juice.squash.decay}`,
    godot: 'create_tween().tween_property(sprite, "scale", Vector2(1+a, 1-a), 0.05) then back to Vector2.ONE over 0.3s with TRANS_ELASTIC / EASE_OUT.' },
  { name: 'Knockback', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'enemy.fling · goat.headbutt.impulse',
    trigger: 'Every headbutt, every body arriving', look: 'The man flies along the blow, spinning — the fling is the attack',
    size: () => `impulse ${Math.round(TUNING.goat.headbutt.impulse)}px/s`,
    godot: 'CharacterBody2D: velocity = dir * impulse, then friction in _physics_process; spin the sprite while velocity > threshold.' },
  { name: 'Player recoil', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'damage(kx, ky) · Butcher planted bounce',
    trigger: 'A blow taken; a headbutt into a planted Butcher', look: 'The goat is shoved back the way the blow came',
    size: () => '5 tiles/s on a planted Butcher',
    godot: 'velocity += -dir * recoil on the hit; clamp with move_toward over a few frames.' },
  { name: 'Motion smear', cat: 'BODY', status: 'in', src: 'JUICE', code: 'goat.trail · goat.trail.*',
    trigger: 'Running, scaled by speed and run-up', look: 'Fading ghosts of the goat behind him',
    size: () => `life ${TUNING.goat.trail.life}s`,
    godot: 'Spawn a Sprite2D copy with the current frame every N ms, tween modulate.a to 0 and free; or a GPUParticles2D using the sprite texture with local_coords off.' },
  { name: 'Invulnerability blink', cat: 'BODY', status: 'in', src: 'GMTK', code: 'goat.invuln',
    trigger: 'After a hit and through a roll', look: 'The goat strobes at half alpha',
    size: () => `${TUNING.goat.invuln}s`,
    godot: 'AnimationPlayer toggling modulate.a on a 1/30s step while an invuln Timer runs.' },
  { name: 'Dazed stars', cat: 'BODY', status: 'in', src: 'JUICE', code: 'drawStars · enemy.dazed',
    trigger: 'The scream, the pen, a stun', look: 'Three stars orbit the head, the body sways',
    size: () => 'as long as the daze',
    godot: 'Three Sprite2Ds on a Node2D child rotated each frame; an ellipse via scale.y = 0.5.' },
  // ---- the world ----
  { name: 'Impact ring + sparks', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'game.impact · juice.impact',
    trigger: 'A headbutt landing', look: 'A tight bright ring at the point of contact and a star of spark streaks thrown along the blow',
    size: () => `${TUNING.juice.impact.ring} tiles · ${TUNING.juice.impact.life}s · ${TUNING.juice.impact.sparks} sparks`,
    godot: 'A one_shot GPUParticles2D (explosiveness 1, spread 45°, direction = blow) plus a ring Sprite2D tweened scale 0 → 1 and alpha 1 → 0. Pool them.' },
  { name: 'Kill shockwave', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'onKill · juice.impact.killRing',
    trigger: 'Every kill but a drop', look: 'A pale ring swells out from the body and thins away',
    size: () => `${TUNING.juice.impact.killRing} tiles · ${TUNING.juice.impact.killLife}s`,
    godot: 'Screen-space distortion shader (SCREEN_TEXTURE offset by a ring function) for the fancy version, or a ring Sprite2D.' },
  { name: 'Hoof dust', cat: 'WORLD', status: 'new', src: 'JUICE', code: 'game.dust · juice.dust',
    trigger: 'Lunge, roll start, roll landing, running on a full run-up', look: 'Soft pale puffs kicked out behind him that swell and fade',
    size: () => `${TUNING.juice.dust.life}s · ${TUNING.juice.dust.size}→${TUNING.juice.dust.size + TUNING.juice.dust.grow}px`,
    godot: 'CPUParticles2D at the feet, emitting = running; scale_amount_curve rising, color_ramp alpha falling. One-shot burst on lunge/land.' },
  { name: 'Muzzle flash', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'fireBullet · juice.muzzle · drawFlares',
    trigger: 'Every rifle shot', look: 'A pointed star of fire along the shot for a frame or two',
    size: () => `${TUNING.juice.muzzle.life}s · ${TUNING.juice.muzzle.size}px`,
    godot: 'Sprite2D at the muzzle, visible for 2 frames with random rotation; a PointLight2D pulse lights the room with it.' },
  { name: 'Aim telegraph', cat: 'WORLD', status: 'in', src: 'GMTK', code: 'drawAimTelegraph · drawTelegraph',
    trigger: 'A rifle aiming, a club winding up', look: 'A line and a wedge showing where the blow will land before it does',
    size: () => 'the windup',
    godot: 'Line2D from the shooter along aim, width and alpha tweened as the windup fills.' },
  { name: 'Particles', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.particles · combat-fx',
    trigger: 'Blows, doors, coals, gunshots', look: 'Squares and chips flung from the contact',
    size: () => '0.3–0.8s',
    godot: 'GPUParticles2D one_shot, pooled; ParticleProcessMaterial with initial_velocity range and damping.' },
  { name: 'Gore and debris', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'game.gore · CombatFX.fragment/debris',
    trigger: 'Kills, broken doors and crates', look: 'Chunks with height that fly, bounce and settle — the body tears into its own sprite',
    size: () => `≤${TUNING.effects.maxAir} in the air`,
    godot: 'RigidBody2D pieces are too heavy; fake height with a z value per piece in one script, draw with _draw() or MultiMeshInstance2D.' },
  { name: 'Permanence (blood, bodies)', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'world.decal · DECAL_SCALE',
    trigger: 'Everything that bleeds, burns or falls', look: 'Blood, scorch and bodies stay on the floor for the whole level',
    size: () => 'the level',
    godot: 'A SubViewport with render_target_clear_mode = NEVER; draw stains into it and show it as a TextureRect under the actors.' },
  { name: 'Floating words', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.floatText',
    trigger: 'Door counts, OOPS, COALS, combo ×N', look: 'Stamped caps that rise and fade',
    size: () => '1.2s',
    godot: 'Label scene spawned at the point, tween position.y -= 30 and modulate.a → 0, then queue_free.' },
  { name: 'Combo counter', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.combo · juice.comboWindow',
    trigger: 'Kills inside the window', look: '×N grows with the streak',
    size: () => `${TUNING.juice.comboWindow}s window`,
    godot: 'Autoload counter with a Timer; the label scales with a TRANS_BACK tween on each increment.' },
  { name: 'Barks', cat: 'WORLD', status: 'in', src: 'GOAT', code: 'game.bark · BARKS',
    trigger: 'Seeing, losing, panicking', look: 'A dark plate over a man\'s head with a line',
    size: () => '< 2s, global gap',
    godot: 'A Label over the head plus a global cooldown in an autoload so a crowd never talks at once.' },
  // ---- sound ----
  { name: 'Layered sound per hit', cat: 'SOUND', status: 'in', src: 'SCREENSHAKE', code: 'GameAudio sfx*',
    trigger: 'Every verb', look: 'Thud + bleat + steel stacked per event',
    size: () => '—',
    godot: 'AudioStreamRandomizer with random_pitch and random_volume_offset_db; several AudioStreamPlayer2Ds per event.' },
  { name: 'Reactive music', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.updateScene · MUSIC.md',
    trigger: 'Who is in the room, spotted / chase / combat', look: 'The score thickens with the room',
    size: () => '16-bar transport',
    godot: 'AudioStreamInteractive (4.3+) with clips per stage and transitions on beat, or AudioStreamSynchronized layers with volume per layer.' },
  // ---- the backlog ----
  { name: 'Input buffer', cat: 'FEEL', status: 'backlog', src: 'GMTK',
    trigger: 'Pressing headbutt/roll during a recovery', look: 'Nothing visible — the press is remembered and fires the frame the recovery ends',
    size: () => '~0.12s window',
    godot: 'Store the press time; in the state machine, on entering idle, consume it if Time.get_ticks_msec() - pressed < window. Not a cancel: the recovery is still eaten in full (pillar 4).' },
  { name: 'Door-hit forgiveness', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'headbuttHits · door.reachSlack',
    trigger: 'A headbutt at a door', look: 'A door takes the blow from its ends and from flush in a wall',
    size: () => `+${TUNING.prop.door.reachSlack}px reach, cone widened for doors`,
    godot: 'Give the hurtbox a margin bigger than the collision shape (a second Area2D) — the "coyote" of melee.' },
  { name: 'Hit direction on the body', cat: 'BODY', status: 'backlog', src: 'SCREENSHAKE',
    trigger: 'A man taking a blow', look: 'His sprite leans away from the blow for a few frames before the fling',
    size: () => '0.1s',
    godot: 'Tween sprite.skew or rotation by ±0.2 toward -blow and back.' },
  { name: 'Shell casings', cat: 'WORLD', status: 'backlog', src: 'SCREENSHAKE',
    trigger: 'A rifle shot', look: 'A brass shell pops out sideways, bounces and stays on the floor',
    size: () => 'permanent',
    godot: 'One-shot particle with a height fake; on land, stamp into the decal SubViewport.' },
  { name: 'Chromatic kick', cat: 'SCREEN', status: 'backlog', src: 'JUICE',
    trigger: 'A big kill or a bomb', look: 'The red and blue channels split apart for a frame',
    size: () => '0.08s, 3px',
    godot: 'Screen shader on a BackBufferCopy: sample SCREEN_TEXTURE at UV ± offset for r and b.' },
  { name: 'Room-clear sting', cat: 'SOUND', status: 'backlog', src: 'GMTK',
    trigger: 'The last man in a room goes down', look: 'A short musical tag and the fog breathes out a little',
    size: () => '1 bar',
    godot: 'Signal from the room when its enemy group empties; play a one-shot on the music bus quantised to the beat.' },
  { name: 'Anticipation on the goat', cat: 'BODY', status: 'backlog', src: 'SWINK',
    trigger: 'Headbutt windup', look: 'A tiny pull-back opposite the aim before the lunge',
    size: () => '3px over the windup',
    godot: 'Offset the sprite by -aim * 3 during windup via tween, snap forward on lunge.' },
  { name: 'Idle life', cat: 'BODY', status: 'backlog', src: 'JUICE',
    trigger: 'Standing still', look: 'Breathing bob, an ear flick, a blink',
    size: () => 'loop 2–4s',
    godot: 'AnimationPlayer idle with randomised start; blink on a random Timer.' },
];

// The whole table as Markdown: the EXPORT button on the JUICE tab downloads it, and
// `node tools/juice-md.js` writes it to JUICE.md, so the list can be handed to somebody who never
// opens the game.
function juiceMarkdown() {
  const cell = (s) => String(s).replace(/\|/g, '\|');
  const status = { in: 'in game', new: 'new', backlog: 'backlog' };
  const out = ['# Goat Out — juice catalogue', '',
    'Generated from `js/juice.js` (the JUICE tab of the level tool). Status: **in game** was already there, **new** landed with the tab, **backlog** is not built yet.', '',
    '| Effect | Status | Trigger | How it looks | Size / time | Godot 4 | Source | Code |',
    '|---|---|---|---|---|---|---|---|'];
  for (const j of JUICE) out.push('| ' + [j.name, status[j.status], j.trigger, j.look, j.size(), j.godot, JUICE_SRC[j.src], j.code ? '`' + j.code + '`' : '—'].map(cell).join(' | ') + ' |');
  out.push('', '## Sources', '', ...Object.values(JUICE_SRC).map((s) => '- ' + s));
  return out.join('\n') + '\n';
}
