// THE JUICE CATALOGUE. Every piece of game feel the game has, has just got, or has been asked for,
// in one list: what sets it off, what it looks like, how big and how long, where it lives in this
// code, and how the same thing is built in Godot 4, because the list is for whoever builds the
// next version as much as for this one. Read by the JUICE tab of the level tool (`drawJuiceTab`)
// and by `node tools/juice-md.js`, which writes JUICE.md from it, so it is written once.
//
// `status`: 'in' was already in the game, 'new' landed with this tab, 'backlog' is not built yet.
// `src` is where the idea comes from:
//   SCREENSHAKE, Jan Willem Nijman (Vlambeer), "The Art of Screenshake", INDIGO 2013
//   JUICE      , Martin Jonasson & Petri Purho, "Juice it or lose it", GDC Europe 2012
//   SWINK      , Steve Swink, "Game Feel" (2008)
//   GMTK       , Mark Brown, "Secrets of Game Feel and Juice" and "Celeste & forgiveness"
//   HITSTOP    , Masahiro Sakurai on hitstop / hit-lag (Smash Bros.), and the fighting-game canon
//   CAMERA2D   , Mark Brown, "How to Make a Good 2D Camera" (GMTK, 2023)
//   GOAT       , asked for by this game's own playtests (BACKLOG.md)
//   HADES      , Supergiant Games, Hades (2020): how a god talks to you between runs
// Sizes are read off TUNING where a number exists, so the table cannot drift from the game.
const JUICE_SRC = {
  SCREENSHAKE: 'Vlambeer, The Art of Screenshake (2013)',
  JUICE: 'Jonasson & Purho, Juice it or lose it (2012)',
  SWINK: 'Steve Swink, Game Feel (2008)',
  GMTK: "Game Maker's Toolkit, Secrets of Game Feel / Celeste forgiveness",
  HITSTOP: 'Sakurai / fighting games, hitstop',
  CAMERA2D: "Game Maker's Toolkit, How to Make a Good 2D Camera (2023)",
  GOAT: 'Goat Out playtests',
  HADES: 'Supergiant Games, Hades (2020): the dialogue screen, the gods in their light, the slash on every hit',
  'CULT OF THE LAMB': 'Massive Monster, Cult of the Lamb (2022): devotion poured into a building, a stream of it from you to the thing being raised',
  'HOLLOW KNIGHT': 'Team Cherry, Hollow Knight (2017): the world holding still and the knight flashing when a mask is lost',
  ZELDA: 'Nintendo, The Legend of Zelda: a row of hearts that empties one heart at a time',
  'MAX PAYNE / HOTLINE': 'Max Payne (2001) bullet time; Hotline Miami (2012), slow motion on the aim',
  SPELUNKY: 'Spelunky (2008), jumping on a man’s head to get over him',
  'Enter the Gungeon': 'Enter the Gungeon (2016), rooms whose furniture is a weapon: chandeliers, tables, armour, barrels',
};

const JUICE = [
  // ---- the camera ----
  { name: 'Hitstop', cat: 'TIME', status: 'in', src: 'HITSTOP', code: 'game.hitstop · juice.hitstop · juice.hurtStop',
    trigger: 'Every kill and every lost heart (Hollow Knight\'s); smaller on door blows, parries, the pen', look: 'The whole simulation freezes for a few frames; the picture holds on the moment of contact',
    size: () => `${TUNING.juice.hitstop}s kill, +${TUNING.juice.comboHitstopMul}/combo to +${TUNING.juice.comboHitstopCap}s · ${TUNING.juice.hurtStop}s a lost heart (× stop ${TUNING.juice.stop})`,
    godot: 'Engine.time_scale = 0 then a timer that ignores time scale: await get_tree().create_timer(t, true, false, true).timeout; restore to 1. Keep UI tweens on TWEEN_PAUSE_PROCESS.' },
  { name: 'Screen shake', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.shake · juice.shakeKill/shakeHit/shakeDecay',
    trigger: 'A heart lost; and, smaller and fading with distance, the thuds of the world (game.thud). Every other call site is × juice.shakeOther, which is 0',
    look: 'Random offset of the whole picture that decays, the one thing that says you were hit without your looking at the hearts',
    size: () => `${TUNING.juice.shakeHit}px hurt · ×${TUNING.juice.shakeOther} for anything else · decays ×${TUNING.juice.shakeDecay}/s`,
    godot: 'Trauma model: trauma += amt (clamp 0..1); Camera2D.offset = max_offset * trauma² * FastNoiseLite sample; trauma -= decay * delta. Noise, not randf, so it does not jitter.' },
  { name: 'Directional kick', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.kick · juice.kick/kickMax/kickDecay',
    trigger: 'Headbutt landing, kills, clubs taken', look: 'The picture is shoved along the blow and springs back, a punch, not a rattle',
    size: () => `${TUNING.juice.kick}px, capped ${TUNING.juice.kickMax}px, ×${TUNING.juice.kickOther} unless the goat was hit, decay ×${TUNING.juice.kickDecay}/s`,
    godot: 'A second Camera2D.offset term: kick_vec += dir * amt; kick_vec = kick_vec.lerp(Vector2.ZERO, 1 - exp(-decay * delta)). Add to the shake offset.' },
  { name: 'Zoom punch', cat: 'CAMERA', status: 'in', src: 'JUICE', code: 'game.zoomPunch · juice.zoomKick/zoomDecay',
    trigger: 'Kills, the wraith unmade, bombs', look: 'The lens shoves in a few percent and settles back',
    size: () => `+${Math.round(TUNING.juice.zoomKick * 100)}% · settles ×${TUNING.juice.zoomDecay}/s`,
    godot: 'create_tween().tween_property(camera, "zoom", base * (1 + k), 0.04) then .tween_property(camera, "zoom", base, 0.25).set_trans(Tween.TRANS_EXPO).set_ease(Tween.EASE_OUT).' },
  { name: 'Camera lead', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.camLead · camera.lead/leadLerp',
    trigger: 'Always, toward the aim and scaled by run speed', look: 'The view looks ahead of the goat, not at him',
    size: () => `${TUNING.camera.lead}px ahead · lerp ${TUNING.camera.leadLerp}`,
    godot: 'Camera2D child of the player with its own script: target = player.global_position + aim * lead; position = position.lerp(target, 1 - exp(-rate * delta)).' },
  { name: 'Deadzone camera', cat: 'CAMERA', status: 'in', src: 'SWINK', code: 'game.camFollow · camera.deadzone/fitMargin',
    trigger: 'Standing still, or in a room that fits the screen', look: 'Small motion never re-centres the picture; a small room holds still',
    size: () => `${TUNING.camera.deadzone}px deadzone`,
    godot: 'Camera2D.drag_horizontal_enabled / drag_vertical_enabled with drag margins; a room-sized Area2D can set limit_* to lock a small room.' },
  // From GMTK's "How to Make a Good 2D Camera" (26 Sep 2026 review). Lookahead, damping, the
  // deadzone, the room lock, the kick and the zoom punch were already in; these are what it had that we do not.
  { name: 'Shake off noise, not dice', cat: 'CAMERA', status: 'new', src: 'CAMERA2D', code: 'Game.shakeNoise · juice.shakeFreq/shakeRef',
    trigger: 'The one shake there is: a heart lost', look: 'A smooth rattle that wanders instead of a new random spot every frame; strength goes as trauma² so a small hit is a nudge and a big one a jolt',
    size: () => `${TUNING.juice.shakeFreq} Hz · trauma² against ${TUNING.juice.shakeRef}px, never above the old peak`,
    godot: 'FastNoiseLite sampled at time * freq for x and y (different seeds); offset = max * trauma * trauma * noise.' },
  { name: 'Frame the fight', cat: 'CAMERA', status: 'new', src: 'CAMERA2D', code: 'game.fightFocus · camera.fight',
    trigger: 'A boss or sealed arena that does not fit the screen', look: 'The follow point is pulled part way toward the boss, and the lens backs out a little, so he and the wall behind him are both in the picture, the wall is the weapon (pillar 3)',
    size: () => { const F = TUNING.camera.fight; return `pull ${Math.round(F.pull * 100)}% (max ${F.max / TILE} tiles) · zoom ×${F.zoom} · ease ${F.ease}/s`; },
    godot: 'Camera target = lerp(player, boss, w); zoom tweened to fit both with a margin; drop back on the boss down.' },
  { name: 'Threat pull', cat: 'CAMERA', status: 'backlog', src: 'CAMERA2D', code: 'game.camLead (not built)',
    trigger: 'An aware man in the goat\'s room just outside the view (a rifle aiming, a hound winding up)', look: 'The lead leans a little toward him, the Gungeon / Nuclear Throne weighting of points of interest',
    size: () => 'at most a third of camera.lead, only while he is winding up',
    godot: 'Sum of attractor offsets (weight / distance) added to the aim lead before the lerp, clamped.' },
  { name: 'Leash at speed', cat: 'CAMERA', status: 'new', src: 'CAMERA2D', code: 'game.updateCamera · camera.leash',
    trigger: 'A roll, a leapfrog, the goat flung by a blast', look: 'Past the leash the camera closes the gap hard (leashLerp) so he never nears the screen edge; normal walking and room changes never touch it',
    size: () => `${Math.round(TUNING.camera.leash * 100)}% of the half-view from centre`,
    godot: 'After the lerp: if (cam - target).length() > leash, cam = target + dir * leash.' },
  { name: 'World thud', cat: 'CAMERA', status: 'new', src: 'GOAT', code: 'game.thud · juice.shakeThud/thudNear/thudFar',
    trigger: 'The ogre or rat ogre landing, a bomb, a barrel going up, a poison blast', look: 'A small shake that tells weight, full close by and gone off-screen; always under a lost heart',
    size: () => `× ${TUNING.juice.shakeThud} of the call · full inside ${TUNING.juice.thudNear} tiles, none past ${TUNING.juice.thudFar}`,
    godot: 'add_trauma(amount * clamp(inverse_lerp(far, near, distance), 0, 1)) on the camera.' },
  { name: 'Room blend', cat: 'CAMERA', status: 'new', src: 'CAMERA2D', code: 'game.camHold/camTrack/camRoomMid · Game.roomMouthDist · camera.blend/blendIn/holdLerp',
    trigger: 'Walking into a room that fits the screen, or toward its way out', look: 'No switch: in a doorway the picture is on him as in the corridor, and it slides to the middle of the room as he walks in, never a jump between room one and room two',
    size: () => `held from ${(TUNING.camera.blendIn / TILE).toFixed(1)} to ${(TUNING.camera.blendIn / TILE + TUNING.camera.blend).toFixed(1)} tiles in from the nearest doorway, smoothstepped, eased at ${TUNING.camera.holdLerp}/s`,
    godot: 'Camera2D target = lerp(player_follow, room_center, smoothstep(dist_to_nearest_door / blend)); no Area2D toggle.' },
  { name: 'Shake setting', cat: 'CAMERA', status: 'new', src: 'CAMERA2D', code: 'SETTINGS shake · game.shakeMul',
    trigger: 'The player\'s choice on the title', look: 'A SCREEN SHAKE slider (full as tuned, down to still) over shake, kick and lens punch, an accessibility switch every camera talk asks for',
    size: () => `0..1 × juice.screen (${TUNING.juice.screen})`,
    godot: 'A ConfigFile value multiplied into the trauma amount.' },
  { name: 'Slow motion on a kill', cat: 'TIME', status: 'in', src: 'SCREENSHAKE', code: 'game.slowTimer · juice.killSlow/comboSlow/deathSlow',
    trigger: 'The Butcher down, a third kill in a streak, death', look: 'Time eases to a third and back',
    size: () => `${TUNING.juice.killSlow}s boss · ${TUNING.juice.comboSlow}s combo · ${TUNING.juice.deathSlow}s death`,
    godot: 'Tween Engine.time_scale to 0.3 and back with a tween set to ignore time scale (set_ignore_time_scale(true)). Pitch music down with AudioServer bus effect, not the stream.' },
  { name: 'Aiming slow motion (COLD EYE)', cat: 'TIME', status: 'in', src: 'MAX PAYNE / HOTLINE', code: 'game.coldEye · game.aimSlow · BOONS coldeye',
    trigger: 'Anything into his mouth, with COLD EYE; ends on the throw', look: 'Time eases down and holds while he aims, the grab chip drains, one falling note',
    size: () => { const p = BOONS.find((b) => b.id === 'coldeye').params; return `×${p.scale} for ${p.time}s real · once per ${p.every}s`; },
    godot: 'Same Engine.time_scale tween, counted with a Timer whose process_callback ignores time scale; cancel it from the throw.' },
  { name: 'Caught on the teeth', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Enemy.impale · impaledStep · Renderer.drawEnemy · cave.spikes.impale',
    trigger: 'The ogre (or the rat ogre) coming down on a cave spire out of a leap or a stagger', look: 'Blood and a thud, STUCK over him; he strains in place, the tooth drawn through his feet, then tears off with a roar',
    size: () => { const I = TUNING.cave.spikes.impale; return `${I.time}s stuck × the enemy clock · shiver ${I.shiver}px · ${I.free}s stagger after`; },
    godot: 'A state in the ogre state machine that zeroes velocity; the sprite offset.x = sin(t*38)*shiver; draw the spike as a separate Sprite2D with a higher z_index than the ogre while stuck.' },
  { name: 'The vault (LEAPFROG)', cat: 'BODY', status: 'in', src: 'SPELUNKY', code: 'Goat.leapTarget · goat.leap · PaintedArt.drawGoat',
    trigger: 'A roll at a man in front, with LEAPFROG', look: 'He lifts off his shadow in a stretched arc, a knock and a puff off the man\'s back at the top, lands on four feet',
    size: () => { const p = BOONS.find((b) => b.id === 'leapfrog').params; return `${p.height}px high · ${p.time}s in the air · ${p.behind} tile past him`; },
    godot: 'Sprite2D offset.y = -sin(t/T*PI)*h on a child, shadow Sprite2D scaled by the same curve; the body moves on a straight line with collision_mask off for enemies until it lands.' },
  // ---- the screen ----
  { name: 'Screen flash', cat: 'SCREEN', status: 'in', src: 'JUICE', code: 'game.flash · juice.flashDecay',
    trigger: 'Kills (blood), witchfire, a soul, reaching the stairs', look: 'An additive colour wash over the picture that fades fast',
    size: () => `0.1–0.4 alpha · fades ×${TUNING.juice.flashDecay}/s`,
    godot: 'CanvasLayer > ColorRect (full rect), material blend_mode ADD; tween modulate.a from amt to 0.' },
  { name: 'Hurt direction arc', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'game.hurtFlash · drawHurt',
    trigger: 'Taking a hit', look: 'A red arc at the edge of the screen pointing back at whoever hit you',
    size: () => '0.6s',
    godot: 'TextureRect arc on a CanvasLayer, rotation = angle to attacker; tween modulate.a.' },
  { name: 'Hurt vignette', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'drawHurtVignette · juice.hurtVignette',
    trigger: 'Taking a hit', look: 'Every corner reddens and fades',
    size: () => `${TUNING.juice.hurtVignette.life}s · ${TUNING.juice.hurtVignette.alpha} alpha`,
    godot: 'Full-screen ColorRect with a radial-gradient shader (smoothstep on distance from UV centre), uniform intensity tweened.' },
  { name: 'Last-heart heartbeat', cat: 'SCREEN', status: 'new', src: 'GMTK', code: 'drawHeartbeat · juice.heartbeat',
    trigger: 'Down to the last heart', look: 'The screen edge pulses red lub-dub, and the last heart on the HUD throbs with it',
    size: () => `${TUNING.juice.heartbeat.bpm} bpm · ${TUNING.juice.heartbeat.alpha} alpha · heart ±${Math.round(TUNING.juice.heartbeat.throb * 100)}%`,
    godot: 'Same vignette shader; drive intensity from an AnimationPlayer loop (two keys close together, then a rest). Pair with a low-pass on the music bus.' },
  { name: 'Rumble', cat: 'SCREEN', status: 'in', src: 'SWINK', code: 'game.vibe',
    trigger: 'Hits, kills, throws, touch devices only', look: 'The phone buzzes, scaled to the blow',
    size: () => '6–80 ms',
    godot: 'Input.start_joy_vibration(0, weak, strong, dur) for pads; Input.vibrate_handheld(ms) on mobile.' },
  // ---- bodies ----
  { name: 'Hit flash (white)', cat: 'BODY', status: 'new', src: 'SCREENSHAKE', code: 'enemy.flash · juice.hitFlash · drawEnemy',
    trigger: 'A headbutt lands on a man (and every Butcher blow)', look: 'He is repainted as a solid white silhouette for a few frames',
    size: () => `${TUNING.juice.hitFlash}s`,
    godot: 'CanvasItem shader: uniform float flash; COLOR.rgb = mix(texture(TEXTURE, UV).rgb, vec3(1.0), flash); keep alpha. Tween flash 1 → 0. Use a per-instance uniform (instance uniform float flash) so one material serves all.' },
  { name: 'Windup tint', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.windupGlow · juice.windupTint · drawEnemyBody',
    trigger: 'Any man in a telegraph: a club or blade windup, the butcher\'s hook, the ogre\'s slam and leap, the rat ogre\'s, a hound\'s plant, a seer\'s cast, a rifle\'s aim',
    look: 'His own sprite goes lighter and warmer as the blow comes, faint at first and bright at the last frame (as in Cult of the Lamb); masked to his pixels, no glow',
    size: () => { const W = TUNING.juice.windupTint; return `up to ${W.max} alpha · ease ^${W.curve} · warm ${W.warm}`; },
    godot: 'The hit-flash shader with a second uniform: COLOR.rgb = mix(tex.rgb, warm_white, windup); set windup = pow(1 - timer / wind, curve) * max from the enemy script every frame.' },
  { name: 'Squash & stretch (poses)', cat: 'BODY', status: 'in', src: 'JUICE', code: 'drawGoat · painted-art drawGoat',
    trigger: 'Windup, lunge, roll, stun', look: 'Crouched before a headbutt, stretched through it, curled in a roll',
    size: () => 'windup 0.85×1.1 · lunge 1.15×0.92',
    godot: 'AnimationPlayer keys on Sprite2D.scale per state, or set scale in the state machine enter().' },
  { name: 'Squash spring', cat: 'BODY', status: 'new', src: 'JUICE', code: 'game.squashGoat · juice.squash',
    trigger: 'A headbutt landing, a blow taken, the end of a roll', look: 'The goat wobbles wide-and-flat then tall-and-thin and settles, like jelly',
    size: () => `hit ${TUNING.juice.squash.hit} · hurt ${TUNING.juice.squash.hurt} · ${TUNING.juice.squash.freq} rad/s, decay ${TUNING.juice.squash.decay}`,
    godot: 'create_tween().tween_property(sprite, "scale", Vector2(1+a, 1-a), 0.05) then back to Vector2.ONE over 0.3s with TRANS_ELASTIC / EASE_OUT.' },
  { name: 'Knockback', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'enemy.fling · goat.headbutt.impulse',
    trigger: 'Every headbutt, every body arriving', look: 'The man flies along the blow, spinning, the fling is the attack',
    size: () => `impulse ${Math.round(TUNING.goat.headbutt.impulse)}px/s`,
    godot: 'CharacterBody2D: velocity = dir * impulse, then friction in _physics_process; spin the sprite while velocity > threshold.' },
  { name: 'The horns wave', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawHornWave · Goat.hornHit · TUNING.goat.horns',
    trigger: 'The moment the head comes up, whichever horns he has (the SHORT, BIG, LONG; the dev drawer HORNS row)', look: 'Cells on the floor where the blow lands: a fan for the SHORT and BIG, two straight strips for LONG; pale where it shoves, bright at the front of the wave and on LONG tips, where it throws hard',
    size: () => `${TUNING.goat.horns.wave.time}s, at most ${Math.round(TUNING.goat.horns.wave.alpha * 100)}% · LONG tips x${TUNING.goat.horns.long.tipMul}, shafts x${TUNING.goat.horns.long.shaftMul}`,
    godot: 'A Node2D child of the goat with a short Tween: draw the hit shape with _draw() (a polygon for the fan, two rects for the strips) on a grid-snapped ShaderMaterial or as TileMap cells, modulate.a fades to 0; reuse the same Area2D shape the hit test uses so the picture is the hit.' },
  { name: 'The horns land', cat: 'BODY', status: 'new', src: 'HADES', code: 'Game.hornSplash · Renderer.drawSlashes · TUNING.goat.horns.splash',
    trigger: 'Every man the horns land on (LONG tips harder and gold)', look: 'A short slash of cells across the man along the blow, a hot streak down its middle, a ring of cells round him, the man white for a beat, a breath more hitstop',
    size: () => { const S = TUNING.goat.horns.splash; return `${S.life}s · ${S.len}px (tips ${S.tipLen}) · white ${S.flash}s · stop ${S.stop}s (tips ${S.tipStop}s)`; },
    godot: 'An AnimatedSprite2D slash spawned at the hit, rotated to the blow, freed on animation_finished; the enemy material flash_amount tweened 1 to 0; Engine.time_scale dip for the stop.' },
  { name: 'A heart taken, on him', cat: 'BODY', status: 'new', src: 'HOLLOW KNIGHT', code: 'Goat.damage · goat.hurtT · PaintedArt.drawGoat · Game.hurtBurst · juice.hurtLook',
    trigger: 'A heart lost (not armour, halo or a wet fleece)', look: 'He is a white silhouette for a moment, then a red one that blinks; a slash of blood-red cells across him along the blow',
    size: () => { const L = TUNING.juice.hurtLook; return `${L.life}s · white ${L.white}s · blink ${L.blink}/s · slash ${L.len}px ${L.slash}s`; },
    godot: 'A CanvasItem shader on the goat: mix(texture, flash_color, flash_amount) with flash_color white then red, flash_amount tweened; a slash sprite as for the horns.' },
  { name: 'A heart breaks', cat: 'HUD', status: 'new', src: 'ZELDA', code: 'Renderer.drawHeartBreak · juice.heartBreak',
    trigger: 'The heart row loses a heart', look: 'The lost heart swells white, splits down the middle, the halves drift apart and fall, cells of blood fly off it',
    size: () => { const B = TUNING.juice.heartBreak; return `${B.life}s · swell x${B.swell} · split at ${B.split} · ${B.bits} bits`; },
    godot: 'Two TextureRect halves of the heart icon tweened apart (position, rotation, modulate.a) and a CPUParticles2D burst at the heart.' },
  { name: 'Souls poured in', cat: 'WORLD', status: 'new', src: 'CULT OF THE LAMB', code: 'Heaven.updatePour · drawPour · heaven.home.pour',
    trigger: 'GRAB held at the broken mirror, the broken overlook or a broken stand in heaven', look: 'A white soul at a time flies off the goat in a bend into the thing, a chime each, the count over it climbing; mended, a ring and a bell',
    size: () => { const P = TUNING.heaven.home.pour; return `${P.rate} a second · ${P.fly}s in the air`; },
    godot: 'A Timer at 1/rate spawning a small Sprite2D that tweens along a Curve2D from the player to the target and frees itself; an AudioStreamPlayer per soul with a pitch step.' },
  { name: 'An escort dies', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Beast.farewell · Beast.drawFarewell · beast.farewell',
    trigger: 'One of his animals killed, fallen, or left behind by the clamp', look: 'The world slows and stops a beat, a ring and pale cells rise off it, and a plate drops over the top of the screen with the animal on it: THE PIG IS DEAD',
    size: () => { const F = TUNING.beast.farewell; return `${F.life}s · slow ${F.slow}s · stop ${F.stop}s · ${F.wisps} wisps`; },
    godot: 'A CanvasLayer panel tweened down from the top and back up after a Timer, Engine.time_scale lowered and eased back, a GPUParticles2D of rising motes at the body.' },
  { name: 'Player recoil', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'damage(kx, ky) · Butcher planted bounce',
    trigger: 'A blow taken; a headbutt into a Butcher crouching or winding a slam', look: 'The goat is shoved back the way the blow came',
    size: () => '5 tiles/s on a planted Butcher',
    godot: 'velocity += -dir * recoil on the hit; clamp with move_toward over a few frames.' },
  { name: 'Motion smear', cat: 'BODY', status: 'in', src: 'JUICE', code: 'goat.trail · goat.trail.*',
    trigger: 'Running, scaled by speed and run-up', look: 'Fading ghosts of the goat behind him',
    size: () => `life ${TUNING.goat.trail.life}s`,
    godot: 'Spawn a Sprite2D copy with the current frame every N ms, tween modulate.a to 0 and free; or a GPUParticles2D using the sprite texture with local_coords off.' },
  { name: 'Invulnerability blink', cat: 'BODY', status: 'in', src: 'GMTK', code: 'goat.invuln',
    trigger: 'After a hit and through a roll', look: 'The goat strobes at half alpha',
    size: () => `${TUNING.goat.invuln}s`,
    godot: 'AnimationPlayer toggling modulate.a on a 1/30s step while an invuln Timer runs.' },
  { name: 'Dazed stars', cat: 'BODY', status: 'in', src: 'JUICE', code: 'Renderer.starMarks / drawStars · juice.marks · enemy.dazed',
    trigger: 'The scream, the pen, a stun', look: 'Stars turn over the head, each a plus of cells, the one coming toward the camera a cell bigger; over the sprite\'s own top, not across his chest. They were smooth discs.',
    size: () => `${TUNING.juice.marks.stars} stars of ${TUNING.juice.marks.px}px cells round ${TUNING.juice.marks.rx}×${TUNING.juice.marks.ry}px, ${TUNING.juice.marks.spin} rad/s, as long as the daze`,
    godot: 'Three Sprite2Ds on a Node2D child rotated each frame; an ellipse via scale.y = 0.5, texture_filter NEAREST.' },
  { name: 'The shock mark', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawEnemyBody · juice.marks · Status.sting',
    trigger: 'POISON meets STUN: one mark for the pair', look: 'Two arms wound out from the middle a cell at a time, gold and green for the two things that made it, turning over his head. It was a stroked spiral, the one smooth line left over a man.',
    size: () => `${TUNING.juice.marks.shock} cells a turn, ${TUNING.juice.marks.turns} turns, ${TUNING.juice.marks.shockSpin} rad/s`,
    godot: 'Bake the two arms into one texture and rotate the Sprite2D; NEAREST filtering.' },
  { name: 'Rocked back', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawEnemyBody · enemyAnim.rocked',
    trigger: 'An ogre staggered (a blast, a door, a crate, a body), a shieldman braced behind his board', look: 'He is thrown back off his facing and tipped, easing home over his own count, trembling over the first part of it. It was a buzz on the spot, and the board got nothing at all.',
    size: () => `${TUNING.enemyAnim.rocked.back}px back, ${TUNING.enemyAnim.rocked.tilt} rad, trembling ${TUNING.enemyAnim.rocked.shake}px over the first ${Math.round(TUNING.enemyAnim.rocked.shakeFor * 100)}%`,
    godot: 'Tween the sprite offset along -facing and back, with a short shake track at the start.' },
  { name: 'Fire that grows on him', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Goat.update (fireK) · Renderer.goatFlame · goat.burnLook',
    trigger: 'The goat standing in flame (a burning tile, a brazier he walked into, witchfire)',
    look: 'A small flame on his body the moment he steps in, stepping up in size as the tick runs; full grown over his back and flanks is the moment a heart goes',
    size: () => { const B = TUNING.goat.burnLook; return `${B.sizes.length} sizes ${B.sizes.join('/')} over ${TUNING.goat.fireDamageInterval}s · cools ${B.cool}s/s off it`; },
    godot: 'An AnimatedSprite2D on the goat whose frame set is picked from burn_timer / interval (a few discrete sizes), its position lerped a little up the body.' },
  // ---- the world ----
  { name: 'Impact ring + sparks', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'game.impact · juice.impact',
    trigger: 'A headbutt landing', look: 'A tight bright ring at the point of contact and a star of spark streaks thrown along the blow',
    size: () => `${TUNING.juice.impact.ring} tiles · ${TUNING.juice.impact.life}s · ${TUNING.juice.impact.sparks} sparks`,
    godot: 'A one_shot GPUParticles2D (explosiveness 1, spread 45°, direction = blow) plus a ring Sprite2D tweened scale 0 → 1 and alpha 1 → 0. Pool them.' },
  { name: 'Kill shockwave', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'onKill · juice.impact.killRing',
    trigger: 'Every kill but a drop', look: 'A pale ring swells out from the body and thins away',
    size: () => `${TUNING.juice.impact.killRing} tiles · ${TUNING.juice.impact.killLife}s`,
    godot: 'Screen-space distortion shader (SCREEN_TEXTURE offset by a ring function) for the fancy version, or a ring Sprite2D.' },
  { name: 'Hoof dust', cat: 'WORLD', status: 'new', src: 'JUICE', code: 'game.dust · juice.dust',
    trigger: 'Lunge, roll start, roll landing, never plain running', look: 'Soft pale puffs kicked out behind him that swell and fade',
    size: () => `${TUNING.juice.dust.life}s · ${TUNING.juice.dust.size}→${TUNING.juice.dust.size + TUNING.juice.dust.grow}px`,
    godot: 'CPUParticles2D at the feet, one-shot burst on lunge/roll/land; scale_amount_curve rising, color_ramp alpha falling.' },
  { name: 'Muzzle flash', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'fireBullet · juice.muzzle · drawFlares',
    trigger: 'Every rifle shot', look: 'A tapering tongue of fire cells along the shot with a hot core and a short cross-flare, for a frame or two',
    size: () => `${TUNING.juice.muzzle.life}s · ${TUNING.juice.muzzle.size}px`,
    godot: 'Sprite2D at the muzzle, visible for 2 frames with random rotation; a PointLight2D pulse lights the room with it.' },
  { name: 'Aim telegraph', cat: 'WORLD', status: 'in', src: 'GMTK', code: 'drawAimTelegraph · drawTelegraph',
    trigger: 'A rifle aiming, a club winding up', look: 'A line and a wedge showing where the blow will land before it does',
    size: () => 'the windup',
    godot: 'Line2D from the shooter along aim, width and alpha tweened as the windup fills.' },
  { name: 'A blow as a body', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'PaintedArt.attackPose · enemyAnim',
    trigger: 'A man winding up, swinging and recovering', look: 'The windup coils away from the goat and crouches, trembling at the end; the swing snaps out past him with a stretch; the recover drifts home slumped',
    size: () => `coil ${TUNING.enemyAnim.windup.back}px, lunge ${TUNING.enemyAnim.swing.lunge}px, tremble from ${Math.round(TUNING.enemyAnim.windup.shakeFrom * 100)}%`,
    godot: 'AnimationPlayer on the sprite node: position and scale keys per state, eased in for the windup, out for the swing.' },
  { name: 'The swing seen', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawSwingSmear · enemyAnim.smear',
    trigger: 'A club, a board or a claw coming round', look: 'A crescent of bright amber cells sweeping the wedge the windup showed, a fading tail behind it',
    size: () => `outer ${Math.round((1 - TUNING.enemyAnim.smear.inner) * 100)}% of the reach, trail ${TUNING.enemyAnim.smear.trail} rad, ${TUNING.enemyAnim.smear.fade}s out`,
    godot: 'A Polygon2D arc built per frame from the swing progress, or a shader on a ring mesh masking by angle.' },
  { name: 'Rifle recoil', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'PaintedArt.attackPose · enemyAnim.recoil',
    trigger: 'A rifle going off', look: 'The shooter jolts back off the muzzle and settles',
    size: () => `${TUNING.enemyAnim.recoil.kick}px over ${TUNING.enemyAnim.recoil.time}s`,
    godot: 'Tween the sprite offset back along -aim and ease it home.' },
  { name: 'Knocked down, and up again', cat: 'BODY', status: 'new', src: 'GOAT', code: 'PaintedArt.knockdown · enemyAnim.down',
    trigger: 'A man floored or stunned (a headbutt, a crate, the end of a fling)', look: 'He tips over past his side and bounces back onto it, squashed as he meets the floor; lies; then rises through a crouch for the last beat before he is up. It was a snap onto his side and a snap back.',
    size: () => `over in ${TUNING.enemyAnim.down.time}s to ${TUNING.enemyAnim.down.over} rad, lies at ${TUNING.enemyAnim.down.lie}, up over the last ${TUNING.enemyAnim.down.up}s`,
    godot: 'An AnimationPlayer track on the sprite rotation and scale: back-out ease in, a squash key at the landing, an ease-out crouch at the end read off the state timer.' },
  { name: 'A body in flight', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawEnemyBody · enemyAnim.flung',
    trigger: 'A man flung by the horns, a blast, a barrel', look: 'On the beat the horns land he is squashed along the blow under the white flash; then stretched along his flight the faster he goes, spinning; a puff of dust where he comes down',
    size: () => `squash ${TUNING.enemyAnim.flung.hit}, stretch up to ${TUNING.enemyAnim.flung.stretch} at ${TUNING.enemyAnim.flung.per}px/s`,
    godot: 'Scale the sprite along its velocity (rotate, scale, rotate back) each frame; a one-shot CPUParticles2D of dust on landing.' },
  { name: 'The windup pop', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawEnemyBody · juice.windupTint.pop',
    trigger: 'The last share of every windup', look: 'The warm tint on his body jumps to bright for the last beat before the blow, so the moment to move is a flash, not the end of a fade',
    size: () => `past ${Math.round(TUNING.juice.windupTint.pop * 100)}% of the windup, at ${TUNING.juice.windupTint.popMax} alpha`,
    godot: 'A shader uniform for the tint stepped to its max when the windup timer passes the share.' },
  { name: 'The poison pool', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawPoison · status.look',
    trigger: 'Any puddle: SPLASH, VENOM JAW, SOUR TUMBLE, VENOM SPIT, a barrel of poison', look: 'One pool in cells, not an oval a tile: a dark rim bitten in along every open side, a dithered body with a sheen that comes and goes, bubbles that swell and pop into rings; dithered away as it dries. Drops off the hooves of anyone moving through it.',
    size: () => `${TUNING.status.look.cell}px cells, rim bitten ${TUNING.status.look.bite} deep, ${TUNING.status.look.bubbles} bubbles a tile every ${TUNING.status.look.bubble}s, ${TUNING.status.look.drops} drops/s`,
    godot: 'A TileMap layer with autotile terrain for the pool (bitmask edges), a shader for the dither and sheen, a CPUParticles2D for the drops.' },
  { name: 'Poisoned', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.drawEnemyBody / drawBubbles · PaintedArt.drawGoat · status.look',
    trigger: 'A man with poison in him; the goat once his ring has filled', look: 'The green is in him: his own pixels again flat venom, breathing, with bubbles in cells rising off his head and popping. The goat the same once the slow is on him.',
    size: () => `tint ${TUNING.status.look.tint} on a man, ${TUNING.status.look.goatTint} on the goat`,
    godot: 'A flat-colour modulate pass of the same sprite (a CanvasItem shader), bubbles as a small AnimatedSprite2D over the head.' },
  { name: 'Particles', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.particles · combat-fx',
    trigger: 'Blows, doors, coals, gunshots', look: 'Squares and chips flung from the contact, snapped to the world pixel grid; sparks are runs of cells along their flight',
    size: () => '0.3–0.8s',
    godot: 'GPUParticles2D one_shot, pooled; ParticleProcessMaterial with initial_velocity range and damping.' },
  { name: 'Gore and debris', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'game.gore · CombatFX.fragment/debris',
    trigger: 'Kills, broken doors and crates', look: 'Chunks with height that fly, bounce and settle, the body tears into its own sprite, each piece\'s cut its own edge pixels in blood (`effects.goreCut`)',
    size: () => `≤${TUNING.effects.maxAir} in the air`,
    godot: 'RigidBody2D pieces are too heavy; fake height with a z value per piece in one script, draw with _draw() or MultiMeshInstance2D.' },
  { name: 'Permanence (blood, bodies)', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'world.decal · DECAL_SCALE',
    trigger: 'Everything that bleeds, burns or falls', look: 'Blood, scorch and bodies stay on the floor for the whole level',
    size: () => 'the level',
    godot: 'A SubViewport with render_target_clear_mode = NEVER; draw stains into it and show it as a TextureRect under the actors.' },
  { name: 'A body that settles', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.death / corpseSprite / updateGround / pool · effects.corpse',
    trigger: 'A man killed whole (not torn, not fallen)', look: 'He carries the speed he died with, lands, skids leaving a smear, rolls onto his side square to the pixel grid, twitches, and a dark pool seeps out from under him; duller than the living, on his own silhouette for a shadow',
    size: () => `pool ${TUNING.effects.corpse.pool}px (${TUNING.effects.corpse.big} Butcher) over ${TUNING.effects.corpse.time}s · ${TUNING.effects.corpse.twitches} twitches`,
    godot: 'A Sprite2D rotated to ±90° on landing via tween; a pool Sprite2D under it scaling up with an ease-out, baked into the decal viewport when done.' },
  { name: 'Pixel fire', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.flameFrames / flame · effects.flame',
    trigger: 'Every flame: a burning tile, a brazier, a lamp, a man alight, witchfire', look: 'A looping teardrop of five flat bands (ember red to white core) whose tongues are eaten from the top by noise scrolling up through it, sparks climbing off the tip, baked once per whole-pixel size, drawn with smoothing off',
    size: () => `${TUNING.effects.flame.frames} frames at ${TUNING.effects.fireFps} fps · ${TUNING.effects.flame.wide}×${TUNING.effects.flame.tall} of its size · ${TUNING.effects.pixel}px texel`,
    godot: 'Bake the frames offline (or in a tool script) into a SpriteFrames sheet; AnimatedSprite2D with texture_filter NEAREST, frame offset per tile so neighbours never flicker in step.' },
  { name: 'Pixel blast', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.burstFrames / explosion · effects.blast',
    trigger: 'A bomb, a bomb charge, a puddle going off (green); dust for a door, a crate, a man burnt out; a spray of blood on a kill', look: 'Three phases: a solid pale flash disc with rays, a fireball of puffs in concentric bands white-hot to ember cooling from the rim in, then smoke lighter than the floor, lit from above, rising and ordered-dithered away, every cloud cut out by a one-texel dark rim. On the floor the harm radius stamped the frame it goes off and a thick shock ring racing to it; embers and charred chunks thrown, the room lit for an instant, a lens punch, no shake',
    size: () => `${TUNING.effects.blast.frames} frames over ${TUNING.effects.burstLife}s · flash to ${Math.round(TUNING.effects.blast.flashTo * 100)}%, fire to ${Math.round(TUNING.effects.blast.fireTo * 100)}% · stamp ${TUNING.effects.blast.stamp.time}s · light ×${TUNING.effects.blast.light} r for ${TUNING.effects.blast.lightFor}s · ${TUNING.effects.blast.embers} embers, ${TUNING.effects.blast.debris} chunks`,
    godot: 'A pre-baked SpriteFrames explosion (NEAREST), a PointLight2D energy tween for the flash, a one_shot CPUParticles2D of embers, and a ring Sprite2D on the floor layer.' },
  { name: 'Soot column', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.explosion · effects.blast.soot',
    trigger: 'Every blast, once the fireball has burnt out', look: 'A second, darker cloud that starts a beat late above the blast and goes on rising and dithering away after it',
    size: () => `×${TUNING.effects.blast.soot} r, from ${TUNING.effects.blast.sootAfter}s for ${TUNING.effects.blast.sootLife}s`,
    godot: 'A second AnimatedSprite2D started on a Timer, drifting up with a Tween.' },
  { name: 'A barrel that rolls', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Prop.roll / updateBarrel / oilBurst · PaintedArt.drawProp · prop.barrel',
    trigger: 'A headbutt or a thrown body into a barrel; flame under it or a burning man against it', look: 'It goes over onto its side and rolls end for end in whole quarter turns; every man it meets flashes and is bowled aside with a small kick of the camera; lit, one flame sits on it and a standing one shivers harder as the fuse runs down, then a blast and a pool of fire',
    size: () => `rolls ${(TUNING.prop.barrel.roll / TILE).toFixed(0)} tiles/s · fuse ${TUNING.prop.barrel.fuse}s · burst ${TUNING.prop.barrel.burst} tiles for ${TUNING.prop.barrel.burstTime}s`,
    godot: 'A CharacterBody2D with move_and_collide and a linear damp; two lying frames flipped every quarter turn of travel; a Timer for the fuse driving a shake tween and a flame child, then the blast scene.' },
  { name: 'Floating words', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.floatText',
    trigger: 'Door counts, COALS, combo ×N', look: 'Stamped caps that rise and fade',
    size: () => '1.2s',
    godot: 'Label scene spawned at the point, tween position.y -= 30 and modulate.a → 0, then queue_free.' },
  { name: 'Combo counter', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.combo · juice.comboWindow',
    trigger: 'Kills inside the window', look: '×N grows with the streak',
    size: () => `${TUNING.juice.comboWindow}s window`,
    godot: 'Autoload counter with a Timer; the label scales with a TRANS_BACK tween on each increment.' },
  { name: 'Barks', cat: 'WORLD', status: 'in', src: 'GOAT', code: 'game.bark · BARKS',
    trigger: 'Seeing, losing, panicking', look: 'A dark plate over a man\'s head with a line',
    size: () => '< 2s, global gap',
    godot: 'A Label over the head plus a global cooldown in an autoload so a crowd never talks at once.' },
  // ---- sound ----
  { name: 'Layered sound per hit', cat: 'SOUND', status: 'in', src: 'SCREENSHAKE', code: 'GameAudio sfx*',
    trigger: 'Every verb', look: 'Thud + bleat + steel stacked per event',
    size: () => '-',
    godot: 'AudioStreamRandomizer with random_pitch and random_volume_offset_db; several AudioStreamPlayer2Ds per event.' },
  { name: 'No two takes alike', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.foley · js/foley.js',
    trigger: 'Every effect', look: 'Physical models rendered in a few takes; one picked, nudged in pitch and level',
    size: () => `${TUNING.audio.foley.takes} takes, ±${Math.round(TUNING.audio.foley.pitch * 100)}% pitch, ±${Math.round(TUNING.audio.foley.level * 100)}% level`,
    godot: 'Bake the takes to .wav once; AudioStreamRandomizer (PLAYBACK_RANDOM_NO_REPEATS) with random_pitch and random_volume_offset_db.' },
  { name: 'A stone room', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'Foley.roomImpulse · TUNING.audio.room',
    trigger: 'Always', look: 'Every effect and a little of the score through one short dark reverb; loud things send more',
    size: () => `${TUNING.audio.room.decay}s tail`,
    godot: 'AudioEffectReverb on a Room bus (room_size ~0.35, damping ~0.7, wet ~0.3), SFX and Music buses sending to it.' },
  { name: 'Heard from where it is', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.heard · Enemy.updateDog',
    trigger: 'A hound barking as it runs', look: 'Quieter with distance, panned to its side of the goat',
    size: () => `whole to ${TUNING.audio.space.near} tiles, ${Math.round(TUNING.audio.space.floor * 100)}% at ${TUNING.audio.space.far}`,
    godot: 'AudioStreamPlayer2D on the hound (max_distance, attenuation), the AudioListener2D on the goat.' },
  { name: 'Reactive music', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.updateScene · MUSIC.md',
    trigger: 'Who is in the room, spotted / chase / combat', look: 'The score thickens with the room: each kind its own figure, one hit a man',
    size: () => `16-bar transport · ${TUNING.audio.layers.maxPerFamily} a family`,
    godot: 'AudioStreamInteractive (4.3+) with clips per stage and transitions on beat, or AudioStreamSynchronized layers with volume per layer.' },
  { name: 'The fight starting', cat: 'SOUND', status: 'in', src: 'GOAT', code: "encounterStage · musicEvent('spotted')",
    trigger: 'Somebody in the room knows where he is', look: 'One frame-drum hit and a low plucked root on the next sixteenth, then the two-bar warning',
    size: () => `gain ${TUNING.audio.layers.spottedGain}`,
    godot: 'On the detection signal, play a one-shot on the music bus quantised to the next 16th of the AudioStreamInteractive clock.' },
  { name: 'The blow under water', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.hurtDip · setScoreTone · audio.tone',
    trigger: 'A heart lost; the last heart', look: 'The score (not the effects) dips to a muffle and comes back; on the last heart it stays muffled',
    size: () => `${TUNING.audio.tone.hurt} Hz dip, back over ${TUNING.audio.tone.back}s · ${TUNING.audio.tone.heart} Hz on the last heart`,
    godot: 'AudioEffectLowPassFilter on the Music bus; tween cutoff_hz down and back on the hurt signal.' },
  { name: 'The heart you hear', cat: 'SOUND', status: 'in', src: 'GMTK', code: 'GameAudio.heartbeat · Foley heart',
    trigger: 'Down to the last heart', look: 'A soft lub-dub under the ribs, in time with the red at the screen edge',
    size: () => `${TUNING.juice.heartbeat.bpm} bpm · dub ${TUNING.audio.ambience.heart.dub} of the lub`,
    godot: 'AudioStreamPlayer fired from the same AnimationPlayer track that pulses the vignette.' },
  { name: 'The room\'s own sound', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.updateAmbience · Foley.loop · audio.ambience',
    trigger: 'Always, on a floor', look: 'Still air, a cave\'s hollow or wind by canon; the nearest fire crackling from its side; drips; the cult drumming far off; the milk grass when hurt. Under a fight all of it steps back and the drips stop',
    size: () => `bed ${TUNING.audio.ambience.gain} · fire within ${TUNING.audio.ambience.fire.radius} tiles · ${TUNING.audio.ambience.fight} of it in a fight`,
    godot: 'A looping AudioStreamPlayer per bed crossfaded on level load; AudioStreamPlayer2D crackle on each brazier (max_distance ~7 tiles). The fight duck is a tween on the Ambience bus volume.' },
  { name: 'A death above everything', cat: 'SOUND', status: 'new', src: 'GOAT', code: 'GameAudio.sfxDeath / spotlight · keyBus · Foley death · audio.spotlight',
    trigger: 'A man killed (not over an edge; the wraith gets only the quiet round it)',
    look: 'His own sound, a bright bone crack, the one muffled log stroke every death shares, the air knocked out of him, the wet, then his weight hitting the floor (heavier for a big man), then his last breath, on a bus nothing ducks, while the score, the other effects and the room dip for a beat. An ogre or a chain dips deeper and longer',
    size: () => { const S = TUNING.audio.spotlight; return `score ${S.duck.score} · sfx ${S.duck.sfx} · room ${S.duck.amb} · ${S.attack}s in, ${S.hold}s held, ${S.release}s out`; },
    godot: 'A Kills bus outside a Duck group; on a kill tween the Music/SFX/Ambience buses down and back (or an AudioEffectCompressor sidechained to Kills on each).' },
  { name: 'One sound, not a wall of it', cat: 'SOUND', status: 'new', src: 'GOAT', code: 'GameAudio.foley · audio.foley.stack',
    trigger: 'The same sound fired several times in one moment (a bomb\'s splats, a supper landing, three doors)',
    look: 'Each copy after the first is quieter, and past a few it is not played',
    size: () => { const S = TUNING.audio.foley.stack; return `within ${S.window}s · ×${S.mul} a copy · at most ${S.max}`; },
    godot: 'max_polyphony on the AudioStreamPlayer, plus volume_db lowered by the number of voices already playing.' },
  // ---- the backlog ----
  { name: 'Input buffer', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'Goat.update · buttBuf / rollBuf · goat.buffer',
    trigger: 'Pressing headbutt while busy, or roll before it is back', look: 'Nothing visible, the press is remembered and fires the frame he is free',
    size: () => `${TUNING.goat.buffer}s window`,
    godot: 'Store the press time; in the state machine, on entering idle, consume it if Time.get_ticks_msec() - pressed < window. Not a cancel: the recovery is still eaten in full (pillar 4).' },
  { name: 'Door-hit forgiveness', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'headbuttHits · door.reachSlack',
    trigger: 'A headbutt at a door', look: 'A door takes the blow from its ends and from flush in a wall',
    size: () => `+${TUNING.prop.door.reachSlack}px reach, cone widened for doors`,
    godot: 'Give the hurtbox a margin bigger than the collision shape (a second Area2D), the "coyote" of melee.' },
  { name: 'Hit direction on the body', cat: 'BODY', status: 'backlog', src: 'SCREENSHAKE',
    trigger: 'A man taking a blow', look: 'His sprite leans away from the blow for a few frames before the fling',
    size: () => '0.1s',
    godot: 'Tween sprite.skew or rotation by ±0.2 toward -blow and back.' },
  { name: 'Shell casings', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'game.fireBullet · CombatFX.fragment · effects.shell',
    trigger: 'A rifle shot', look: 'A brass case pops out of the side of the breech, bounces once and stays on the floor',
    size: () => `${TUNING.effects.shell.w}×${TUNING.effects.shell.h}px, permanent`,
    godot: 'One-shot particle with a height fake; on land, stamp into the decal SubViewport.' },
  { name: 'Chromatic kick', cat: 'SCREEN', status: 'backlog', src: 'JUICE',
    trigger: 'A big kill or a bomb', look: 'The red and blue channels split apart for a frame',
    size: () => '0.08s, 3px',
    godot: 'Screen shader on a BackBufferCopy: sample SCREEN_TEXTURE at UV ± offset for r and b.' },
  { name: 'Room-clear sting', cat: 'SOUND', status: 'new', src: 'GMTK', code: "game.onKill · musicEvent('cleared') · playMusicEvents",
    trigger: 'The last man of a room goes down', look: 'Three notes up the scale to the octave, half a beat after the kill accent',
    size: () => `4 steps, gain ${TUNING.audio.layers.clearGain}`,
    godot: 'Signal from the room when its enemy group empties; play a one-shot on the music bus quantised to the beat.' },
  { name: 'Anticipation on the goat', cat: 'BODY', status: 'new', src: 'SWINK', code: 'drawGoat · goat.feel.pull',
    trigger: 'Headbutt windup', look: 'A tiny pull-back opposite the aim before the lunge, eased in over the windup',
    size: () => `${TUNING.goat.feel.pull}px over ${TUNING.goat.headbutt.windup}s`,
    godot: 'Offset the sprite by -aim * 3 during windup via tween, snap forward on lunge.' },
  { name: 'Idle life', cat: 'BODY', status: 'new', src: 'JUICE', code: 'Goat.update fidget · drawGoat · goat.idle / goat.breathe',
    trigger: 'Standing still', look: 'Breathing, and after a moment a fidget now and then: a glance one facing aside, a little pronk, a head shake, a hoof pawing the floor with a puff of dirt',
    size: () => `breath ${TUNING.goat.breathe.period}s · first fidget after ${TUNING.goat.idle.after}s, then every ${TUNING.goat.idle.gap.join('–')}s`,
    godot: 'AnimationPlayer idle loop; a Timer with a random wait_time picks one of a few one-shot fidget animations; any input stops it.' },
  { name: 'Weight in the stride', cat: 'BODY', status: 'new', src: 'SWINK', code: 'Goat.update (lean) · drawGoat · goat.feel',
    trigger: 'Running, starting, stopping, turning', look: 'He leans into a change of pace and a little forward at full stride, and hops a pixel per hoof-fall in step with the walk frames',
    size: () => `lean ${TUNING.goat.feel.lean} rad + ${TUNING.goat.feel.run} running · bob ${TUNING.goat.feel.bob}px`,
    godot: 'Sprite rotation = lerp toward accel.x / max_accel * lean; offset.y = -abs(sin(frame * PI / 2)) * bob.' },
  { name: 'Kick-off, settle and skid', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'Goat.update · goat.feel.kick/stop/skid/turnGrip',
    trigger: 'Setting off from still, letting go at speed, asking back against your own run', look: 'A stretch and a puff behind on a start, a squash on a stop; a reversal grips harder, squashes him and sprays dirt ahead',
    size: () => `reversal grip ×${TUNING.goat.feel.turnGrip} · skid squash ${TUNING.goat.feel.skid.squash}, ${TUNING.goat.feel.skid.dust} puffs, once per ${TUNING.goat.feel.skid.gap}s`,
    godot: 'In _physics_process: if input.dot(velocity) < -0.3, multiply acceleration and emit a one-shot GPUParticles2D at the feet.' },
  // ---- the shop (js/shop.js) ----
  { name: 'The rat ogre comes out', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Shop.spawnOgre · ratogre.emerge',
    trigger: 'The third blow on the mouse or her shelf', look: 'Stone out of the hole, a blood ring, the picture shoved away from the wall, a beat of slow motion, and he scales up out of the gap',
    size: () => `${TUNING.ratogre.emerge}s emerge · hitstop ${TUNING.ratogre.emergeFx.hitstop} · slow ${TUNING.ratogre.emergeFx.slow}s · zoom ${TUNING.ratogre.emergeFx.zoom} · no shake (only a lost heart shakes: juice.shakeOther ${TUNING.juice.shakeOther})`,
    godot: 'Spawn at the gap with scale 0.4→1 over a tween; Engine.time_scale 0.5 for 0.35s; camera trauma 0.6; a one-shot particle burst of stone.' },
  { name: 'A blow that does nothing', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Goat.headbuttHits (ratogre) · Shop.ogreShrug',
    trigger: 'Horns on the rat ogre standing', look: 'The goat bounces off him, ash off the impact, no flash on him; once a run, the words for what would work',
    size: () => `${TUNING.ratogre.bounce} tiles/s bounce · no shake (juice.shakeOther ${TUNING.juice.shakeOther})`,
    godot: 'On hit with no damage: knock the player back along -aim, small shake, skip the hit-flash shader; show the hint label once per run.' },
  { name: 'The blink', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Shop.blink · CAPES symbols',
    trigger: 'Q, with the CLOAK OF SIGNS on his back', look: 'Violet burst where he left and where he arrives, two rings, five ghosts along the line, dust at both ends, a squash on landing',
    size: () => `${TUNING.goat.trail.fastLife}s ghosts · ring 1.2 tiles · ${TUNING.juice.squash.land} squash`,
    godot: 'Teleport the body; spawn a GPUParticles2D burst at both points; push 5 sprite ghosts along the segment with staggered lifetimes; play the landing squash tween.' },
  { name: 'The boomerang', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Shop.throwBoomerang / updateBoomerang · Renderer.drawBoomerang',
    trigger: 'Q, with the BONE MANTLE on his back', look: 'A bent stick spinning out along the aim with a short smear behind it, a thud and a flash on each man it takes, and it curves home',
    size: () => `${(TUNING.shop.boomerang.speed / TILE).toFixed(0)} tiles/s · spin 22 rad/s · hitstop 0.02 a man`,
    godot: 'A Node2D with a rotating Sprite2D and a Line2D trail; outward leg on a straight velocity, return leg steers to the player each frame; Area2D body_entered applies the stun once per body.' },
  { name: 'The ruin (CAPE OF RUIN)', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Cape.ruin · CAPES ruin · TUNING.cape.ruin',
    trigger: 'Q, with the CAPE OF RUIN on his back', look: 'A blood ring out to the shock\'s edge and an ember ring inside it, ash and blood thrown out, every crate, barrel and plank door in reach breaking, men thrown, a thud, a short hitstop and a squash',
    size: () => `${CAPES.find((c) => c.id === 'ruin').params.r} tiles · thud ${TUNING.cape.ruin.shake} · ${TUNING.cape.ruin.parts} cells of ash`,
    godot: 'An Area2D circle query on the press: break props, apply impulses to bodies; a ring Sprite2D with a radial fill shader, GPUParticles2D burst, camera shake by distance.' },
  { name: 'The tuft (SHEPHERD\'S MANTLE)', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Cape.sprout · CAPES meadow',
    trigger: 'Q, with the SHEPHERD\'S MANTLE on his back', look: 'A tuft of milk grass a tile ahead, a small green ring and a puff of green cells, a bleat',
    size: () => `${CAPES.find((c) => c.id === 'meadow').params.ahead} tile ahead · ring 0.9 tiles`,
    godot: 'Instance the grass scene at a free cell ahead of the player; one-shot ring + particles.' },
  { name: 'Taking from the mouse', cat: 'UI', status: 'new', src: 'GOAT', code: 'Shop.buy',
    trigger: 'Grab on one of her three offers', look: 'A ring and a burst in the talisman’s own colour off the stool (or her pail of milk set down in a puff of white), the name floats over the goat, the bell rings, the rest go back into the wall in a puff of ash, and her gate gives',
    size: () => 'ring 1.6 tiles · 14 particles · bell · 8 ash',
    godot: 'On take: ring tween + particle burst tinted by item colour; float label; play the bell; free the other ware with a small ash burst; open the gate door.' },
  { name: 'The veil', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'game.updateClamps · Renderer.drawUnseen · Renderer.drawVeil',
    trigger: 'A room two behind the goat with nobody alive in it', look: 'The room goes black and a breathing curtain of dark with violet threads hangs across the mouth of its way out; a low drawn breath if it is near',
    size: () => `fades in over ${(TUNING.clamp.slam * 3).toFixed(2)}s · heard within ${TUNING.clamp.hear} tiles`,
    godot: 'Swap the mouth tiles to wall in the TileMap; a black ColorRect over the room faded in with a tween; a shader-driven curtain Sprite2D across the mouth (scrolling noise, violet threshold lines).' },
  { name: 'Hound run line', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Enemy.planDash · Renderer.drawDashPaths · dog.windup/dashSpeed/dashTime',
    trigger: 'A hound plants to run at the goat, and while it runs', look: 'A wide red smear with a dashed bright line and an arrowhead along the bent path it will take, brightening across the charge',
    size: () => `${TUNING.dog.windup}s charge · ${(TUNING.dog.dashSpeed * TUNING.dog.dashTime / TILE).toFixed(1)} tiles`,
    godot: 'Line2D fed each frame from a simulated path (Curve2D baked points), width_curve fat to thin, modulate alpha tweened up over the windup.' },
  { name: 'Butcher hook line', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Enemy.hookStep · hookLead · Renderer.drawHookLine · drawHooks · champion.hook',
    trigger: 'The butcher plants to throw his hook, while it flies, and while it drags what it caught', look: 'A thin dashed amber line on the floor to where the hook will land, crawling outward and brightening, four cells marking the spot; then a thin rope from his hand to a few iron cells of hook, taut while it pulls',
    size: () => { const H = TUNING.champion.hook; return `${H.wind}s windup · ${H.min}-${H.max} tiles · ${(H.speed / TILE).toFixed(0)} tiles/s · pull ${(H.pull / TILE).toFixed(0)} tiles/s`; },
    godot: 'Line2D with a dashed texture (texture_mode TILE, UV scrolled) from the butcher to the aim point, modulate alpha tweened up over the windup; the rope a two-point Line2D updated each frame, the hook a small Sprite2D rotated to the rope.' },
  { name: 'Soul fanfare', cat: 'UI', status: 'new', src: 'GOAT', code: 'Renderer.drawSoulFanfare · game.boonT · fanfare',
    trigger: 'A soul picked up: the cards come up', look: 'A pale flash, a wheel of gold and violet pixel rays turning behind the soul, the soul springing in, A SOUL bouncing up in gold, pixel confetti bursting and falling; then the cards spring in one after another and the rays settle to a glow',
    size: () => `${TUNING.fanfare.intro}s before the cards · ${TUNING.fanfare.rays} rays · ${TUNING.fanfare.sparks} sparks · cards ${TUNING.fanfare.stagger}s apart`,
    godot: 'A CanvasLayer: a rotating Polygon2D fan with a nearest-filtered low-res SubViewport, a CPUParticles2D burst with gravity, a Label tweened with TRANS_BACK, card Controls tweened in with a stagger.' },
  { name: 'Soul into the goat', cat: 'UI', status: 'new', src: 'GOAT', code: 'Game.watchBoonMorph · Codex.drawBoonGoat / drawPull / drawMorphRing · fanfare.morph',
    trigger: 'The soul cards up and a card first pointed at (mouse over it, a finger on it, a pad\'s lit card)', look: 'The soul, hanging and bobbing where he will stand, is swallowed: it shrinks and turns into his middle while violet cells spiral in from round him; he springs up out of it as a pale violet shape, steps through violet to his own colours, a ring of cells goes out and the rays flare once. He stays after that',
    size: () => `${TUNING.fanfare.morph.time}s · ${TUNING.fanfare.morph.cells} cells · springs from ${TUNING.fanfare.morph.pop} of his height`,
    godot: 'An AnimationPlayer on the card screen: the wisp scaled down along an ease-in curve, GPUParticles2D with an attractor at the goat, the goat TextureRect with a flat-colour shader whose mix steps 1, 0.75, 0.5, 0.25, 0, and a ring of particles.' },
  { name: 'Ogre slam ring', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawSlamRing · Enemy.quake · butcher.slam',
    trigger: 'The ogre, close in, raises both fists to bring them down on the floor', look: 'A bone ring on the floor at the reach of the slam, filling red from the middle; on the blow two rings and dust; the picture shakes only if it cost the goat a heart',
    size: () => `${TUNING.butcher.slam.range} tiles · ${TUNING.butcher.slam.wind}s`,
    godot: 'A floor decal Sprite2D ring with a radial fill shader (progress uniform), then a one-shot ring particle and camera shake on the hit.' },
  { name: 'Talisman: parry', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Talisman.parryFx · mirror.window',
    trigger: 'A blow, bite or round arrives inside MIRROR SHARD\'s window', look: 'A pale ring round the goat, a violet-white spark burst at the blow, PARRIED, a steel note and a short hitstop',
    size: () => `${ARTIFACTS.find((a) => a.id === 'mirror').tiers[0].params.window}s window, COMMON`,
    godot: 'Area2D parry window timer; on overlap spawn a ring Sprite2D + GPUParticles2D burst, Engine.time_scale dip for 60 ms.' },
  { name: 'Talisman: echo', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Talisman.updateEchoes · echo.delay',
    trigger: 'A headbutt with ECHO HORN worn', look: 'A pale outline of the goat and his horns lunging again where the blow landed',
    size: () => `${ARTIFACTS.find((a) => a.id === 'echo').tiers[0].params.delay}s after`,
    godot: 'Delayed ghost Sprite2D with additive blend at the lunge end point, a shape cast for the hit.' },
  { name: 'Death-map skulls', cat: 'UI', status: 'new', src: 'GOAT', code: 'game.killMarks · Renderer.skullMark · deathCam.skull',
    trigger: 'The death screen pulls back over the level', look: 'A small bone skull on a dark rim wherever a man went down, alongside the red line of the run',
    size: () => `${TUNING.deathCam.skull}px`,
    godot: 'Sprite2D per kill position on a CanvasLayer overlay scaled against camera zoom.' },
  { name: 'Last-heart blood trail', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Goat.update · goat.bleed',
    trigger: 'Running on the last heart', look: 'A dark drop on the floor behind him every so often, not a stripe',
    size: () => `every ${TUNING.goat.bleed.gap}s ±${Math.round(TUNING.goat.bleed.jitter * 100)}%`,
    godot: 'Timer with randomised wait_time spawning a decal Sprite2D while hp == 1 and velocity above a threshold.' },
  { name: 'Blood in the wool', cat: 'BODY', status: 'new', src: 'GOAT', code: 'PaintedArt.wounds · goat.wounds',
    trigger: 'Every heart he has lost', look: 'One dark blot of blood on his body per missing heart, masked to the sprite so it is only ever on him, health read off the goat at a glance',
    size: () => `${TUNING.goat.wounds.r}px, +${TUNING.goat.wounds.grow} each, up to ${TUNING.goat.wounds.spots.length}`,
    godot: 'A child Sprite2D per lost heart using the goat frame as a clip mask (CanvasGroup / clip_children), shown by hp.' },
  { name: 'Ogre landing ring', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawHopMark · Enemy.hopLand / quake · ratogre.hop, butcher.leap',
    trigger: 'The rat ogre or the ogre crouching to leap, and landing', look: 'A red ring on the floor where he will come down, filling as he flies; he rises over his shadow and lands with a ring and dust (a shake only on a lost heart)',
    size: () => `${TUNING.ratogre.hop.radius} tiles, ${TUNING.ratogre.hop.wind}s crouch, ${TUNING.ratogre.hop.air}s air, ${TUNING.ratogre.hop.lift}px lift · Butcher ${TUNING.butcher.leap.radius} tiles, ${TUNING.butcher.leap.wind}s, ${TUNING.butcher.leap.air}s, ${TUNING.butcher.leap.lift}px`,
    godot: 'A Decal or a Line2D circle at the target, its fill tweened by the jump progress; the sprite offset.y = -sin(t*PI)*lift over a static shadow; camera shake on landing.' },
  { name: 'Hay about to catch', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawCatching · World.updateFire · fire.catch',
    trigger: 'Hay or grass beside a burning tile of hay or grass', look: 'Ember cells wake in the next tile and rise off it, more of them and brighter as the spread fills, so the line the fire will take is visible before it takes it',
    size: () => `up to ${TUNING.fire.catch.embers} cells of ${TUNING.fire.catch.cell}px, rising ${TUNING.fire.catch.rise}px`,
    godot: 'A GPUParticles2D ember emitter per fuel cell next to a burning one, amount_ratio driven by that neighbour\'s spread timer.' },
  { name: 'Burning grass', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawBurningGrass · World.updateFire · grass.burn/spread',
    trigger: 'Fire reaching tall grass', look: 'Each blade chars from the root and shortens, a small baked pixel flame at every tip that steps down a size as it burns; the front walks tile by tile across the patch',
    size: () => `${TUNING.grass.burn}s a tile, spreads every ${TUNING.grass.spread}s`,
    godot: 'Per-tile GPUParticles2D flame emitters on the grass TileMap layer, the blade shader lerping to char by burn progress; spread on a Timer per burning cell.' },
  { name: 'The trip wash', cat: 'SCREEN', status: 'new', src: 'GOAT', code: 'Renderer.drawTrip',
    trigger: 'The whole of THE TRIP', look: 'A three-colour gradient whose hue walks round the wheel, laid on in soft light, and glowing spores drifting up the screen on their own parallax',
    size: () => '46 spores, hue at 14°/s, gradient turning at 0.25 rad/s',
    godot: 'A full-screen ColorRect with a soft-light blend shader taking TIME for the hue; a GPUParticles2D of spores in a CanvasLayer with a parallax offset off the camera.' },
  { name: 'Eating the mushrooms', cat: 'SCREEN', status: 'new', src: 'GOAT', code: 'game.eatShrooms',
    trigger: 'Standing still over the tuft until the ring fills', look: 'A violet flash, a zoom punch, a ring and a puff of pale spores, a low bleat and two lines of warning',
    size: () => `grazed ${TUNING.shroom.eatTime}s inside ${TUNING.shroom.eatR} tiles`,
    godot: 'An Area2D on the tuft; on body_entered a screen flash (CanvasModulate tween), a camera zoom tween and a one-shot particle burst.' },
  // 1.79: the supper on the tables, and the pasture above.
  { name: 'The supper scatters', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Scatter.fromTable / burst · TUNING.scatter',
    trigger: 'A headbutt on a laid table; a body, a crate or a barrel into one; a blast near one', look: 'The food flies off in arcs, a shadow under each piece, each bounce lower, rolling to rest on a quarter turn; a jug, milk or a plate breaks into pixel shards and leaves a spill; what lies on the floor is kicked by whoever walks through it',
    size: () => `${TUNING.scatter.count[0]}–${TUNING.scatter.count[1]} things a table · ${TUNING.scatter.speed[0]}–${TUNING.scatter.speed[1]} px/s, lift ${TUNING.scatter.lift[0]}–${TUNING.scatter.lift[1]} · gravity ${TUNING.scatter.gravity} · bounce ×${TUNING.scatter.bounce} · breaks past ${TUNING.scatter.breakAt[0]}–${TUNING.scatter.breakAt[1]} px/s`,
    godot: 'Each piece a Node2D with a fake height: vz -= g * delta, the sprite drawn at y - z over a shadow at y; at z <= 0 bounce with restitution and skid the xy velocity; a brittle one frees itself into a one-shot GPUParticles2D of shards and a decal.' },
  { name: 'Rising into the pasture', cat: 'SCREEN', status: 'new', src: 'HADES', code: 'Heaven.enter · Heaven.drawScreen · heaven.arrive',
    trigger: 'Clicking through a death card', look: 'The picture comes out of white, the goat rises in a pool of light, THE PASTURE ABOVE is lettered over the top with a gold rule, and the last life’s sacrifices are counted into the heap under it',
    size: () => `white ${TUNING.heaven.arrive.flash}s · rise ${TUNING.heaven.arrive.rise}s · title ${TUNING.heaven.arrive.title}s · tally from ${TUNING.heaven.arrive.tallyAfter}s over ${TUNING.heaven.arrive.tallyTime}s`,
    godot: 'A CanvasLayer ColorRect tweened out of white; a Label faded in and out on modulate.a; the goat’s sprite offset tweened up over its shadow; the tally a Label driven by tween_method.' },
  { name: 'The god speaks', cat: 'UI', status: 'new', src: 'HADES', code: 'Heaven.drawTalk · heaven.type/talkArm/talkOut',
    trigger: 'GRAB by the god, or his call on the first visit', look: 'The picture dims; he comes in big from the left on a turning star of light inside a gold pixel ring; a dark box with gold corners under his name types his words out while his mouth moves; a gold arrow bobs when a line is done',
    size: () => `${TUNING.heaven.type} letters/s · a press ignored ${TUNING.heaven.talkArm}s · out over ${TUNING.heaven.talkOut}s`,
    godot: 'A CanvasLayer: a ColorRect dim, a TextureRect portrait tweened in, a RichTextLabel whose visible_characters steps per letter, and an additive ray Sprite2D turned in _process.' },
  { name: 'The god’s light', cat: 'WORLD', status: 'new', src: 'HADES', code: 'Heaven.drawGodLight',
    trigger: 'Always, round the god on his cloud', look: 'Nine soft rays turning slowly round him, each breathing on its own, over a warm pool of light, all laid on added',
    size: () => '9 rays · 420 px · a turn every 140 s',
    godot: 'A Sprite2D of a ray fan with an additive CanvasItemMaterial rotated in _process; a PointLight2D for the warm pool.' },
  { name: 'Off the edge', cat: 'SCREEN', status: 'new', src: 'GOAT', code: 'Heaven.update (jump) · Heaven.goatLook · game.dropIn · heaven.jump/drop',
    trigger: 'Walking off the pasture’s edge (or Backspace)', look: 'He drops away into the cloud and the picture goes white over the last of it; on the floor below he falls in from above, landing as the level card clears',
    size: () => `${TUNING.heaven.jump.time}s at ${TUNING.heaven.jump.speed}px/s, white over the last ${Math.round(TUNING.heaven.jump.fade * 100)}% · dropped ${TUNING.heaven.drop.height}px over ${TUNING.heaven.drop.time}s`,
    godot: 'A tween on the goat sprite’s offset and scale with a white ColorRect tweened in; on the next scene a tween from a negative y offset timed off the level card’s own tween.' },
  { name: 'Tumble and wake', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Heaven.goatLook · Heaven.flip · Heaven.updateDrop · heaven.drop.ko/getup',
    trigger: 'Falling off the edge, and down onto the floor below', look: 'A steady spin with a roll over his long axis (he thins edge-on and widens flat); he lands on his side, lies stunned, then gets up with a wobble',
    size: () => `${TUNING.heaven.drop.turns} turns, ${TUNING.heaven.drop.flips} rolls on the way down · ${TUNING.heaven.drop.ko}s down · ${TUNING.heaven.drop.getup}s up`,
    godot: 'An AnimationPlayer track on rotation and scale.x (|cos| of the roll); the goat’s state machine holds a STUNNED state for the lie.' },
  { name: 'Chandelier comes down', cat: 'WORLD', status: 'new', src: 'Enter the Gungeon', code: 'Prop.cutRope · Prop.updateChandelier · Renderer.drawChandelierAir · TUNING.chandelier',
    trigger: 'The rope cut at its cleat: a headbutt, a thrown body, fire', look: 'Its shadow on the floor darkens as the ring falls; it lands with a thud, dust, sparks and a ring of fire from the candles, and lies bent where it fell',
    size: () => `${TUNING.chandelier.z}px up, ${TUNING.chandelier.gravity}px/s² · crushes within ${TUNING.chandelier.killR}px · fire ${TUNING.chandelier.fireR} tile for ${TUNING.chandelier.fireFor}s`,
    godot: 'A RigidBody2D-free fall: a tween on the sprite’s y offset with an ease-in, an Area2D checked on landing, GPUParticles2D for sparks and dust, a shadow Sprite2D scaled by height.' },
  { name: 'Armour flies apart', cat: 'WORLD', status: 'new', src: 'Enter the Gungeon', code: 'Prop.burstArmor · Scatter.fromArmor · Enemy.wallDressing · TUNING.prop.armor',
    trigger: 'A headbutt on a suit of armour, a flung body into it or landing by it; a thrown crate or blade, a blast', look: 'Helm, pauldrons and breastplate hop off the far wall from the heights they hung at, out into the room, ringing and bouncing as they land, the helm rolling; the halberd and the bare plate left on the wall',
    size: () => `${TUNING.prop.armor.pieces.length} pieces · within ${TUNING.prop.armor.near}px past touching · the body flies on at ${Math.round(TUNING.prop.armor.slow * 100)}%`,
    godot: 'Swap the stand’s sprite; spawn the pieces as small RigidBody2D-free nodes with a z tween and a bounce, or GPUParticles2D with sub-emitters for the rolls.' },
  { name: 'Blades and shields fall apart', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Prop.snap · Scatter.breakUp · Scatter.piecesOf · PROP_PIXELS brokeUp · Enemy.shieldTakes',
    trigger: 'A sword, halberd or shield spent (on stone, in a man, in the teeth), the shieldman’s board broken, a magnet’s orbiter stopping a blow', look: 'It breaks where it was into pieces cut off its own sprite (hilt and point; three planks; four skulls), thrown on along the way it was going, ringing or knocking as they land, and left on the floor to be kicked',
    size: () => `sword and halberd 2 pieces, shield 3, the board 4 · ${TUNING.scatter.speed[0]}-${TUNING.scatter.speed[1]}px/s × 0.8`,
    godot: 'Pre-cut piece textures (an Image region each); spawn them as small nodes with a z tween and a bounce, the scatter’s own code, or GPUParticles2D with one texture per piece.' },
  { name: 'A blade stays in him', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Prop.stickIn · Renderer.drawStuck · Scatter.breakStuck · prop.weapon.stick',
    trigger: 'A thrown blade spent in a man with a heart to spare', look: 'The sword stays in him at the angle it went in, fanned a little, turning with him as he walks, behind him when it went in through his back; when he dies it breaks out of him into its pieces',
    size: () => `${TUNING.prop.weapon.stick.max} at once · ${TUNING.prop.weapon.stick.k}px a texel · fanned ±${TUNING.prop.weapon.stick.fan} rad`,
    godot: 'A Sprite2D child of the enemy, rotated by the hit angle minus his facing, z_index under or over the body by its angle; freed into piece nodes on his death signal.' },
  { name: 'Hung on the antlers', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Enemy.antlers · Enemy.wallDressing · PaintedArt.trophy · TUNING.prop.trophy',
    trigger: 'A flung body meeting a stag’s head on the far wall, even too slow to die on the stone', look: 'He sticks up on the wall with the tines through him and his blood runs down to the floor; a man with hearts to spare strains there, then tears free',
    size: () => `from ${TUNING.prop.trophy.hit / TILE} tiles/s · within ${TUNING.prop.trophy.hitR}px · pinned ${TUNING.prop.trophy.time}s · ${TUNING.prop.trophy.lift}px up the wall`,
    godot: 'Reparent the body sprite to the trophy node at a pin offset, a Line2D or particle drip for the blood; a Timer for the tear-free.' },
  { name: 'Table goes over', cat: 'WORLD', status: 'new', src: 'Enter the Gungeon', code: 'Prop.flipTable · Prop.knockFlipped · Prop.smashTable · prop.table.flip',
    trigger: 'A table knocked sliding coming to rest, or slamming into stone', look: 'It tips onto its side, top toward where it went, the supper flying; butted it rocks, and the last blow breaks it into planks',
    size: () => `${Math.round(TUNING.prop.table.flip.chance * 100)}% on stopping · always past ${TUNING.prop.table.flip.wall / TILE} tiles/s into stone · ${TUNING.prop.table.flip.hits} blows to break`,
    godot: 'Swap the table’s sprite frame and CollisionShape2D on a signal; an AnimationPlayer shake for the rock; GPUParticles2D planks.' },
  { name: 'A blast goes through the room', cat: 'WORLD', status: 'new', src: 'Enter the Gungeon', code: 'Prop.blastRoom · Prop.light · Bullet.update · prop.barrel.chain · prop.bomb.chain',
    trigger: 'A bomb, BOMB CHARGE’s man, a barrel going up or a poison blast; a rifle round into a barrel', look: 'What stands in it answers: a barrel says OIL and goes up a beat later, then the next one; a poison barrel bursts, a lamp goes over into fire, a crate is matchwood, the bowl spills its coals, the gong rings, a cracked wall opens, a rope parts',
    size: () => `a blast lights a barrel ${TUNING.prop.barrel.chain}s short, a bomb ${TUNING.prop.bomb.chain}s · a round lights one on its own ${TUNING.prop.barrel.fuse}s fuse`,
    godot: 'An Area2D on the explosion; each prop in it with a line of sight gets a "blasted(from)" signal and chooses its own answer; a short Timer before a barrel goes, so a chain reads as a chain.' },
  { name: 'The board takes it', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Enemy.shieldTakes · Enemy.shieldCovers · PaintedArt.board · TUNING.shieldman',
    trigger: 'A headbutt, a crate, a blade, a bite or a round meeting a shieldman’s board from in front', look: 'The bone knocks and sheds chips, he is rocked back a step behind it; the horns into its horns throw the goat off seeing stars (a boss’s or a soul-bearer’s take a heart); the last thrown thing breaks it (SHATTERED)',
    size: () => `${TUNING.shieldman.uses} blows · ${Math.round(TUNING.shieldman.arc * 180 / Math.PI)}° either side of his front · the spikes throw him off at ${TUNING.shieldman.spikes.plain.speed / TILE} tiles/s, dazed ${TUNING.shieldman.spikes.plain.daze}s (a boss: ${TUNING.shieldman.spikes.hurt} heart)`,
    godot: 'An angle test against the facing before the hit is applied; an AnimationPlayer shake on the shield Sprite2D, GPUParticles2D splinters, a frame swap when it breaks.' },
  { name: 'A table from heaven', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Prop.fall · Game.updateSkyTables · Renderer.drawSkyTables · heaven.tables',
    trigger: 'A table butted off heaven’s edge; on the floor below, more than two men in his room and two hearts lost in it and the last', look: 'Up there it drops away off the lip, turning and shrinking; below, a shadow finds a man and follows him, the table tumbles in from above the screen, crushes whoever is under it and lies on its side',
    size: () => `${TUNING.heaven.tables.z}px up, ${TUNING.heaven.tables.grav}px/s² · follows him until ${TUNING.heaven.tables.lock}s out · crushes within ${TUNING.heaven.tables.killR}px`,
    godot: 'A tween on the sprite’s y offset with an ease-in over a shadow Sprite2D that tracks a target until a timer locks it, an Area2D checked on landing.' },
  { name: 'Powder trail', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Game.spillPowder · Game.updatePowder · Renderer.drawPowder · prop.powder',
    trigger: 'A barrel broken without going up; then fire, or a man alight, on the powder', look: 'Dark grains on four tiles; lit, some spit white and orange, then each tile blows in turn with a small fireball, a ring and a scorch, the next one a beat later',
    size: () => `${TUNING.prop.powder.tiles} tiles · fuse ${TUNING.prop.powder.fuse}s, chain ${TUNING.prop.powder.chain}s · blast ${TUNING.prop.powder.r} tile`,
    godot: 'A TileMap layer of powder cells; a Timer per lit cell that spawns the blast scene and lights its neighbours.' },
  { name: 'White souls', cat: 'WORLD', status: 'new', src: 'Enter the Gungeon', code: 'Motes.spawn · Motes.update · Motes.bank · Motes.draw · heaven.motes',
    trigger: 'A man put down, once the god has given the gift; the goat walking out of that room (or the floor cleared)', look: 'A small white soul rises over the body and breathes there; out of the room they all come after him, curling, a dotted tail each, and every one that reaches him lights the heap and rings a note that climbs with a quick run of them',
    size: () => `${TUNING.heaven.motes.rise}px up · ${TUNING.heaven.motes.speed}→${TUNING.heaven.motes.max}px/s · caught within ${TUNING.heaven.motes.catchR}px · ${TUNING.heaven.pay.kill} each`,
    godot: 'A pooled Node2D per soul with a small state machine (rise, wait, home); steering by lerped velocity toward the player; an AudioStreamPlayer whose pitch_scale steps up on a short combo timer.' },
  { name: 'The soul goes up', cat: 'DEATH', status: 'new', src: 'GOAT', code: 'Motes.drawAscent · Motes.ghost · Motes.beam · heaven.ascent · deathCam.delay',
    trigger: 'The goat dies (before the pull-back to the whole floor)', look: 'A column of pale light comes down on him and his own picture, washed white and see-through, lifts out of the body, slow and then away, swaying, specks of light coming off it',
    size: () => `${TUNING.heaven.ascent.rise}px over ${TUNING.heaven.ascent.time}s from ${TUNING.heaven.ascent.lift}s · beam ${TUNING.heaven.ascent.beam}px · the pull-back waits ${TUNING.deathCam.delay}s`,
    godot: 'The goat’s AnimatedSprite2D duplicated with a modulate of white at 0.8 alpha (or a flat-colour shader), a tween up with EASE_IN; a ColorRect beam in three bands with additive blend.' },
  { name: 'Second chance', cat: 'DEATH', status: 'new', src: 'GOAT', code: 'Motes.second · Motes.updateRevive · Motes.drawRevive · heaven.second',
    trigger: 'A killing blow with SECOND CHANCE bought in the mirror, once a floor', look: 'He goes down; the beam comes, his ghost lifts a little way, hangs, and drops back into him, a white flash, a ring, the men round him thrown back dazed, NOT YET',
    size: () => `${TUNING.heaven.second.time}s · up on ${TUNING.heaven.second.hearts} hearts · untouchable ${TUNING.heaven.second.invuln}s · ${TUNING.heaven.second.push} tiles pushed`,
    godot: 'Pause the tree but the revive node (process_mode ALWAYS); the same ghost tween out and back; a Shockwave Area2D on landing that applies an impulse and a stun.' },
  { name: 'Helldive', cat: 'DEATH', status: 'new', src: 'GOAT', code: 'Motes.updateDive · Motes.drawDive · Motes.diveLook · Motes.diveLand · heaven.dive',
    trigger: 'Any revive (SECOND CHANCE, ONE MORE LIFE) with HELLDIVE bought in the mirror', look: 'The beam pulls him up out of the picture; a mark of amber cells on the floor he steers, heavy, with a ring closing in and a pip over every man it will reach; he comes down head first in a shaft, a crater, a ring, a flash, a boom, NOT YET',
    size: () => `${TUNING.heaven.dive.up}s up · ${TUNING.heaven.dive.aim}s to steer · ${TUNING.heaven.dive.fall}s down · hurts ${TUNING.heaven.dive.hurt.join(' / ')} tiles · dazes ${TUNING.heaven.dive.stun[0]} tiles / the room`,
    godot: 'Pause the tree but the dive node; a CharacterBody2D reticle with heavy acceleration and damping, clamped to a radius and the TileMap; on landing an Area2D: damage inside, stun to the room.' },
];

// The whole table as Markdown: the EXPORT button on the JUICE tab downloads it, and
// `node tools/juice-md.js` writes it to JUICE.md, so the list can be handed to somebody who never
// opens the game.
function juiceMarkdown() {
  const cell = (s) => String(s).replace(/\|/g, '\|');
  const status = { in: 'in game', new: 'new', backlog: 'backlog' };
  const out = ['# Goat Out, juice catalogue', '',
    'Generated from `js/juice.js` (the JUICE tab of the level tool). Status: **in game** was already there, **new** landed with the tab, **backlog** is not built yet.', '',
    '| Effect | Status | Trigger | How it looks | Size / time | Godot 4 | Source | Code |',
    '|---|---|---|---|---|---|---|---|'];
  for (const j of JUICE) out.push('| ' + [j.name, status[j.status], j.trigger, j.look, j.size(), j.godot, JUICE_SRC[j.src], j.code ? '`' + j.code + '`' : '-'].map(cell).join(' | ') + ' |');
  out.push('', '## Sources', '', ...Object.values(JUICE_SRC).map((s) => '- ' + s));
  return out.join('\n') + '\n';
}
