// THE JUICE CATALOGUE. Every piece of game feel the game has, has just got, or has been asked for,
// in one list: what sets it off, what it looks like, how big and how long, where it lives in this
// code, and how the same thing is built in Godot 4 — because the list is for whoever builds the
// next version as much as for this one. Read by the JUICE tab of the level tool (`drawJuiceTab`)
// and by `node tools/juice-md.js`, which writes JUICE.md from it, so it is written once.
//
// `status`: 'in' was already in the game, 'new' landed with this tab, 'backlog' is not built yet.
// `src` is where the idea comes from:
//   SCREENSHAKE — Jan Willem Nijman (Vlambeer), "The Art of Screenshake", INDIGO 2013
//   JUICE       — Martin Jonasson & Petri Purho, "Juice it or lose it", GDC Europe 2012
//   SWINK       — Steve Swink, "Game Feel" (2008)
//   GMTK        — Mark Brown, "Secrets of Game Feel and Juice" and "Celeste & forgiveness"
//   HITSTOP     — Masahiro Sakurai on hitstop / hit-lag (Smash Bros.), and the fighting-game canon
//   GOAT        — asked for by this game's own playtests (BACKLOG.md)
// Sizes are read off TUNING where a number exists, so the table cannot drift from the game.
const JUICE_SRC = {
  SCREENSHAKE: 'Vlambeer — The Art of Screenshake (2013)',
  JUICE: 'Jonasson & Purho — Juice it or lose it (2012)',
  SWINK: 'Steve Swink — Game Feel (2008)',
  GMTK: "Game Maker's Toolkit — Secrets of Game Feel / Celeste forgiveness",
  HITSTOP: 'Sakurai / fighting games — hitstop',
  GOAT: 'Goat Out playtests',
};

const JUICE = [
  // ---- the camera ----
  { name: 'Hitstop', cat: 'TIME', status: 'in', src: 'HITSTOP', code: 'game.hitstop · juice.hitstop',
    trigger: 'Every kill; smaller on door blows, parries, the pen', look: 'The whole simulation freezes for a few frames; the picture holds on the moment of contact',
    size: () => `${TUNING.juice.hitstop}s kill, +${TUNING.juice.comboHitstopMul}/combo to +${TUNING.juice.comboHitstopCap}s`,
    godot: 'Engine.time_scale = 0 then a timer that ignores time scale: await get_tree().create_timer(t, true, false, true).timeout; restore to 1. Keep UI tweens on TWEEN_PAUSE_PROCESS.' },
  { name: 'Screen shake', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.shake · juice.shakeKill/shakeHit/shakeDecay',
    trigger: 'A heart lost, and nothing else: every other call site is multiplied by juice.shakeOther, which is 0',
    look: 'Random offset of the whole picture that decays — the one thing that says you were hit without your looking at the hearts',
    size: () => `${TUNING.juice.shakeHit}px hurt · ×${TUNING.juice.shakeOther} for anything else · decays ×${TUNING.juice.shakeDecay}/s`,
    godot: 'Trauma model: trauma += amt (clamp 0..1); Camera2D.offset = max_offset * trauma² * FastNoiseLite sample; trauma -= decay * delta. Noise, not randf, so it does not jitter.' },
  { name: 'Directional kick', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.kick · juice.kick/kickMax/kickDecay',
    trigger: 'Headbutt landing, kills, clubs taken', look: 'The picture is shoved along the blow and springs back — a punch, not a rattle',
    size: () => `${TUNING.juice.kick}px, capped ${TUNING.juice.kickMax}px, ×${TUNING.juice.kickOther} unless the goat was hit, decay ×${TUNING.juice.kickDecay}/s`,
    godot: 'A second Camera2D.offset term: kick_vec += dir * amt; kick_vec = kick_vec.lerp(Vector2.ZERO, 1 - exp(-decay * delta)). Add to the shake offset.' },
  { name: 'Zoom punch', cat: 'CAMERA', status: 'in', src: 'JUICE', code: 'game.zoomPunch · juice.zoomKick/zoomDecay',
    trigger: 'Kills, the wraith unmade, bombs', look: 'The lens shoves in a few percent and settles back',
    size: () => `+${Math.round(TUNING.juice.zoomKick * 100)}% · settles ×${TUNING.juice.zoomDecay}/s`,
    godot: 'create_tween().tween_property(camera, "zoom", base * (1 + k), 0.04) then .tween_property(camera, "zoom", base, 0.25).set_trans(Tween.TRANS_EXPO).set_ease(Tween.EASE_OUT).' },
  { name: 'Camera lead', cat: 'CAMERA', status: 'in', src: 'SCREENSHAKE', code: 'game.camLead · camera.lead/leadLerp',
    trigger: 'Always, toward the aim and scaled by run speed', look: 'The view looks ahead of the goat, not at him',
    size: () => `${TUNING.camera.lead}px ahead · lerp ${TUNING.camera.leadLerp}`,
    godot: 'Camera2D child of the player with its own script: target = player.global_position + aim * lead; position = position.lerp(target, 1 - exp(-rate * delta)).' },
  { name: 'Deadzone camera', cat: 'CAMERA', status: 'in', src: 'SWINK', code: 'game.camFollow · camera.deadzone/fitMargin',
    trigger: 'Standing still, or in a room that fits the screen', look: 'Small motion never re-centres the picture; a small room holds still',
    size: () => `${TUNING.camera.deadzone}px deadzone`,
    godot: 'Camera2D.drag_horizontal_enabled / drag_vertical_enabled with drag margins; a room-sized Area2D can set limit_* to lock a small room.' },
  { name: 'Slow motion on a kill', cat: 'TIME', status: 'in', src: 'SCREENSHAKE', code: 'game.slowTimer · juice.killSlow/comboSlow/deathSlow',
    trigger: 'The Butcher down, a third kill in a streak, death', look: 'Time eases to a third and back',
    size: () => `${TUNING.juice.killSlow}s boss · ${TUNING.juice.comboSlow}s combo · ${TUNING.juice.deathSlow}s death`,
    godot: 'Tween Engine.time_scale to 0.3 and back with a tween set to ignore time scale (set_ignore_time_scale(true)). Pitch music down with AudioServer bus effect, not the stream.' },
  { name: 'Aiming slow motion (COLD EYE)', cat: 'TIME', status: 'in', src: 'MAX PAYNE / HOTLINE', code: 'game.coldEye · game.aimSlow · BOONS coldeye',
    trigger: 'Anything into his mouth, with COLD EYE; ends on the throw', look: 'Time eases down and holds while he aims, the grab chip drains, one falling note',
    size: () => { const p = BOONS.find((b) => b.id === 'coldeye').params; return `×${p.scale} for ${p.time}s real · once per ${p.every}s`; },
    godot: 'Same Engine.time_scale tween, counted with a Timer whose process_callback ignores time scale; cancel it from the throw.' },
  { name: 'The vault (LEAPFROG)', cat: 'BODY', status: 'in', src: 'SPELUNKY', code: 'Goat.leapTarget · goat.leap · PaintedArt.drawGoat',
    trigger: 'A roll at a man in front, with LEAPFROG', look: 'He lifts off his shadow in a stretched arc, a knock and a puff off the man\'s back at the top, lands on four feet',
    size: () => { const p = BOONS.find((b) => b.id === 'leapfrog').params; return `${p.height}px high · ${p.time}s in the air · ${p.behind} tile past him`; },
    godot: 'Sprite2D offset.y = -sin(t/T*PI)*h on a child, shadow Sprite2D scaled by the same curve; the body moves on a straight line with collision_mask off for enemies until it lands.' },
  // ---- the screen ----
  { name: 'Screen flash', cat: 'SCREEN', status: 'in', src: 'JUICE', code: 'game.flash · juice.flashDecay',
    trigger: 'Kills (blood), witchfire, a soul, reaching the stairs', look: 'An additive colour wash over the picture that fades fast',
    size: () => `0.1–0.4 alpha · fades ×${TUNING.juice.flashDecay}/s`,
    godot: 'CanvasLayer > ColorRect (full rect), material blend_mode ADD; tween modulate.a from amt to 0.' },
  { name: 'Hurt direction arc', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'game.hurtFlash · drawHurt',
    trigger: 'Taking a hit', look: 'A red arc at the edge of the screen pointing back at whoever hit you',
    size: () => '0.6s',
    godot: 'TextureRect arc on a CanvasLayer, rotation = angle to attacker; tween modulate.a.' },
  { name: 'Hurt vignette', cat: 'SCREEN', status: 'in', src: 'GMTK', code: 'drawHurtVignette · juice.hurtVignette',
    trigger: 'Taking a hit', look: 'Every corner reddens and fades',
    size: () => `${TUNING.juice.hurtVignette.life}s · ${TUNING.juice.hurtVignette.alpha} alpha`,
    godot: 'Full-screen ColorRect with a radial-gradient shader (smoothstep on distance from UV centre), uniform intensity tweened.' },
  { name: 'Last-heart heartbeat', cat: 'SCREEN', status: 'new', src: 'GMTK', code: 'drawHeartbeat · juice.heartbeat',
    trigger: 'Down to the last heart', look: 'The screen edge pulses red lub-dub, and the last heart on the HUD throbs with it',
    size: () => `${TUNING.juice.heartbeat.bpm} bpm · ${TUNING.juice.heartbeat.alpha} alpha · heart ±${Math.round(TUNING.juice.heartbeat.throb * 100)}%`,
    godot: 'Same vignette shader; drive intensity from an AnimationPlayer loop (two keys close together, then a rest). Pair with a low-pass on the music bus.' },
  { name: 'Rumble', cat: 'SCREEN', status: 'in', src: 'SWINK', code: 'game.vibe',
    trigger: 'Hits, kills, throws — touch devices only', look: 'The phone buzzes, scaled to the blow',
    size: () => '6–80 ms',
    godot: 'Input.start_joy_vibration(0, weak, strong, dur) for pads; Input.vibrate_handheld(ms) on mobile.' },
  // ---- bodies ----
  { name: 'Hit flash (white)', cat: 'BODY', status: 'new', src: 'SCREENSHAKE', code: 'enemy.flash · juice.hitFlash · drawEnemy',
    trigger: 'A headbutt lands on a man (and every Butcher blow)', look: 'He is repainted as a solid white silhouette for a few frames',
    size: () => `${TUNING.juice.hitFlash}s`,
    godot: 'CanvasItem shader: uniform float flash; COLOR.rgb = mix(texture(TEXTURE, UV).rgb, vec3(1.0), flash); keep alpha. Tween flash 1 → 0. Use a per-instance uniform (instance uniform float flash) so one material serves all.' },
  { name: 'Windup tint', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Renderer.windupGlow · juice.windupTint · drawEnemyBody',
    trigger: 'Any man in a telegraph: a club or blade windup, the brute\'s charge, the ogre\'s slam and leap, the rat ogre\'s, a hound\'s plant, a seer\'s cast, a rifle\'s aim',
    look: 'His own sprite goes lighter and warmer as the blow comes, faint at first and bright at the last frame (as in Cult of the Lamb); masked to his pixels, no glow',
    size: () => { const W = TUNING.juice.windupTint; return `up to ${W.max} alpha · ease ^${W.curve} · warm ${W.warm}`; },
    godot: 'The hit-flash shader with a second uniform: COLOR.rgb = mix(tex.rgb, warm_white, windup); set windup = pow(1 - timer / wind, curve) * max from the enemy script every frame.' },
  { name: 'Squash & stretch (poses)', cat: 'BODY', status: 'in', src: 'JUICE', code: 'drawGoat · painted-art drawGoat',
    trigger: 'Windup, lunge, roll, stun', look: 'Crouched before a headbutt, stretched through it, curled in a roll',
    size: () => 'windup 0.85×1.1 · lunge 1.15×0.92',
    godot: 'AnimationPlayer keys on Sprite2D.scale per state, or set scale in the state machine enter().' },
  { name: 'Squash spring', cat: 'BODY', status: 'new', src: 'JUICE', code: 'game.squashGoat · juice.squash',
    trigger: 'A headbutt landing, a blow taken, the end of a roll', look: 'The goat wobbles wide-and-flat then tall-and-thin and settles, like jelly',
    size: () => `hit ${TUNING.juice.squash.hit} · hurt ${TUNING.juice.squash.hurt} · ${TUNING.juice.squash.freq} rad/s, decay ${TUNING.juice.squash.decay}`,
    godot: 'create_tween().tween_property(sprite, "scale", Vector2(1+a, 1-a), 0.05) then back to Vector2.ONE over 0.3s with TRANS_ELASTIC / EASE_OUT.' },
  { name: 'Knockback', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'enemy.fling · goat.headbutt.impulse',
    trigger: 'Every headbutt, every body arriving', look: 'The man flies along the blow, spinning — the fling is the attack',
    size: () => `impulse ${Math.round(TUNING.goat.headbutt.impulse)}px/s`,
    godot: 'CharacterBody2D: velocity = dir * impulse, then friction in _physics_process; spin the sprite while velocity > threshold.' },
  { name: 'Player recoil', cat: 'BODY', status: 'in', src: 'SCREENSHAKE', code: 'damage(kx, ky) · Butcher planted bounce',
    trigger: 'A blow taken; a headbutt into a Butcher crouching or winding a slam', look: 'The goat is shoved back the way the blow came',
    size: () => '5 tiles/s on a planted Butcher',
    godot: 'velocity += -dir * recoil on the hit; clamp with move_toward over a few frames.' },
  { name: 'Motion smear', cat: 'BODY', status: 'in', src: 'JUICE', code: 'goat.trail · goat.trail.*',
    trigger: 'Running, scaled by speed and run-up', look: 'Fading ghosts of the goat behind him',
    size: () => `life ${TUNING.goat.trail.life}s`,
    godot: 'Spawn a Sprite2D copy with the current frame every N ms, tween modulate.a to 0 and free; or a GPUParticles2D using the sprite texture with local_coords off.' },
  { name: 'Invulnerability blink', cat: 'BODY', status: 'in', src: 'GMTK', code: 'goat.invuln',
    trigger: 'After a hit and through a roll', look: 'The goat strobes at half alpha',
    size: () => `${TUNING.goat.invuln}s`,
    godot: 'AnimationPlayer toggling modulate.a on a 1/30s step while an invuln Timer runs.' },
  { name: 'Dazed stars', cat: 'BODY', status: 'in', src: 'JUICE', code: 'drawStars · enemy.dazed',
    trigger: 'The scream, the pen, a stun', look: 'Three stars orbit the head, the body sways',
    size: () => 'as long as the daze',
    godot: 'Three Sprite2Ds on a Node2D child rotated each frame; an ellipse via scale.y = 0.5.' },
  // ---- the world ----
  { name: 'Impact ring + sparks', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'game.impact · juice.impact',
    trigger: 'A headbutt landing', look: 'A tight bright ring at the point of contact and a star of spark streaks thrown along the blow',
    size: () => `${TUNING.juice.impact.ring} tiles · ${TUNING.juice.impact.life}s · ${TUNING.juice.impact.sparks} sparks`,
    godot: 'A one_shot GPUParticles2D (explosiveness 1, spread 45°, direction = blow) plus a ring Sprite2D tweened scale 0 → 1 and alpha 1 → 0. Pool them.' },
  { name: 'Kill shockwave', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'onKill · juice.impact.killRing',
    trigger: 'Every kill but a drop', look: 'A pale ring swells out from the body and thins away',
    size: () => `${TUNING.juice.impact.killRing} tiles · ${TUNING.juice.impact.killLife}s`,
    godot: 'Screen-space distortion shader (SCREEN_TEXTURE offset by a ring function) for the fancy version, or a ring Sprite2D.' },
  { name: 'Hoof dust', cat: 'WORLD', status: 'new', src: 'JUICE', code: 'game.dust · juice.dust',
    trigger: 'Lunge, roll start, roll landing — never plain running', look: 'Soft pale puffs kicked out behind him that swell and fade',
    size: () => `${TUNING.juice.dust.life}s · ${TUNING.juice.dust.size}→${TUNING.juice.dust.size + TUNING.juice.dust.grow}px`,
    godot: 'CPUParticles2D at the feet, one-shot burst on lunge/roll/land; scale_amount_curve rising, color_ramp alpha falling.' },
  { name: 'Muzzle flash', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'fireBullet · juice.muzzle · drawFlares',
    trigger: 'Every rifle shot', look: 'A tapering tongue of fire cells along the shot with a hot core and a short cross-flare, for a frame or two',
    size: () => `${TUNING.juice.muzzle.life}s · ${TUNING.juice.muzzle.size}px`,
    godot: 'Sprite2D at the muzzle, visible for 2 frames with random rotation; a PointLight2D pulse lights the room with it.' },
  { name: 'Aim telegraph', cat: 'WORLD', status: 'in', src: 'GMTK', code: 'drawAimTelegraph · drawTelegraph',
    trigger: 'A rifle aiming, a club winding up', look: 'A line and a wedge showing where the blow will land before it does',
    size: () => 'the windup',
    godot: 'Line2D from the shooter along aim, width and alpha tweened as the windup fills.' },
  { name: 'Particles', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.particles · combat-fx',
    trigger: 'Blows, doors, coals, gunshots', look: 'Squares and chips flung from the contact, snapped to the world pixel grid; sparks are runs of cells along their flight',
    size: () => '0.3–0.8s',
    godot: 'GPUParticles2D one_shot, pooled; ParticleProcessMaterial with initial_velocity range and damping.' },
  { name: 'Gore and debris', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'game.gore · CombatFX.fragment/debris',
    trigger: 'Kills, broken doors and crates', look: 'Chunks with height that fly, bounce and settle — the body tears into its own sprite',
    size: () => `≤${TUNING.effects.maxAir} in the air`,
    godot: 'RigidBody2D pieces are too heavy; fake height with a z value per piece in one script, draw with _draw() or MultiMeshInstance2D.' },
  { name: 'Permanence (blood, bodies)', cat: 'WORLD', status: 'in', src: 'SCREENSHAKE', code: 'world.decal · DECAL_SCALE',
    trigger: 'Everything that bleeds, burns or falls', look: 'Blood, scorch and bodies stay on the floor for the whole level',
    size: () => 'the level',
    godot: 'A SubViewport with render_target_clear_mode = NEVER; draw stains into it and show it as a TextureRect under the actors.' },
  { name: 'A body that settles', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.death / corpseSprite / updateGround / pool · effects.corpse',
    trigger: 'A man killed whole (not torn, not fallen)', look: 'He carries the speed he died with, lands, skids leaving a smear, rolls onto his side square to the pixel grid, twitches, and a dark pool seeps out from under him; duller than the living, on his own silhouette for a shadow',
    size: () => `pool ${TUNING.effects.corpse.pool}px (${TUNING.effects.corpse.big} Butcher) over ${TUNING.effects.corpse.time}s · ${TUNING.effects.corpse.twitches} twitches`,
    godot: 'A Sprite2D rotated to ±90° on landing via tween; a pool Sprite2D under it scaling up with an ease-out, baked into the decal viewport when done.' },
  { name: 'Pixel fire', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.flameFrames / flame · effects.flame',
    trigger: 'Every flame: a burning tile, a brazier, a lamp, a man alight, witchfire', look: 'A looping teardrop of five flat bands (ember red to white core) whose tongues are eaten from the top by noise scrolling up through it, sparks climbing off the tip — baked once per whole-pixel size, drawn with smoothing off',
    size: () => `${TUNING.effects.flame.frames} frames at ${TUNING.effects.fireFps} fps · ${TUNING.effects.flame.wide}×${TUNING.effects.flame.tall} of its size · ${TUNING.effects.pixel}px texel`,
    godot: 'Bake the frames offline (or in a tool script) into a SpriteFrames sheet; AnimatedSprite2D with texture_filter NEAREST, frame offset per tile so neighbours never flicker in step.' },
  { name: 'Pixel blast', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.burstFrames / explosion · effects.blast',
    trigger: 'A bomb, a bomb charge; dust for a door, a crate, a man burnt out; a spray of blood on a kill', look: 'White flash and a star of rays, a fireball of puffs cooling through the bands into soot lit from above, rising and ordered-dithered away; a pixel shock ring on the floor, embers streaking out, the room lit for an instant and a lens punch — no shake',
    size: () => `${TUNING.effects.blast.frames} frames over ${TUNING.effects.burstLife}s · light ×${TUNING.effects.blast.light} r for ${TUNING.effects.blast.lightFor}s · ${TUNING.effects.blast.embers} embers`,
    godot: 'A pre-baked SpriteFrames explosion (NEAREST), a PointLight2D energy tween for the flash, a one_shot CPUParticles2D of embers, and a ring Sprite2D on the floor layer.' },
  { name: 'Soot column', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'CombatFX.explosion · effects.blast.soot',
    trigger: 'Every blast, once the fireball has burnt out', look: 'A second, darker cloud that starts a beat late above the blast and goes on rising and dithering away after it',
    size: () => `×${TUNING.effects.blast.soot} r, from ${TUNING.effects.blast.sootAfter}s for ${TUNING.effects.blast.sootLife}s`,
    godot: 'A second AnimatedSprite2D started on a Timer, drifting up with a Tween.' },
  { name: 'A barrel that rolls', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Prop.roll / updateBarrel / oilBurst · PaintedArt.drawProp · prop.barrel',
    trigger: 'A headbutt, a thrown body or a charge into a barrel; flame under it or a burning man against it', look: 'It goes over onto its side and rolls end for end in whole quarter turns; every man it meets flashes and is bowled aside with a small kick of the camera; lit, one flame sits on it and a standing one shivers harder as the fuse runs down, then a blast and a pool of fire',
    size: () => `rolls ${(TUNING.prop.barrel.roll / TILE).toFixed(0)} tiles/s · fuse ${TUNING.prop.barrel.fuse}s · burst ${TUNING.prop.barrel.burst} tiles for ${TUNING.prop.barrel.burstTime}s`,
    godot: 'A CharacterBody2D with move_and_collide and a linear damp; two lying frames flipped every quarter turn of travel; a Timer for the fuse driving a shake tween and a flame child, then the blast scene.' },
  { name: 'Floating words', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.floatText',
    trigger: 'Door counts, OOPS, COALS, combo ×N', look: 'Stamped caps that rise and fade',
    size: () => '1.2s',
    godot: 'Label scene spawned at the point, tween position.y -= 30 and modulate.a → 0, then queue_free.' },
  { name: 'Combo counter', cat: 'WORLD', status: 'in', src: 'JUICE', code: 'game.combo · juice.comboWindow',
    trigger: 'Kills inside the window', look: '×N grows with the streak',
    size: () => `${TUNING.juice.comboWindow}s window`,
    godot: 'Autoload counter with a Timer; the label scales with a TRANS_BACK tween on each increment.' },
  { name: 'Barks', cat: 'WORLD', status: 'in', src: 'GOAT', code: 'game.bark · BARKS',
    trigger: 'Seeing, losing, panicking', look: 'A dark plate over a man\'s head with a line',
    size: () => '< 2s, global gap',
    godot: 'A Label over the head plus a global cooldown in an autoload so a crowd never talks at once.' },
  // ---- sound ----
  { name: 'Layered sound per hit', cat: 'SOUND', status: 'in', src: 'SCREENSHAKE', code: 'GameAudio sfx*',
    trigger: 'Every verb', look: 'Thud + bleat + steel stacked per event',
    size: () => '—',
    godot: 'AudioStreamRandomizer with random_pitch and random_volume_offset_db; several AudioStreamPlayer2Ds per event.' },
  { name: 'No two takes alike', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.foley · js/foley.js',
    trigger: 'Every effect', look: 'Physical models rendered in a few takes; one picked, nudged in pitch and level',
    size: () => `${TUNING.audio.foley.takes} takes, ±${Math.round(TUNING.audio.foley.pitch * 100)}% pitch, ±${Math.round(TUNING.audio.foley.level * 100)}% level`,
    godot: 'Bake the takes to .wav once; AudioStreamRandomizer (PLAYBACK_RANDOM_NO_REPEATS) with random_pitch and random_volume_offset_db.' },
  { name: 'A stone room', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'Foley.roomImpulse · TUNING.audio.room',
    trigger: 'Always', look: 'Every effect and a little of the score through one short dark reverb; loud things send more',
    size: () => `${TUNING.audio.room.decay}s tail`,
    godot: 'AudioEffectReverb on a Room bus (room_size ~0.35, damping ~0.7, wet ~0.3), SFX and Music buses sending to it.' },
  { name: 'Heard from where it is', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.heard · Enemy.updateDog',
    trigger: 'A hound barking as it runs', look: 'Quieter with distance, panned to its side of the goat',
    size: () => `whole to ${TUNING.audio.space.near} tiles, ${Math.round(TUNING.audio.space.floor * 100)}% at ${TUNING.audio.space.far}`,
    godot: 'AudioStreamPlayer2D on the hound (max_distance, attenuation), the AudioListener2D on the goat.' },
  { name: 'Reactive music', cat: 'SOUND', status: 'in', src: 'GOAT', code: 'GameAudio.updateScene · MUSIC.md',
    trigger: 'Who is in the room, spotted / chase / combat', look: 'The score thickens with the room',
    size: () => '16-bar transport',
    godot: 'AudioStreamInteractive (4.3+) with clips per stage and transitions on beat, or AudioStreamSynchronized layers with volume per layer.' },
  // ---- the backlog ----
  { name: 'Input buffer', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'Goat.update · buttBuf / rollBuf · goat.buffer',
    trigger: 'Pressing headbutt while busy, or roll before it is back', look: 'Nothing visible — the press is remembered and fires the frame he is free',
    size: () => `${TUNING.goat.buffer}s window`,
    godot: 'Store the press time; in the state machine, on entering idle, consume it if Time.get_ticks_msec() - pressed < window. Not a cancel: the recovery is still eaten in full (pillar 4).' },
  { name: 'Door-hit forgiveness', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'headbuttHits · door.reachSlack',
    trigger: 'A headbutt at a door', look: 'A door takes the blow from its ends and from flush in a wall',
    size: () => `+${TUNING.prop.door.reachSlack}px reach, cone widened for doors`,
    godot: 'Give the hurtbox a margin bigger than the collision shape (a second Area2D) — the "coyote" of melee.' },
  { name: 'Hit direction on the body', cat: 'BODY', status: 'backlog', src: 'SCREENSHAKE',
    trigger: 'A man taking a blow', look: 'His sprite leans away from the blow for a few frames before the fling',
    size: () => '0.1s',
    godot: 'Tween sprite.skew or rotation by ±0.2 toward -blow and back.' },
  { name: 'Shell casings', cat: 'WORLD', status: 'new', src: 'SCREENSHAKE', code: 'game.fireBullet · CombatFX.fragment · effects.shell',
    trigger: 'A rifle shot', look: 'A brass case pops out of the side of the breech, bounces once and stays on the floor',
    size: () => `${TUNING.effects.shell.w}×${TUNING.effects.shell.h}px, permanent`,
    godot: 'One-shot particle with a height fake; on land, stamp into the decal SubViewport.' },
  { name: 'Chromatic kick', cat: 'SCREEN', status: 'backlog', src: 'JUICE',
    trigger: 'A big kill or a bomb', look: 'The red and blue channels split apart for a frame',
    size: () => '0.08s, 3px',
    godot: 'Screen shader on a BackBufferCopy: sample SCREEN_TEXTURE at UV ± offset for r and b.' },
  { name: 'Room-clear sting', cat: 'SOUND', status: 'new', src: 'GMTK', code: "game.onKill · musicEvent('cleared') · playMusicEvents",
    trigger: 'The last man of a room goes down', look: 'Three notes up the scale to the octave, on the beat after the kill accent',
    size: () => `4 steps, gain ${TUNING.audio.layers.clearGain}`,
    godot: 'Signal from the room when its enemy group empties; play a one-shot on the music bus quantised to the beat.' },
  { name: 'Anticipation on the goat', cat: 'BODY', status: 'new', src: 'SWINK', code: 'drawGoat · goat.feel.pull',
    trigger: 'Headbutt windup', look: 'A tiny pull-back opposite the aim before the lunge, eased in over the windup',
    size: () => `${TUNING.goat.feel.pull}px over ${TUNING.goat.headbutt.windup}s`,
    godot: 'Offset the sprite by -aim * 3 during windup via tween, snap forward on lunge.' },
  { name: 'Idle life', cat: 'BODY', status: 'new', src: 'JUICE', code: 'Goat.update fidget · drawGoat · goat.idle / goat.breathe',
    trigger: 'Standing still', look: 'Breathing, and after a moment a fidget now and then: a glance one facing aside, a little pronk, a head shake, a hoof pawing the floor with a puff of dirt',
    size: () => `breath ${TUNING.goat.breathe.period}s · first fidget after ${TUNING.goat.idle.after}s, then every ${TUNING.goat.idle.gap.join('–')}s`,
    godot: 'AnimationPlayer idle loop; a Timer with a random wait_time picks one of a few one-shot fidget animations; any input stops it.' },
  { name: 'Weight in the stride', cat: 'BODY', status: 'new', src: 'SWINK', code: 'Goat.update (lean) · drawGoat · goat.feel',
    trigger: 'Running, starting, stopping, turning', look: 'He leans into a change of pace and a little forward at full stride, and hops a pixel per hoof-fall in step with the walk frames',
    size: () => `lean ${TUNING.goat.feel.lean} rad + ${TUNING.goat.feel.run} running · bob ${TUNING.goat.feel.bob}px`,
    godot: 'Sprite rotation = lerp toward accel.x / max_accel * lean; offset.y = -abs(sin(frame * PI / 2)) * bob.' },
  { name: 'Kick-off, settle and skid', cat: 'FEEL', status: 'new', src: 'GMTK', code: 'Goat.update · goat.feel.kick/stop/skid/turnGrip',
    trigger: 'Setting off from still, letting go at speed, asking back against your own run', look: 'A stretch and a puff behind on a start, a squash on a stop; a reversal grips harder, squashes him and sprays dirt ahead',
    size: () => `reversal grip ×${TUNING.goat.feel.turnGrip} · skid squash ${TUNING.goat.feel.skid.squash}, ${TUNING.goat.feel.skid.dust} puffs, once per ${TUNING.goat.feel.skid.gap}s`,
    godot: 'In _physics_process: if input.dot(velocity) < -0.3, multiply acceleration and emit a one-shot GPUParticles2D at the feet.' },
  // ---- the shop (js/shop.js) ----
  { name: 'The rat ogre comes out', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Shop.spawnOgre · ratogre.emerge',
    trigger: 'The third blow on the mouse or her shelf', look: 'Stone out of the hole, a blood ring, the picture shoved away from the wall, a beat of slow motion, and he scales up out of the gap',
    size: () => `${TUNING.ratogre.emerge}s emerge · hitstop 0.08 · slow 0.35s · no shake (only a lost heart shakes: juice.shakeOther ${TUNING.juice.shakeOther})`,
    godot: 'Spawn at the gap with scale 0.4→1 over a tween; Engine.time_scale 0.5 for 0.35s; camera trauma 0.6; a one-shot particle burst of stone.' },
  { name: 'A blow that does nothing', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Goat.headbuttHits (ratogre) · Shop.ogreShrug',
    trigger: 'Horns on the rat ogre standing', look: 'The goat bounces off him, ash off the impact, no flash on him; once a run, the words for what would work',
    size: () => `4 tiles/s bounce · no shake (juice.shakeOther ${TUNING.juice.shakeOther})`,
    godot: 'On hit with no damage: knock the player back along -aim, small shake, skip the hit-flash shader; show the hint label once per run.' },
  { name: 'The blink', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Shop.blink · ARTIFACTS symbols',
    trigger: 'Q, with STRANGE SYMBOLS at his neck', look: 'Violet burst where he left and where he arrives, two rings, five ghosts along the line, dust at both ends, a squash on landing',
    size: () => `${TUNING.goat.trail.fastLife}s ghosts · ring 1.2 tiles · ${TUNING.juice.squash.land} squash`,
    godot: 'Teleport the body; spawn a GPUParticles2D burst at both points; push 5 sprite ghosts along the segment with staggered lifetimes; play the landing squash tween.' },
  { name: 'The boomerang', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Shop.throwBoomerang / updateBoomerang · Renderer.drawBoomerang',
    trigger: 'Q, with the BOOMERANG at his neck', look: 'A bent stick spinning out along the aim with a short smear behind it, a thud and a flash on each man it takes, and it curves home',
    size: () => `${(TUNING.shop.boomerang.speed / TILE).toFixed(0)} tiles/s · spin 22 rad/s · hitstop 0.02 a man`,
    godot: 'A Node2D with a rotating Sprite2D and a Line2D trail; outward leg on a straight velocity, return leg steers to the player each frame; Area2D body_entered applies the stun once per body.' },
  { name: 'Taking from the mouse', cat: 'UI', status: 'new', src: 'GOAT', code: 'Shop.buy',
    trigger: 'Grab on one of her three offers', look: 'A ring and a burst in the talisman’s own colour off the stool (or her pail of milk set down in a puff of white), the name floats over the goat, the bell rings, the rest go back into the wall in a puff of ash, and her gate gives',
    size: () => 'ring 1.6 tiles · 14 particles · bell · 8 ash',
    godot: 'On take: ring tween + particle burst tinted by item colour; float label; play the bell; free the other ware with a small ash burst; open the gate door.' },
  { name: 'The veil', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'game.updateClamps · Renderer.drawUnseen · Renderer.drawVeil',
    trigger: 'A room two behind the goat with nobody alive in it', look: 'The room goes black and a breathing curtain of dark with violet threads hangs across the mouth of its way out; a low drawn breath if it is near',
    size: () => `fades in over ${(TUNING.clamp.slam * 3).toFixed(2)}s · heard within ${TUNING.clamp.hear} tiles`,
    godot: 'Swap the mouth tiles to wall in the TileMap; a black ColorRect over the room faded in with a tween; a shader-driven curtain Sprite2D across the mouth (scrolling noise, violet threshold lines).' },
  { name: 'Hound run line', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Enemy.planDash · Renderer.drawDashPaths · dog.windup/dashSpeed/dashTime',
    trigger: 'A hound plants to run at the goat, and while it runs', look: 'A wide red smear with a dashed bright line and an arrowhead along the bent path it will take, brightening across the charge',
    size: () => `${TUNING.dog.windup}s charge · ${(TUNING.dog.dashSpeed * TUNING.dog.dashTime / TILE).toFixed(1)} tiles`,
    godot: 'Line2D fed each frame from a simulated path (Curve2D baked points), width_curve fat to thin, modulate alpha tweened up over the windup.' },
  { name: 'Soul fanfare', cat: 'UI', status: 'new', src: 'GOAT', code: 'Renderer.drawSoulFanfare · game.boonT · fanfare',
    trigger: 'A soul picked up: the three cards come up', look: 'A pale flash, a wheel of gold and violet pixel rays turning behind the soul, the soul springing in, A SOUL bouncing up in gold, pixel confetti bursting and falling; then the cards spring in one after another and the rays settle to a glow',
    size: () => `${TUNING.fanfare.intro}s before the cards · ${TUNING.fanfare.rays} rays · ${TUNING.fanfare.sparks} sparks · cards ${TUNING.fanfare.stagger}s apart`,
    godot: 'A CanvasLayer: a rotating Polygon2D fan with a nearest-filtered low-res SubViewport, a CPUParticles2D burst with gravity, a Label tweened with TRANS_BACK, card Controls tweened in with a stagger.' },
  { name: 'Ogre slam ring', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawSlamRing · Enemy.quake · butcher.slam',
    trigger: 'The ogre, close in, raises both fists to bring them down on the floor', look: 'A bone ring on the floor at the reach of the slam, filling red from the middle; on the blow two rings, dust and a shake',
    size: () => `${TUNING.butcher.slam.range} tiles · ${TUNING.butcher.slam.wind}s`,
    godot: 'A floor decal Sprite2D ring with a radial fill shader (progress uniform), then a one-shot ring particle and camera shake on the hit.' },
  { name: 'Talisman: parry', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Talisman.parryFx · mirror.window',
    trigger: 'A blow, bite or round arrives inside MIRROR SHARD\'s window', look: 'A pale ring round the goat, a violet-white spark burst at the blow, PARRIED, a steel note and a short hitstop',
    size: () => `${ARTIFACTS.find((a) => a.id === 'mirror').tiers[0].params.window}s window at tier I`,
    godot: 'Area2D parry window timer; on overlap spawn a ring Sprite2D + GPUParticles2D burst, Engine.time_scale dip for 60 ms.' },
  { name: 'Talisman: grease', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Talisman.drawGround · grease.life',
    trigger: 'A wall kill with BUTCHER\'S GREASE worn', look: 'Overlapping wet red smears round the body with a glint of light, fading over their life',
    size: () => `${ARTIFACTS.find((a) => a.id === 'grease').tiers[0].params.life}s`,
    godot: 'TileMap overlay layer with a shine shader; per-cell timer fades modulate alpha.' },
  { name: 'Talisman: echo', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Talisman.updateEchoes · echo.delay',
    trigger: 'A headbutt with ECHO HORN worn', look: 'A pale outline of the goat and his horns lunging again where the blow landed',
    size: () => `${ARTIFACTS.find((a) => a.id === 'echo').tiers[0].params.delay}s after`,
    godot: 'Delayed ghost Sprite2D with additive blend at the lunge end point, a shape cast for the hit.' },
  { name: 'Talisman: bell shapes', cat: 'UI', status: 'new', src: 'GOAT', code: 'Talisman.drawWorld · bell.sil',
    trigger: "BELLWETHER'S BELL II+, men out of sight within range", look: 'Men behind stone drawn as flat shapes over the shade — ash if they have not seen you, red if they have — and screen-edge marks to the stairs and the vault',
    size: () => `${ARTIFACTS.find((a) => a.id === 'bell').tiers[1].params.sil} tiles at II`,
    godot: 'Second CanvasItem pass of enemy sprites with a flat-colour shader above the fog layer; edge arrows on a CanvasLayer.' },
  { name: 'Death-map skulls', cat: 'UI', status: 'new', src: 'GOAT', code: 'game.killMarks · Renderer.skullMark · deathCam.skull',
    trigger: 'The death screen pulls back over the level', look: 'A small bone skull on a dark rim wherever a man went down, alongside the red line of the run',
    size: () => `${TUNING.deathCam.skull}px`,
    godot: 'Sprite2D per kill position on a CanvasLayer overlay scaled against camera zoom.' },
  { name: 'Last-heart blood trail', cat: 'BODY', status: 'new', src: 'GOAT', code: 'Goat.update · goat.bleed',
    trigger: 'Running on the last heart', look: 'A dark drop on the floor behind him every so often, not a stripe',
    size: () => `every ${TUNING.goat.bleed.gap}s ±${Math.round(TUNING.goat.bleed.jitter * 100)}%`,
    godot: 'Timer with randomised wait_time spawning a decal Sprite2D while hp == 1 and velocity above a threshold.' },
  { name: 'Blood in the wool', cat: 'BODY', status: 'new', src: 'GOAT', code: 'PaintedArt.wounds · goat.wounds',
    trigger: 'Every heart he has lost', look: 'One dark blot of blood on his body per missing heart, masked to the sprite so it is only ever on him — health read off the goat at a glance',
    size: () => `${TUNING.goat.wounds.r}px, +${TUNING.goat.wounds.grow} each, up to ${TUNING.goat.wounds.spots.length}`,
    godot: 'A child Sprite2D per lost heart using the goat frame as a clip mask (CanvasGroup / clip_children), shown by hp.' },
  { name: 'Ogre landing ring', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawHopMark · Enemy.hopLand / quake · ratogre.hop, butcher.leap',
    trigger: 'The rat ogre or the ogre crouching to leap, and landing', look: 'A red ring on the floor where he will come down, filling as he flies; he rises over his shadow and lands with shake, a ring and dust',
    size: () => `${TUNING.ratogre.hop.radius} tiles, ${TUNING.ratogre.hop.wind}s crouch, ${TUNING.ratogre.hop.air}s air, ${TUNING.ratogre.hop.lift}px lift · Butcher ${TUNING.butcher.leap.radius} tiles, ${TUNING.butcher.leap.wind}s, ${TUNING.butcher.leap.air}s, ${TUNING.butcher.leap.lift}px`,
    godot: 'A Decal or a Line2D circle at the target, its fill tweened by the jump progress; the sprite offset.y = -sin(t*PI)*lift over a static shadow; camera shake on landing.' },
  { name: 'Hay about to catch', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawCatching · World.updateFire · fire.catch',
    trigger: 'Hay or grass beside a burning tile of hay or grass', look: 'Ember cells wake in the next tile and rise off it, more of them and brighter as the spread fills, so the line the fire will take is visible before it takes it',
    size: () => `up to ${TUNING.fire.catch.embers} cells of ${TUNING.fire.catch.cell}px, rising ${TUNING.fire.catch.rise}px`,
    godot: 'A GPUParticles2D ember emitter per fuel cell next to a burning one, amount_ratio driven by that neighbour\'s spread timer.' },
  { name: 'Burning grass', cat: 'WORLD', status: 'new', src: 'GOAT', code: 'Renderer.drawBurningGrass · World.updateFire · grass.burn/spread',
    trigger: 'Fire reaching tall grass', look: 'Each blade chars from the root and shortens, a small baked pixel flame at every tip that steps down a size as it burns; the front walks tile by tile across the patch',
    size: () => `${TUNING.grass.burn}s a tile, spreads every ${TUNING.grass.spread}s`,
    godot: 'Per-tile GPUParticles2D flame emitters on the grass TileMap layer, the blade shader lerping to char by burn progress; spread on a Timer per burning cell.' },
  { name: 'The trip wash', cat: 'SCREEN', status: 'new', src: 'GOAT', code: 'Renderer.drawTrip',
    trigger: 'The whole of THE TRIP', look: 'A three-colour gradient whose hue walks round the wheel, laid on in soft light, and glowing spores drifting up the screen on their own parallax',
    size: () => '46 spores, hue at 14°/s, gradient turning at 0.25 rad/s',
    godot: 'A full-screen ColorRect with a soft-light blend shader taking TIME for the hue; a GPUParticles2D of spores in a CanvasLayer with a parallax offset off the camera.' },
  { name: 'Eating the mushrooms', cat: 'SCREEN', status: 'new', src: 'GOAT', code: 'game.eatShrooms',
    trigger: 'Standing still over the tuft until the ring fills', look: 'A violet flash, a zoom punch, a ring and a puff of pale spores, a low bleat and two lines of warning',
    size: () => `grazed ${TUNING.shroom.eatTime}s inside ${TUNING.shroom.eatR} tiles`,
    godot: 'An Area2D on the tuft; on body_entered a screen flash (CanvasModulate tween), a camera zoom tween and a one-shot particle burst.' },
];

// The whole table as Markdown: the EXPORT button on the JUICE tab downloads it, and
// `node tools/juice-md.js` writes it to JUICE.md, so the list can be handed to somebody who never
// opens the game.
function juiceMarkdown() {
  const cell = (s) => String(s).replace(/\|/g, '\|');
  const status = { in: 'in game', new: 'new', backlog: 'backlog' };
  const out = ['# Goat Out — juice catalogue', '',
    'Generated from `js/juice.js` (the JUICE tab of the level tool). Status: **in game** was already there, **new** landed with the tab, **backlog** is not built yet.', '',
    '| Effect | Status | Trigger | How it looks | Size / time | Godot 4 | Source | Code |',
    '|---|---|---|---|---|---|---|---|'];
  for (const j of JUICE) out.push('| ' + [j.name, status[j.status], j.trigger, j.look, j.size(), j.godot, JUICE_SRC[j.src], j.code ? '`' + j.code + '`' : '—'].map(cell).join(' | ') + ' |');
  out.push('', '## Sources', '', ...Object.values(JUICE_SRC).map((s) => '- ' + s));
  return out.join('\n') + '\n';
}
