// Hand-authored room templates. Legend:
// '#' wall  '.' floor  'P' pillar  'h' hay  'B' brazier  'o' pot  'b' bell  't' table  'L' lamp post
// 'w' a stand of arms: a sword or a shield to grab and throw
// 'e' bearer spawn  'r' hunter spawn (bearer if level has no hunters)  'X' butcher spawn
// 'R' always a rifle where the level has them  'm' seer spawn  'M' the Mill's hub
// Rooms are randomly flipped on both axes at generation time.
// A template with a `tag` is only drawn by a level whose `pool` matches it; untagged ones are the
// default pool every other level uses.
const ROOM_TEMPLATES = [
  { name: 'hall', rows: [
    '################',
    '#..............#',
    '#..hh....PP....#',
    '#..hh.......L..#',
    '#.....e....o...#',
    '#..e....tt...r.#',
    '#....PP.tt.hh..#',
    '#..B.......hh..#',
    '#..............#',
    '################',
  ]},
  { name: 'pillars', rows: [
    '##############',
    '#............#',
    '#..P..e...P..#',
    '#......L.....#',
    '#......o.....#',
    '#..P......P..#',
    '#....m....e..#',
    '#..P......P..#',
    '#............#',
    '##############',
  ]},
  { name: 'kitchen', rows: [
    '############',
    '#..........#',
    '#.o....B...#',
    '#.tt.......#',
    '#..e.PPP...#',
    '#....PPP.r.#',
    '#.tt.......#',
    '#.B....e...#',
    '#..........#',
    '############',
  ]},
  { name: 'barn', rows: [
    '################',
    '#..............#',
    '#.hhh......hhh.#',
    '#.hhh..e...hhh.#',
    '#.....L...L....#',
    '#...P......P...#',
    '#......r.......#',
    '#.hhh......hhh.#',
    '#.hhh..e...hhh.#',
    '#..............#',
    '################',
  ]},
  { name: 'shrine', rows: [
    '##############',
    '#............#',
    '#..B......B..#',
    '#............#',
    '#....PPPP....#',
    '#..e.P..P..r.#',
    '#....P..P....#',
    '#....b.......#',
    '#..B......B..#',
    '#...t....t...#',
    '##############',
  ]},
  { name: 'corridors', rows: [
    '##################',
    '#................#',
    '#.PPPP..e..PPPP..#',
    '#....L.......L...#',
    '#..o.PPPPPP...m..#',
    '#................#',
    '#.PPPP..e..PPPP..#',
    '#.......h........#',
    '##################',
  ]},
  { name: 'store', rows: [
    '############',
    '#..........#',
    '#.o....tt..#',
    '#......tt..#',
    '#...e..PP..#',
    '#..r...PP..#',
    '#....L.....#',
    '#.hh.....o.#',
    '#.hh...e...#',
    '#..........#',
    '############',
  ]},
  { name: 'cross', rows: [
    '################',
    '#..............#',
    '#..e...PP...e..#',
    '#......PP......#',
    '#.PP...tt...PP.#',
    '#.PP...o....PP.#',
    '#......PP......#',
    '#..m...PP...h..#',
    '#...L......L...#',
    '################',
  ]},
  { name: 'tight', rows: [
    '##########',
    '#........#',
    '#..e.....#',
    '#....B...#',
    '#.o...t..#',
    '#.....e..#',
    '#..h.....#',
    '#........#',
    '##########',
  ]},

  // ---- THE THRESHING FLOOR: open ground, tagged 'open' so only that level draws from them. ----
  // Out here the walls are nearly gone and the structure is furniture: posts, tables, braziers and
  // hay. A headbutt on bare floor still only knocks a man down, so the level is about herding him
  // into something that finishes the job — and about deciding which half of the room is yours.
  // Props in the middle and open ground all round it: the fight happens on your side of the island.
  { name: 'island', tag: 'open', rows: [
    '############################',
    '#..........................#',
    '#..e....................e..#',
    '#..........................#',
    '#.....B..............B.....#',
    '#........tt......tt........#',
    '#........tt..PP..tt........#',
    '#.....o....P.PP.P....o.....#',
    '#........tt..PP..tt........#',
    '#........tt......tt........#',
    '#.....B......r.......B.....#',
    '#..........................#',
    '#..e....................e..#',
    '#..........................#',
    '############################',
  ]},
  // Everything useful is along the two edges. Crossing the middle is fast, open and stupid.
  { name: 'flanks', tag: 'open', rows: [
    '##############################',
    '#............................#',
    '#.PP...B...hh........hh...B..#',
    '#.PP.......hh........hh...PP.#',
    '#...r....................R...#',
    '#............................#',
    '#..........e......e..........#',
    '#.....o..................o...#',
    '#..........e......e..........#',
    '#............................#',
    '#....m...................e...#',
    '#.PP.......hh........hh...PP.#',
    '#.PP...B...hh........hh...B..#',
    '#............................#',
    '##############################',
  ]},
  // A ring of hay: a wall you do not have until you light it, and cannot take back once you have.
  { name: 'hayring', tag: 'open', rows: [
    '############################',
    '#..........................#',
    '#..B....................B..#',
    '#..........................#',
    '#.....hhhhhhhhhhhhhhhh.....#',
    '#.....h..............h.....#',
    '#..e..h....o....o....h..e..#',
    '#.....h...PP....PP...h.....#',
    '#..r..h....o....o....h.....#',
    '#.....h..............h.....#',
    '#.....hhhhhhhhhhhhhhhh.....#',
    '#..........................#',
    '#..B.........e..........B..#',
    '#..........................#',
    '############################',
  ]},
  // Table rows you can shoulder about. The lanes are only where you leave them.
  { name: 'lanes', tag: 'open', rows: [
    '##############################',
    '#............................#',
    '#..tt..tt..tt..tt..tt..tt....#',
    '#..tt..tt..tt..tt..tt..tt....#',
    '#............................#',
    '#......e........r........e...#',
    '#............................#',
    '#..L......................L..#',
    '#............................#',
    '#......e........m........e...#',
    '#............................#',
    '#..tt..tt..tt..tt..tt..tt....#',
    '#..tt..tt..tt..tt..tt..tt....#',
    '#............................#',
    '##############################',
  ]},
  // A field of posts, spread wide. The only hard geometry out here, and the only thing that kills for you.
  { name: 'posts', tag: 'open', rows: [
    '############################',
    '#..........................#',
    '#..P...P...P...P...P...P...#',
    '#..........................#',
    '#..e....................e..#',
    '#..........o....o..........#',
    '#..P...P...........P...P...#',
    '#.....r............m.......#',
    '#..P...P...........P...P...#',
    '#..........o....o..........#',
    '#..e....................e..#',
    '#..........................#',
    '#..P...P...P...P...P...P...#',
    '#..........................#',
    '############################',
  ]},
];

const ARENA_TEMPLATE = { name: 'arena', rows: [
  '##############',
  '#............#',
  '#..w......w..#',
  '#....P..P....#',
  '#.L........L.#',
  '#......X.....#',
  '#............#',
  '#....P..P....#',
  '#..hh....hh..#',
  '#..B......B..#',
  '#............#',
  '##############',
]};

// The Mill: a big open room built around a ritual grinding wheel. 'M' is the hub.
// The room is deliberately taller than the arms are long: there is a lane along the top and the
// bottom that the sweep never reaches, so the room can be crossed by reading it rather than by luck.
const MILL_TEMPLATE = { name: 'mill', rows: [
  '##################',
  '#................#',
  '#..o.............#',
  '#................#',
  '#.e............e.#',
  '#................#',
  '#................#',
  '#.......M........#',
  '#................#',
  '#................#',
  '#.e............e.#',
  '#................#',
  '#..hh........hh..#',
  '#..B..........B..#',
  '#................#',
  '##################',
]};

// The Gallery: long sightlines, hard cover, and rifles standing on their own rather than in a pile.
const GALLERY_TEMPLATE = { name: 'gallery', rows: [
  '####################',
  '#..................#',
  '#...PP...PP...PP...#',
  '#...PP...PP...PP...#',
  '#..R....o.......R..#',
  '#..................#',
  '#...PP...PP...PP...#',
  '#...PP...PP...PP...#',
  '#........R.........#',
  '####################',
]};

// The room you woke up in. The altar stands off to one side, made ready, with the straps and the
// knife and what is left of the goat that went before you. You are in the pen beside it.
// Two tiles wider than it was, so the second cage fits on the right without crowding the way out.
const START_TEMPLATE = { name: 'start', rows: [
  '##################',
  '#................#',
  '#.B............B.#',
  '#................#',
  '#................#',
  '#................#',
  '#................#',
  '#................#',
  '#.B............B.#',
  '#................#',
  '##################',
]};

// The Great Hall: one enormous room with two mills, pillar rows, hay, tables and a crowd.
// Running straight through it is a bad idea. Running through it anyway is the point.
const GREAT_HALL_TEMPLATE = { name: 'greathall', rows: [
  '######################################',
  '#....................................#',
  '#..................B...hhhh.......B..#',
  '#...................e..hhhh....e.....#',
  '#....................PP.....PP.......#',
  '#....................PP.....PP.....L.#',
  '#.........M........o.....e......tt...#',
  '#....................e..........tt...#',
  '#.................b..........r.......#',
  '#....e............................e..#',
  '#............L.........m.............#',
  '#...hh........e......................#',
  '#...hh...........B.............e.....#',
  '#.....tt............r................#',
  '#.....tt...............e.............#',
  '#..........PP..............M.........#',
  '#....e.....PP......L.................#',
  '#..B...........hh....e...............#',
  '#........o.....hh.................B..#',
  '#.......e..........r..........e......#',
  '#....................................#',
  '######################################',
]};
