// THE AUTOPLAY BOT (3 Oct 2026): written by a friend of the project against the itch build, kept here
// as he sent it. It plays through synthetic keys and pointer events only and reads `game` to see the
// world, never writes it, so what it does is what a player could do. Watchable: F8 on/off, F9 its panel.
// It learns per browser (localStorage 'doomedgoatbot.v1': margins round hazards, reach per kind, which
// souls served it). Load it in the page like the harness, or paste it into the console:
//   const s = document.createElement('script'); s.src = '/tools/autoplay-bot.js'; document.body.appendChild(s);
// A reference for active testing when asked (not every time): bugs a careful player meets, and later
// a base for playtest numbers (how often it uses the verbs, how it reads hazards and takes blows) and
// for judging levels. `window.bot.log` is its diary, `bot.mem.deaths` what killed it.
(function waitForGoat() {
  const g = window.game;
  if (!g || !g.canvas || !g.goat || typeof TUNING === 'undefined' || typeof Heaven === 'undefined') return setTimeout(waitForGoat, 500);
  if (window.bot && window.bot.iv) return; // already running
  // Doomed Goat autoplay bot (release build, generated by tools/make-release.py from src/bot-dev.js).
  // Plays https://dimache.itch.io/doomed-goat through synthetic keyboard and mouse input only:
  // it reads the game state to see the world but never edits it.
  // F8 = bot on/off, F9 = hide/show the info panel. Per-player adjustments are kept in localStorage.
  (() => {
    if (window.bot && window.bot.iv) clearInterval(window.bot.iv);
    const g = window.game, cv = g.canvas, hyp = Math.hypot;
    const KEY = 'doomedgoatbot.v1';
    // parameters learned over 42 lives of the run that beat the game
    const DEFAULTS = {"margin": {"mill": 25.47, "brazier": 1.69, "spike": 27.17, "barrel": 20.89, "fire": 29.37}, "millLook": 0.78, "rollLead": {"bearer": 0.6, "champion": 0.39, "dog": 0.6, "seer": 0.21, "hunter": 0.6, "shieldman": 0.07, "default": 0.29}, "reach": {"bearer": 63.09, "champion": 96.91, "dog": 101.19, "seer": 100.3, "hunter": 110.39, "shieldman": 56.65, "default": 70.65}, "engage": 10.93, "bulletDist": 130.91, "healBelow": 1, "screamAt": 1, "retreatAt": 4, "retreatHp": 0, "throwMin": 46.35, "throwMax": 346.64};
    const clone = o => JSON.parse(JSON.stringify(o));
    let mem = null;
    try { mem = JSON.parse(localStorage.getItem(KEY) || 'null'); } catch (e) { mem = null; }
    if (!mem) mem = { best: clone(DEFAULTS), bestFit: {}, lives: 0, lessons: [], hits: {}, deaths: {}, boonScore: {"breath": -0.15, "hunger": -0.15, "leapfrog": -0.15, "oracle": -0.15, "horns": -0.15, "hide": 0.15, "collar": -0.3, "ember": -0.15, "venomjaw": -0.15, "throat": 0.3, "skull": 0.3, "coldeye": 0.3, "joints": 0.45, "lungs": 0.3, "hocks": 0.3} };
    if (mem.best && mem.best.margin) for (const k in mem.best.margin) mem.best.margin[k] = Math.min(k === 'mill' ? 40 : k === 'spike' ? 10 : 30, mem.best.margin[k]);
    for (const k in DEFAULTS) if (mem.best[k] == null) mem.best[k] = clone(DEFAULTS[k]);
    for (const k of ['margin', 'rollLead', 'reach']) for (const j in DEFAULTS[k]) if (mem.best[k][j] == null) mem.best[k][j] = DEFAULTS[k][j];
    const save = () => {
      try { localStorage.setItem(KEY, JSON.stringify(mem)); } catch (e) { }
    };
  
    g.autoPause = false; // keep playing when the Chrome window is not focused
    const B = window.bot = { mem, log: [], keys: new Set(), on: true, t: 0, lastState: null, buttT: 0, stuckT: 0, lastPos: null, goal: null };
    B.P = clone(mem.best);
    const say = m => { B.log.push(`${(performance.now() / 1000).toFixed(1)} L${g.levelIndex} ${m}`); if (B.log.length > 300) B.log.shift(); };
    const lesson = m => { mem.lessons.push(`life ${mem.lives}: ${m}`); if (mem.lessons.length > 40) mem.lessons.shift(); say('LEARN ' + m); save(); };
  
    // ---------- parameters for this life ----------
    const jitter = (v, s, lo, hi) => Math.max(lo, Math.min(hi, v + (Math.random() * 2 - 1) * s));
    function mutate(p) {
      const q = clone(p);
      for (const k in q.margin) q.margin[k] = jitter(q.margin[k], 4, 0, k === 'mill' ? 40 : 30);
      q.millLook = jitter(q.millLook, 0.1, 0.3, 0.9);
      for (const k in q.rollLead) q.rollLead[k] = jitter(q.rollLead[k], 0.05, 0.05, 0.6);
      for (const k in q.reach) q.reach[k] = jitter(q.reach[k], 8, 50, 140);
      q.engage = jitter(q.engage, 1, 4, 14);
      q.bulletDist = jitter(q.bulletDist, 15, 60, 260);
      q.screamAt = Math.round(jitter(q.screamAt, 0.6, 1, 4));
      q.retreatAt = Math.round(jitter(q.retreatAt, 0.6, 2, 5));
      q.retreatHp = Math.round(jitter(q.retreatHp, 0.6, 0, 2));
      q.throwMin = jitter(q.throwMin, 10, 30, 120); q.throwMax = jitter(q.throwMax, 25, 140, 400);
      return q;
    }
    function newLife(reason) {
      B.P = B.explore ? mutate(mem.best) : clone(mem.best);
      B.life = { level: g.levelIndex, kills0: g.kills, dmg: 0, startX: g.goat ? g.goat.x : 0, maxX: 0, t0: performance.now() };
      mem.lives++; save();
      say(`life ${mem.lives} starts (${reason})`);
    }
    function fitness() {
      const L = B.life, ex = g.level.exit, sx = g.level.start;
      const total = Math.max(1, hyp(ex.x - sx.x, ex.y - sx.y));
      return L.maxProg * 100 + (g.kills - L.kills0) * 5 - L.dmg * 15;
    }
    function endLife(outcome) {
      if (!B.life) return;
      const lv = B.life.level, f = outcome === 'clear' ? 1000 - B.life.dmg * 15 : fitness();
      const prev = mem.bestFit[lv];
      if (prev == null || f > prev) {
        mem.bestFit[lv] = f; mem.best = clone(B.P);
        lesson(`life on level ${lv + 1} ${outcome}, fitness ${f.toFixed(0)} beats ${prev == null ? 'nothing' : prev.toFixed(0)}: kept its parameters`);
      } else say(`life ${outcome}, fitness ${f.toFixed(0)} <= best ${prev.toFixed(0)}`);
      if (outcome === 'death') mem.deaths[B.lastCause || '?'] = (mem.deaths[B.lastCause || '?'] || 0) + 1;
      B.life = null; save();
    }
  
    // ---------- observing damage (wrapper only records, then calls the original) ----------
    const GP = Object.getPrototypeOf(g.goat);
    if (!GP.__botWrapped) {
      const orig = GP.damage;
      GP.damage = function (n, game, kx, ky, force, cause) {
        const hp0 = this.hp; const r = orig.apply(this, arguments);
        if (this === game.goat && this.hp < hp0 && window.bot && window.bot.onHurt) window.bot.onHurt(cause, hp0 - this.hp);
        return r;
      };
      GP.__botWrapped = true;
    }
    B.onHurt = (cause, n) => {
      const o = g.goat, P = B.P || mem.best;
      let c = cause && typeof cause === 'object' ? (cause.kind || 'object') : cause, near = null;
      if (!c || c === 'hit' || c === 'enemy') {
        let bd = 1e9;
        for (const e of g.enemies) { if (e.dead) continue; const d = hyp(e.x - o.x, e.y - o.y); if (d < bd) { bd = d; near = e; } }
        c = near && bd < 120 ? near.kind : (cause || 'unknown');
      }
      B.lastCause = c;
      B.hurtLog = B.hurtLog || [];
      B.hurtLog.push({ t: (performance.now() / 1000) | 0, c, hp: o.hp, goal: B.goal, x: o.x / TILE | 0, y: o.y / TILE | 0, st: o.state, inFire: g.world.isBurningPx(o.x, o.y), pitNear: [0, 1, 2, 3, 4, 5, 6, 7].some(a => g.world.isPitPx(o.x + Math.cos(a * 0.785) * 40, o.y + Math.sin(a * 0.785) * 40)), near: g.enemies.filter(e => !e.dead && hyp(e.x - o.x, e.y - o.y) < 4 * TILE).map(e => e.kind + ':' + e.state).join(',') });
      if (B.hurtLog.length > 12) B.hurtLog.shift();
      mem.hits[c] = (mem.hits[c] || 0) + 1;
      if (B.life) B.life.dmg += n;
      // online nudges: make the thing that hurt us count more in both this life and the best set
      for (const p of [P, mem.best]) {
        if (p.margin[c] != null) p.margin[c] = Math.min(c === 'mill' ? 40 : c === 'spike' ? 10 : 30, p.margin[c] + 6);
        if (c === 'mill') p.millLook = Math.min(0.9, p.millLook + 0.1);
        if (/fire|burn|rune|witch/.test(c)) p.margin.fire = Math.min(40, p.margin.fire + 6);
        if (p.rollLead[c] != null) p.rollLead[c] = Math.min(0.6, p.rollLead[c] + 0.04);
        if (p.reach[c] != null && near && /windup|swing/.test(near.state || '')) p.reach[c] = Math.max(50, p.reach[c] - 4);
        if (near) {
          const crowd = g.enemies.filter(e => !e.dead && hyp(e.x - o.x, e.y - o.y) < 2.5 * TILE).length;
          if (crowd >= 2) { p.retreatAt = Math.max(2, p.retreatAt - 0.34); p.screamAt = Math.max(1, p.screamAt - 0.34); }
          if (o.hp <= 1) p.retreatHp = Math.min(2, p.retreatHp + 0.34);
        }
      }
      lesson(`hurt by ${c} (${mem.hits[c]}x total) -> margins ${JSON.stringify(mem.best.margin)}, millLook ${mem.best.millLook.toFixed(2)}`);
    };
  
    // ---------- input ----------
    const kd = c => window.dispatchEvent(new KeyboardEvent('keydown', { code: c, key: c.replace(/^(Key|Digit)/, '').toLowerCase(), bubbles: true }));
    const ku = c => window.dispatchEvent(new KeyboardEvent('keyup', { code: c, key: c.replace(/^(Key|Digit)/, '').toLowerCase(), bubbles: true }));
    for (const c of [...g.keys]) ku(c); // drop keys left held by a previous bot instance
    const key = (c, down) => { if (down && (!B.keys.has(c) || !g.keys.has(c))) { B.keys.add(c); kd(c); } else if (!down && B.keys.has(c)) { B.keys.delete(c); ku(c); } };
    const tap = c => { kd(c); setTimeout(() => ku(c), 40); };
    const releaseAll = () => { for (const c of [...B.keys]) key(c, false); };
    const toClient = (wx, wy) => {
      const r = cv.getBoundingClientRect(), z = g.cam.zoom;
      const mx = g.renderer.vcx + (wx - g.cam.x) * z, my = g.renderer.vcy + (wy - g.cam.y) * z * TILT;
      return { x: r.left + mx * r.width / cv.width, y: r.top + my * r.height / cv.height };
    };
    const ptr = (type, cx, cy, button = 0, buttons = 0) => cv.dispatchEvent(new PointerEvent(type, { clientX: cx, clientY: cy, pointerType: 'mouse', pointerId: 1, button, buttons, bubbles: true, cancelable: true }));
    // `B.aimErr` (px, set by tools/bot-lab.js for a weaker hand): the pointer lands that far off at random.
    const aim = (wx, wy) => { if (B.aimErr) { const a = Math.random() * 6.283, r = B.aimErr * Math.sqrt(Math.random()); wx += Math.cos(a) * r; wy += Math.sin(a) * r; }
      B.aimW = { x: wx, y: wy }; const c = toClient(wx, wy); B.mx = c.x; B.my = c.y; ptr('pointermove', c.x, c.y); return c; };
    const butt = (wx, wy) => { const c = aim(wx, wy); ptr('pointerdown', c.x, c.y, 0, 1); setTimeout(() => ptr('pointerup', c.x, c.y, 0, 0), 30); };
    const rmb = (down, wx, wy) => {
      const c = wx != null ? aim(wx, wy) : { x: B.mx || 0, y: B.my || 0 };
      if (down && !B.rmb) { B.rmb = true; ptr('pointerdown', c.x, c.y, 2, 2); }
      else if (!down && B.rmb) { B.rmb = false; window.dispatchEvent(new PointerEvent('pointerup', { clientX: c.x, clientY: c.y, pointerType: 'mouse', pointerId: 1, button: 2, buttons: 0, bubbles: true })); ptr('pointerup', c.x, c.y, 2, 0); }
    };
    const clickCenter = () => { const r = cv.getBoundingClientRect(), x = r.left + r.width / 2, y = r.top + r.height / 2; ptr('pointermove', x, y); ptr('pointerdown', x, y, 0, 1); setTimeout(() => ptr('pointerup', x, y, 0, 0), 30); };
    // every step is checked: a pit or spikes just ahead turn the step up to 90 deg, or cancel it
    const stepBad = (x, y) => { const w = g.world; if (!w || !g.goat) return false; if (w.isPitPx(x, y)) return true;
      for (const h of g.hazards || []) if (!h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && h.spikeThreat && h.spikeThreat() && hyp(h.x - x, h.y - y) < (h.r || 16) + g.goat.r + 2) return true;
      return false; };
    const move = (dx, dy) => {
      let d = hyp(dx, dy) || 1; dx /= d; dy /= d;
      const o = g.goat;
      if (o && (dx || dy) && g.state === 'play') {
        // the keys only give 8 directions: check the direction the goat will really take
        const q8 = (ux, uy) => { const qx = ux > 0.38 ? 1 : ux < -0.38 ? -1 : 0, qy = uy > 0.38 ? 1 : uy < -0.38 ? -1 : 0, l = hyp(qx, qy) || 1; return [qx / l, qy / l]; };
        const ok = (vx, vy) => { const [ux, uy] = q8(vx, vy); return okq(ux, uy); };
        const okq = (ux, uy) => ![12, 24].some(r => stepBad(o.x + ux * r, o.y + uy * r));
        if (!ok(dx, dy)) {
          let found = false;
          for (const a of [0.6, -0.6, 1.2, -1.2, 1.57, -1.57]) { const c = Math.cos(a), sn = Math.sin(a), ux = dx * c - dy * sn, uy = dx * sn + dy * c; if (ok(ux, uy)) { dx = ux; dy = uy; found = true; break; } }
          if (!found) { dx = 0; dy = 0; }
        }
      }
      key('KeyD', dx > 0.38); key('KeyA', dx < -0.38); key('KeyS', dy > 0.38); key('KeyW', dy < -0.38);
    };
    const onSpike = () => { const o = g.goat; return o && (g.hazards || []).find(h => !h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && hyp(h.x - o.x, h.y - o.y) < (h.r || 16) + o.r); };
    const stop = () => { const sp = g.state === 'play' && onSpike(); if (sp) { const o = g.goat; move(o.x - sp.x || 1, o.y - sp.y); } else move(0, 0); };
  
    // ---------- hazards ----------
    const MILL = TUNING.mill;
    const angDiff = (a, b) => { let d = (a - b) % (2 * Math.PI); if (d > Math.PI) d -= 2 * Math.PI; if (d < -Math.PI) d += 2 * Math.PI; return d; };
    function millHits(m, x, y, dt, extra) {
      const r = g.goat.r + extra, dx = x - m.x, dy = y - m.y, a = hyp(dx, dy);
      if (a > MILL.armLen + r || a < MILL.innerR - r) return false;
      const ang = Math.atan2(dy, dx), w = MILL.armHalfWidth + r / Math.max(a, 12), ma = m.angle + MILL.speed * dt;
      return Math.abs(angDiff(ma, ang)) < w || Math.abs(angDiff(ma + Math.PI, ang)) < w;
    }
    const mills = () => (g.hazards || []).filter(h => h.kind === 'mill' && !h.broken && !h.dead);
    // is position (x,y) going to be hit by a mill within `horizon` seconds?
    function millDanger(x, y, horizon) {
      const P = B.P;
      for (const m of mills()) for (let t = 0; t <= horizon; t += 0.05) if (millHits(m, x, y, t, P.margin.mill * 0.5)) return m;
      return null;
    }
  
    // ---------- grid / pathing ----------
    function blockedGrid(withMills, bare) {
      const w = g.world, W = w.W, H = w.H, b = new Uint8Array(W * H), P = B.P;
      // fire only hurts after ~1.2 s spent in it, so short crossings are free: the safe grid avoids it,
      // the fallback grid walks through it rather than getting stuck
      for (let i = 0; i < W * H; i++) { const t = w.tiles[i]; if (t === T.WALL || t === T.PIT || w.furn[i] || (withMills && (w.fire[i] > 0 || w.poison[i] > 0))) b[i] = 1; }
      const disk = (x0, y0, rad) => {
        const r = Math.ceil(rad / TILE), tx = Math.floor(x0 / TILE), ty = Math.floor(y0 / TILE);
        for (let y = ty - r; y <= ty + r; y++) for (let x = tx - r; x <= tx + r; x++) {
          if (x < 0 || y < 0 || x >= W || y >= H) continue;
          if (hyp((x + .5) * TILE - x0, (y + .5) * TILE - y0) <= rad) b[y * W + x] = 1;
        }
      };
  
      if (bare) {
        for (let i = 0; i < W * H; i++) b[i] = (w.tiles[i] === T.WALL || w.tiles[i] === T.PIT) ? 1 : 0;
        for (const h of g.hazards || []) if (!h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && h.spikeThreat && h.spikeThreat()) disk(h.x, h.y, (h.r || 16) + g.goat.r);
      }
      if (!bare) for (const r of g.runes || []) if (r.x != null && !r.dead) disk(r.x, r.y, TUNING.seer.runeRadius * TILE + P.margin.fire);
      if (!bare && withMills && P.margin.fire > 0) for (let i = 0; i < W * H; i++) if (w.fire[i] > 0) disk((i % W + .5) * TILE, (((i / W) | 0) + .5) * TILE, P.margin.fire);
      if (!bare) for (const h of g.hazards || []) {
        if (h.broken || h.dead) continue;
        if (h.kind === 'mill') { if (withMills) disk(h.x, h.y, MILL.armLen + g.goat.r + P.margin.mill); else disk(h.x, h.y, MILL.innerR); }
        // spikes arm when stepped on: normal routes keep off all of them; only the last-resort grid crosses idle ones
        else disk(h.x, h.y, (h.r || 14) + g.goat.r * 0.5 + Math.min(h.kind === 'spike' || h.kind === 'spire' ? 10 : 99, P.margin[h.kind] || 0));
      }
      for (const p of g.props) {
        if (p.broken || p.dead) continue;
        // soul gates stay shut until their soul is taken, seal doors while shut; every other door
        // (wooden, iron, stair) breaks after a few headbutts, so paths may run through it
        const shut = p.gate || p.exitGate || p.locked
          || (p.seal && !(p.open > 0.5));
        if (!shut) continue;
        disk(p.x, p.y, Math.max(16, p.r || 16));
      }
      return b;
    }
    function bfs(fromX, fromY, goals, grid) {
      const w = g.world, W = w.W, H = w.H, b = grid || B.grid;
      const sx = Math.floor(fromX / TILE), sy = Math.floor(fromY / TILE);
      const prev = new Int32Array(W * H).fill(-2), q = new Int32Array(W * H);
      let h = 0, tl = 0; const s = sy * W + sx; prev[s] = -1; q[tl++] = s;
      const goalSet = new Map(); goals.forEach((gl, i) => { const k = Math.floor(gl.y / TILE) * W + Math.floor(gl.x / TILE); if (!goalSet.has(k)) goalSet.set(k, i); });
      while (h < tl) {
        const c = q[h++];
        if (goalSet.has(c)) { const path = []; let k = c; while (k !== -1) { path.push(k); k = prev[k]; } path.reverse(); return { path, goal: goals[goalSet.get(c)], len: path.length }; }
        const cx = c % W, cy = (c / W) | 0;
        for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1], [-1, 1], [-1, -1]]) {
          const nx = cx + dx, ny = cy + dy; if (nx < 0 || ny < 0 || nx >= W || ny >= H) continue;
          const n = ny * W + nx; if (prev[n] !== -2) continue;
          const tt = w.tiles[n]; if (tt === T.WALL || tt === T.PIT) continue;
          if (b[n] && !goalSet.has(n) && !b[c]) continue; // a blocked start region may be walked out of
          if (dx && dy && (b[cy * W + nx] || b[ny * W + cx])) continue;
          prev[n] = c; q[tl++] = n;
        }
      }
      return null;
    }
    function route(goals) {
      // try around mills first; if they wall the way, go through them with timing
      let r = bfs(g.goat.x, g.goat.y, goals, B.gridSafe);
      if (r) { r.viaMill = false; return r; }
      r = bfs(g.goat.x, g.goat.y, goals, B.grid);
      if (r) { r.viaMill = true; return r; }
      r = bfs(g.goat.x, g.goat.y, goals, B.gridBare);
      if (r) { r.viaMill = true; r.bare = true; }
      return r;
    }
    function lineClear(x0, y0, x1, y1, grid) {
      const W = g.world.W, d = hyp(x1 - x0, y1 - y0), n = Math.max(1, Math.ceil(d / 8)), b = grid || B.grid;
      for (let i = 0; i <= n; i++) {
        const x = x0 + (x1 - x0) * i / n, y = y0 + (y1 - y0) * i / n;
        for (const [ox, oy] of [[0, 0], [10, 0], [-10, 0], [0, 10], [0, -10]]) if (b[Math.floor((y + oy) / TILE) * W + Math.floor((x + ox) / TILE)]) return false;
      }
      return true;
    }
    function follow(r) {
      const W = g.world.W, o = g.goat, path = r.path, grid = r.bare ? B.gridBare : r.viaMill ? B.grid : B.gridSafe;
      let tgt = path[Math.min(path.length - 1, 2)];
      for (let i = Math.min(path.length - 1, 5); i >= 1; i--) {
        const k = path[i];
        if (lineClear(o.x, o.y, (k % W + .5) * TILE, (((k / W) | 0) + .5) * TILE, grid)) { tgt = k; break; }
      }
      let px = (tgt % W + .5) * TILE, py = (((tgt / W) | 0) + .5) * TILE;
      if (path.length <= 1) { px = r.goal.x; py = r.goal.y; }
      // mill timing: simulate the next stretch of the walk against the rotating arms
      const dx = px - o.x, dy = py - o.y, d = hyp(dx, dy) || 1, v = 150;
      B.lastDir = { x: dx / d, y: dy / d };
      // keep walking straight through (the goat does not stop at the waypoint); after 4 s of waiting
      // only the next 0.35 s count, so a slow mill can never hold us forever
      const waited = B.millWait0 ? performance.now() - B.millWait0 : 0;
      const look = waited > 4000 ? 0.35 : Math.min(0.9, B.P.millLook);
      let blocked = false;
      for (let t = 0; t <= look && !blocked; t += 0.05) {
        const x = o.x + dx / d * v * t, y = o.y + dy / d * v * t;
        for (const m of mills()) if (millHits(m, x, y, t, B.P.margin.mill * 0.5) && !millHits(m, o.x, o.y, 0, 0)) { blocked = true; break; }
      }
      if (blocked && !millDanger(o.x, o.y, 0.4)) { if (!B.millWait0) B.millWait0 = performance.now(); stop(); B.goal = 'wait mill'; return; }
      B.millWait0 = 0;
      // fire ahead and not burning yet: roll through it (quicker than walking, the burn needs ~1.2 s)
      if (o.rollCd <= 0 && !o.onFire && (o.state === 'idle' || o.state === 'run' || !o.state)) {
        const ux = dx / d, uy = dy / d, w = g.world;
        if ([24, 48].some(r => w.isBurningPx(o.x + ux * r, o.y + uy * r)) && !rollPathBad(o, ux, uy, rollLen(), (x, y) => w.isPitPx(x, y) || (g.hazards || []).some(h => !h.broken && (h.kind === 'spike' || h.kind === 'spire') && hyp(h.x - x, h.y - y) < (h.r || 16) + o.r))) {
          move(ux, uy); aim(o.x + ux * 60, o.y + uy * 60); tap('KeyE'); say('roll through fire'); return;
        }
      }
      // a closed breakable door in the way: headbutt it until it gives
      if (o.state === 'idle' || o.state === 'run' || !o.state) for (const p of g.props) {
        if (p.broken || p.dead || p.held) continue;
        const breakable = (p.kind === 'door' && !p.gate && !p.exitGate && !p.seal && !(p.open >= 0.5))
          || ((p.kind === 'rock' || p.kind === 'coop' || p.kind === 'crate' || (p.kind === 'cage' && !p.deco)) && p.blocking);
        if (!breakable) continue;
        const pd = hyp(p.x - o.x, p.y - o.y);
        if (pd < 75 && ((p.x - o.x) * dx + (p.y - o.y) * dy) / (pd * d || 1) > 0.3 && performance.now() - B.buttT > 350) { stop(); butt(p.x, p.y); B.buttT = performance.now(); B.goal = 'break ' + p.kind; return; }
      }
      move(dx, dy);
    }
  
    // ---------- combat ----------
    const live = e => !e.dead && !e.held && !e.ghosted && e.state !== 'dead' && e.state !== 'hidden' && !e.gone;
  
    function unsafeAt(x, y) {
      const w = g.world;
      if (w.isPitPx(x, y) || w.tileAtPx(x, y) === T.WALL || w.isBurningPx(x, y) || w.isPoisonPx(x, y)) return true;
      for (const h of g.hazards || []) if (!h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && hyp(h.x - x, h.y - y) < (h.r || 16) + g.goat.r + 4) return true;
      return !!millDanger(x, y, 0.5);
    }
    // roll in the aimed direction only if every point of the roll lands safe; otherwise turn up to 90 deg
    // how far a roll carries with the current boons/upgrades, plus the slide after it
    const rollLen = () => { const R = TUNING.goat.roll; return R.speed * (g.mods.rollDistance || 1) * R.duration + 40; };
    function rollPathBad(o, cx, cy, len, deadly) {
      for (let r = 24; r <= len; r += 16) for (const off of [-11, 0, 11]) {
        const x = o.x + cx * r - cy * off, y = o.y + cy * r + cx * off;
        if (g.world.isPitPx(x, y)) return true;
        if ((g.hazards || []).some(h => !h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && hyp(h.x - x, h.y - y) < (h.r || 16) + g.goat.r && ((h.spikeThreat && h.spikeThreat()) || r > len - 40))) return true;
      }
      return false;
    }
    function rollE() {
      const o = g.goat, base = Math.atan2((B.aimW ? B.aimW.y : o.y) - o.y, (B.aimW ? B.aimW.x : o.x + 1) - o.x);
      const deadly = (x, y) => g.world.isPitPx(x, y) || (g.hazards || []).some(h => !h.broken && !h.dead && (h.kind === 'spike' || h.kind === 'spire') && hyp(h.x - x, h.y - y) < (h.r || 16) + g.goat.r);
      const len = rollLen();
      for (const da of [0, 0.5, -0.5, 1, -1, 1.57, -1.57]) {
        const a = base + da, cx = Math.cos(a), cy = Math.sin(a);
        if (rollPathBad(o, cx, cy, len, deadly)) continue;
        if (da) { move(cx, cy); aim(o.x + cx * 60, o.y + cy * 60); }
        tap('KeyE'); return true;
      }
      say('roll skipped: pit or spikes everywhere'); return false;
    }
    const winding = e => /windup|bashwind|hookwind|slamwind|hopwind|aim|cast/.test(e.state || '');
  
    function escapeMill() {
      const o = g.goat, m = millDanger(o.x, o.y, 0.35);
      if (!m) return false;
      // step out radially, or roll if the arm is right on us
      const dx = o.x - m.x, dy = o.y - m.y;
      move(dx, dy);
      if (millHits(m, o.x, o.y, 0.15, 4) && o.rollCd <= 0 && o.state !== 'lunge') { aim(o.x + dx, o.y + dy); rollE(); }
      B.goal = 'escape mill';
      return true;
    }
  
    // expert prior for the soul cards (higher = better for this bot), refined by what the runs teach
    const BOON_PRIOR = { hide: 10, howl: 9, collar: 8, horns: 8, skull: 7, throat: 7, weight: 6, leapfrog: 6, hunger: 6,
      bomb: 6, breath: 9.5, splash: 5, lungs: 5, hooves: 5, joints: 5, coldeye: 4, ember: 4, kindling: 4, jaw: 5, shield: 5,
      hocks: 3, neck: 3, spit: 4, venomroll: 3, venomjaw: 3, charge: 3, oracle: 1, stomachs: -3 };
    mem.boonScore = mem.boonScore || {};
    const boonValue = b => b ? (BOON_PRIOR[b.id] != null ? BOON_PRIOR[b.id] : 3) + (mem.boonScore[b.id] || 0) : 0;
    function pickBoon() {
      const ch = g.boonChoice || []; if (!ch.length) return;
      // tools/bot-lab.js picks for it when it wants variety (`B.choose` returns a card's index, or null to let the bot pick)
      if (B.choose) { const ci = B.choose(ch, g.boonReplace || []); if (ci != null && ch[ci]) { tap('Digit' + (ci + 1)); say('boon: lab took ' + ch[ci].id + ' from ' + ch.map(b => b.id).join('/')); return; } }
      let bi = -1, bv = 0.5;
      ch.forEach((b, i) => { const v = boonValue(b) - boonValue(g.boonReplace && g.boonReplace[i]); if (v > bv) { bv = v; bi = i; } });
      if (bi < 0) { tap('Digit4'); say('boon: skip ' + ch.map(b => b.id).join('/')); return; }
      tap('Digit' + (bi + 1)); say('boon: took ' + ch[bi].id + ' from ' + ch.map(b => b.id).join('/') + (g.boonReplace && g.boonReplace[bi] ? ' replacing ' + g.boonReplace[bi].id : ''));
    }
    // credit the boons held during a life: clears push them up, deaths push them down a little
    function creditBoons(delta) { for (const b of g.boons || []) mem.boonScore[b.id] = Math.max(-5, Math.min(5, (mem.boonScore[b.id] || 0) + delta)); save(); }
  
  
    // ================= heaven (after every death) =================
    // 1. let the god finish talking: the first talk hands out the gift that makes kills pay souls;
    // 2. spend the souls at the mirror on permanent upgrades, best first;
    // 3. leave (Backspace) and drop back onto the floor.
    const SHOP_PLAN = [['fleece', 1], ['halo', 1], ['mercy', 1], ['second', 1], ['fleece', 2], ['halo', 2], ['tumble', 1], ['mercy', 2], ['grazer', 1], ['tumble', 2], ['grazer', 2]];
    function wantedBuy() {
      const M = Heaven.meta, shelf = Heaven.shelf();
      for (const [id, rank] of SHOP_PLAN) {
        const row = shelf.findIndex(m => m.id === id); if (row < 0) continue;
        const have = Heaven.rank(id); if (have >= rank) continue;
        if (have < rank - 1) continue;
        const item = shelf[row], cost = item.costs[have], souls = Heaven.soulCost(item, have);
        if (cost == null) continue;
        if (M.sacrifices >= cost && (M.souls || 0) >= souls) return { id, rank, row, cost, souls };
        // saving up: do not spend on lower rows while the second chance is in reach and unaffordable
        if (id === 'second') return null;
      }
      return null;
    }
    function heaven() {
      const h = g.heaven, M = Heaven.meta, o = g.goat;
      if (!h || !o) return;
      if (!B.hv || B.hv.visit !== M.visits) { B.hv = { visit: M.visits, t: 0, tries: 0, panelT: 0, bought: [] }; releaseAll(); if (B.rmb) rmb(false); say(`heaven visit ${M.visits}: souls ${M.sacrifices}, orbs ${M.souls || 0}, gift ${M.gift}`); }
      const V = B.hv; V.t++;
      if (h.talk) { stop(); if (V.t % 10 === 0) tap('Space'); return; }
      if (h.panel) {
        // the panel follows the mouse hover: park the cursor in a corner so the keys pick the row
        if (!V.panelT) { const rc = cv.getBoundingClientRect(); ptr('pointermove', rc.left + 2, rc.top + 2); say(`heaven: mirror open, want ${V.want && V.want.id} (row ${V.want && V.want.row})`); }
        V.panelT++;
        if (V.panelT < 8) return;
        const w = V.want;
        if (!w || V.panelT > 80) { if (V.panelT % 10 === 0) tap('KeyE'); return; }
        if (h.panel.i < w.row) { if (V.panelT % 3 === 0) tap('KeyS'); return; }
        if (h.panel.i > w.row) { if (V.panelT % 3 === 0) tap('KeyW'); return; }
        if (!V.pressed) { tap('Space'); V.pressed = true; return; }
        if (Heaven.rank(w.id) >= w.rank) { lesson(`heaven: bought ${w.id} rank ${w.rank} for ${w.cost} souls`); V.bought.push(w.id); }
        V.want = wantedBuy(); V.pressed = false; if (!V.want) tap('KeyE'); return;
      }
      V.panelT = 0;
      if (!M.gift) {
        // the god calls on his own about 1.5 s after arrival; if he does not, walk up and ask
        if (V.t < 80) { stop(); return; }
        const god = Heaven.level().god; return heavenGo(god.x, god.y + 26, 'god');
      }
      const w = wantedBuy();
      if (w && V.tries < 6) {
        V.want = w;
        const m = g.props.find(p => p.kind === 'hmirror');
        if (m) return heavenGo(m.x, m.y + 60, 'mirror');
      }
      stop(); if (V.t % 40 === 0) { say(`heaven: leaving with ${M.sacrifices} souls`); tap('Backspace'); }
    }
    function heavenGo(x, y, kind) {
      const o = g.goat, h = g.heaven, V = B.hv;
      if (h.near && h.near.kind === kind) {
        stop();
        if (o.state !== 'idle' || o.holding) return;
        if (B.rmb) { rmb(false); return; }
        if (V.t - (V.rmbAt || -99) > 20) { V.rmbAt = V.t; V.tries++; say(`heaven: RMB at ${kind} try ${V.tries} (goat ${o.state}, rmbWas ${h.rmbWas}, panel ${!!h.panel})`); rmb(true, x, y - 30); B.rmbT = performance.now(); setTimeout(() => rmb(false), 120); }
        return;
      }
      if (!B.grid || B.t % 4 === 1) { B.grid = blockedGrid(false); B.gridSafe = blockedGrid(true); B.gridBare = blockedGrid(false, true); }
      const r = route([{ x, y, what: kind }]);
      if (r && r.len > 1) follow(r); else move(x - o.x, y - o.y);
    }
  
  
    // ================= bosses the horns cannot hurt (butcher: hornsHurt = false) =================
    // A held sword kills anything it touches, bombs and fire take a heart each, so: fetch a sword,
    // else a bomb, else tip a brazier over him when he stands next to it.
    const hornproof = e => e && !e.dead && e.kind === 'butcher' && !(TUNING.butcher && TUNING.butcher.hornsHurt);
    // the strongest weapon goes to the strongest man: a sword kills anything in one cut
    const tough = e => e && !e.dead && (e.boss || e.kind === 'butcher' || e.kind === 'ratogre' || e.champion || e.shield || (e.hp || 0) > 1);
    function bossPlan(o, boss) {
      const M = g.mods, reachG = o.r + TUNING.goat.grab.reach * 0.55, now = performance.now();
      if (o.holding) return false; // the carry/throw logic handles a held sword or bomb
      if (M.breath) return false;   // the breath rule already burns him
      B.grabMiss = B.grabMiss || new Map();
      const usable = p => { const m = B.grabMiss.get(p); return !(m && m.n >= 3 && now < m.until); };
      const pick = (list, what) => {
        const r = route(list.map(p => ({ x: p.x, y: p.y, p, what })));
        if (!r || r.len > (hornproof(boss) ? 45 : 30)) return false;
        const it = r.goal.p, d = hyp(it.x - o.x, it.y - o.y);
        if (d < reachG + (it.r || 10) && (o.state === 'idle' || !o.state) && o.grabCd <= 0) {
          stop(); aim(it.x, it.y);
          const m = B.grabMiss.get(it) && now < B.grabMiss.get(it).until ? B.grabMiss.get(it) : { n: 0, until: now + 15000 };
          m.n++; B.grabMiss.set(it, m);
          rmb(true, it.x, it.y); B.rmbT = now; say('boss: grab ' + what);
        } else { follow(r); aim(it.x, it.y); }
        B.goal = 'boss: fetch ' + what; return true;
      };
      const swords = g.props.filter(p => p.kind === 'weapon' && p.weapon === 'sword' && !p.broken && !p.held && !p.flung && usable(p));
      if (swords.length && pick(swords, 'sword')) return true;
      if (!hornproof(boss)) return false; // bombs and the brazier trick are for the butcher only
      const bombs = g.props.filter(p => p.kind === 'bomb' && !p.broken && !p.held && !p.flung && !(p.fuseT > 0) && usable(p));
      if (bombs.length && pick(bombs, 'bomb')) return true;
      // brazier trick: stand on the far side of a brazier from him, headbutt it when he is in the spill
      const BR = TUNING.prop.brazier;
      const brz = g.props.filter(p => (p.kind === 'brazier' || p.kind === 'lamp') && !p.broken && !p.dead && !p.spilled && !(p.spillCd > 0) && (hyp(p.x - boss.x, p.y - boss.y) < 10 * TILE || hyp(p.x - o.x, p.y - o.y) < 10 * TILE))
        .sort((a, b) => hyp(a.x - boss.x, a.y - boss.y) - hyp(b.x - boss.x, b.y - boss.y))[0];
      if (brz) {
        const db = hyp(boss.x - brz.x, boss.y - brz.y), ux = (boss.x - brz.x) / (db || 1), uy = (boss.y - brz.y) / (db || 1);
        const sx = brz.x - ux * 52, sy = brz.y - uy * 52; // our spot behind the brazier
        const spillX = brz.x + ux * BR.spillAt * TILE, spillY = brz.y + uy * BR.spillAt * TILE;
        if (hyp(sx - o.x, sy - o.y) < 22) {
          aim(brz.x, brz.y);
          if (hyp(boss.x - spillX, boss.y - spillY) < BR.spill * TILE + 24 && performance.now() - B.buttT > 400) { stop(); butt(brz.x, brz.y); B.buttT = performance.now(); say('boss: tip the brazier on him'); }
          else stop();
        } else { const r = route([{ x: sx, y: sy, what: 'brazier spot' }]); if (r) follow(r); else move(sx - o.x, sy - o.y); }
        B.goal = 'boss: brazier trap'; return true;
      }
      // poison/fire throws hurt him: carry any crate or item at him
      if ((g.mods.venomjaw || g.mods.charge || g.mods.splash) && o.grabCd <= 0) {
        const items = g.props.filter(p => p.item && !p.broken && !p.held && !p.flung && usable(p) && hyp(p.x - o.x, p.y - o.y) < 8 * TILE);
        if (items.length && pick(items, 'thing to throw')) return true;
      }
      // nothing that hurts him: keep him at arm's length, horns only waste hearts
      const db = hyp(boss.x - o.x, boss.y - o.y);
      if (db < 4 * TILE) {
        const W = g.world.W; let ax = o.x - boss.x, ay = o.y - boss.y;
        for (const [cx, cy] of [[ax, ay], [ax - ay, ay + ax], [ax + ay, ay - ax], [-ay, ax], [ay, -ax]]) { const l = hyp(cx, cy) || 1; if (!B.gridSafe[Math.floor((o.y + cy / l * 64) / TILE) * W + Math.floor((o.x + cx / l * 64) / TILE)]) { ax = cx; ay = cy; break; } }
        move(ax, ay); aim(boss.x, boss.y); B.goal = 'boss: keep away (no fire to hurt him)'; return true;
      }
      return false;
    }
  
  
    // ================= environment weapons and animals =================
    const BEASTS = ['tortoise', 'goose', 'crow', 'chicken', 'horse', 'pig', 'rabbit', 'husky'];
    const coops = () => g.props.filter(p => (p.kind === 'coop' || (p.kind === 'cage' && !p.deco && p.box)) && !p.broken && !p.dead);
    const freedBeasts = () => g.props.filter(p => BEASTS.includes(p.kind) && !p.broken && !p.dead);
    // a brazier or lamp headbutted from where the goat stands spills fire beyond it: do it when a man stands there
    // levels of narrow beams over pits (THE RAFTERS) leave no room to step around spilled fire
    const beamLevel = () => { if (B.beamLvl && B.beamLvl.l === g.level) return B.beamLvl.v; let n = 0; for (const t of g.world.tiles) if (t === T.PIT) n++; B.beamLvl = { l: g.level, v: n > 60 }; return n > 60; };
    function tipFire(o, enemies) {
      if (g.mods.breath || beamLevel()) return false;
      if (!(o.state === 'idle' || o.state === 'run' || !o.state) || performance.now() - B.buttT < 400) return false;
      const BR = TUNING.prop.brazier;
      for (const p of g.props) {
        if ((p.kind !== 'brazier' && p.kind !== 'lamp') || p.broken || p.dead || p.spillCd > 0 || p.spilled) continue;
        const d = hyp(p.x - o.x, p.y - o.y); if (d > 85 || d < 10) continue;
        const ux = (p.x - o.x) / d, uy = (p.y - o.y) / d, cx = p.x + ux * BR.spillAt * TILE, cy = p.y + uy * BR.spillAt * TILE;
        const hit = enemies.filter(e => hyp(e.x - cx, e.y - cy) < BR.spill * TILE + 26 && !(TUNING[e.kind] && TUNING[e.kind].immune && TUNING[e.kind].immune.fire));
        if (hit.length) { stop(); butt(p.x, p.y); B.buttT = performance.now(); say(`tip ${p.kind} on ${hit.map(e => e.kind).join('/')}`); B.goal = 'fire trap'; return true; }
      }
      return false;
    }
    // a man coming at us with a brazier close by: put the brazier between us and wait for him to step in
    function lureToFire(o, e) {
      if (g.mods.breath || beamLevel() || !e || !(e.aware || e.state === 'chase')) return false;
      if (e.kind === 'seer' || e.kind === 'hunter' || e.kind === 'wraith') return false; // they keep their distance, they never walk in
      const now = performance.now();
      // a pack of melee men is worth a longer detour and a longer wait by the brazier
      const melee = g.enemies.filter(x => !x.dead && (x.aware || x.state === 'chase') && !/seer|hunter|wraith/.test(x.kind) && hyp(x.x - o.x, x.y - o.y) < 7 * TILE).length;
      const pack = melee >= 2, waitMs = pack ? 7000 : 4000;
      if (B.lureE !== e) { B.lureE = e; B.lureT0 = now; } else if (now - B.lureT0 > waitMs) { if (now - B.lureT0 > 15000) B.lureT0 = now; return false; }
      if (TUNING[e.kind] && TUNING[e.kind].immune && TUNING[e.kind].immune.fire) return false;
      const de = hyp(e.x - o.x, e.y - o.y); if (de < 70 || de > 6 * TILE) return false;
      const brz = g.props.filter(p => (p.kind === 'brazier' || p.kind === 'lamp') && !p.broken && !p.dead && !(p.spillCd > 0) && !p.spilled && hyp(p.x - o.x, p.y - o.y) < (pack ? 6 : 3) * TILE)
        .sort((a, b) => hyp(a.x - o.x, a.y - o.y) - hyp(b.x - o.x, b.y - o.y))[0];
      if (!brz) return false;
      const db = hyp(e.x - brz.x, e.y - brz.y) || 1, ux = (e.x - brz.x) / db, uy = (e.y - brz.y) / db;
      const sx = brz.x - ux * 52, sy = brz.y - uy * 52;
      if (unsafeAt(sx, sy)) return false;
      if (hyp(sx - o.x, sy - o.y) > 20) { const r = route([{ x: sx, y: sy, what: 'behind ' + brz.kind }]); if (r && r.len < (pack ? 16 : 8)) follow(r); else return false; }
      else { stop(); aim(brz.x, brz.y); }
      B.goal = (pack ? 'lure the pack' : 'lure ' + e.kind) + ' to the ' + brz.kind; return true;
    }
    // bombs: worth a detour for a group of 2+ or a tough man
    function fetchBomb(o, enemies) {
      if (o.holding || o.grabCd > 0) return false;
      const near = enemies.filter(e => (e.aware || e.state === 'chase') && hyp(e.x - o.x, e.y - o.y) < 7 * TILE);
      if (near.length < 2 && !near.some(e => tough(e))) return false;
      const now = performance.now(); B.grabMiss = B.grabMiss || new Map();
      const bombs = g.props.filter(p => p.kind === 'bomb' && !p.broken && !p.held && !p.flung && !(p.fuseT > 0) && !((B.grabMiss.get(p) || {}).n >= 3 && now < B.grabMiss.get(p).until));
      if (!bombs.length) return false;
      const r = route(bombs.map(p => ({ x: p.x, y: p.y, p, what: 'bomb' })));
      if (!r || r.len > 12) return false;
      const it = r.goal.p, d = hyp(it.x - o.x, it.y - o.y);
      if (d < o.r + TUNING.goat.grab.reach * 0.55 + (it.r || 10) && (o.state === 'idle' || !o.state)) {
        stop(); aim(it.x, it.y);
        const m = B.grabMiss.get(it) && now < B.grabMiss.get(it).until ? B.grabMiss.get(it) : { n: 0, until: now + 15000 }; m.n++; B.grabMiss.set(it, m);
        rmb(true, it.x, it.y); B.rmbT = now; say('grab bomb for ' + near.length);
      } else follow(r);
      B.goal = 'fetch bomb'; return true;
    }
  
  
    // ================= the husky's song: BAAH on the goat's note =================
    // each cycle the husky sings at `her` and the goat's note crosses the line at `you` seconds;
    // a BAAH inside the window counts. Schedule the press for the exact moment.
    function songAssist() {
      const sg = g.song; if (!sg || sg.done) return false;
      const H = TUNING.prop.husky, cyc = Math.floor(sg.t / sg.len), r = sg.t - cyc * sg.len, until = H.you - r;
      if (sg.t >= 0 && !sg.answered && B.songCycle !== cyc && until > 0 && until < 0.3) {
        B.songCycle = cyc;
        setTimeout(() => { tap('Space'); say('husky: BAAH on the beat'); }, Math.max(0, until * 1000 - 15));
      }
      return true; // a song is on: keep the BAAH for the beat
    }
  
    function tick() {
      if (!B.on) return;
      B.t++;
      const st = g.state;
      if (st !== B.lastState) {
        say('state ' + B.lastState + ' -> ' + st);
        if (st === 'dead') { mem.deathLog = (mem.deathLog || []).concat([{ L: g.levelIndex + 1, hits: (B.hurtLog || []).slice(-6) }]).slice(-20); B.hurtLog = []; if (B.life) creditBoons(-0.15); endLife('death'); }
        if ((st === 'clear' || st === 'climb') && B.life) { creditBoons(+0.3); endLife('clear'); }
        if (st === 'win') { lesson('THE GOAT ESCAPED, run won'); }
        B.lastState = st; releaseAll();
      }
      if (st === 'boon') { if (B.t % 20 === 0 && !(g.boonArm > 0)) pickBoon(); return; }
      // the goat escaped: stay on the victory card instead of rolling into a new run
      if (st === 'win') { if (!B.won) { B.won = true; releaseAll(); say('THE GOAT ESCAPED'); } return; }
      if (st === 'clear' || st === 'card') { if (B.t % 15 === 0) { tap('Space'); clickCenter(); } return; }
      if (st === 'heaven') { heaven(); return; }
      if (st === 'paused') { if (B.t % 20 === 0) tap('Escape'); return; }
      if (st === 'dead') { if (B.t % 20 === 0) tap('Space'); return; }
      if (st !== 'play') return;
      if (g.shopDlg) { releaseAll(); if (B.rmb) rmb(false); if (B.t % 10 === 0) { const si = (B.chooseShop && B.chooseShop()) || 0; tap('Digit' + (si + 1)); say('shop: take offer ' + (si + 1)); } return; }
      if (g.beastTalk) { if (B.t % 15 === 0) tap('Space'); }
      const o = g.goat; if (!o || o.dead) return;
      if (!B.life || B.life.level !== g.levelIndex) newLife(B.life ? 'level changed' : 'start');
      const P = B.P;
      if (B.t % 4 === 1 || !B.grid) { B.grid = blockedGrid(false); B.gridSafe = blockedGrid(true); B.gridBare = blockedGrid(false, true); }
      // progress for fitness: fraction of the level's start->exit distance covered
      { const ex = g.level.exit, sx = g.level.start, tot = hyp(ex.x - sx.x, ex.y - sx.y) || 1;
        const prog = 1 - hyp(ex.x - o.x, ex.y - o.y) / tot; B.life.maxProg = Math.max(B.life.maxProg || 0, prog); }
  
      if (B.lastPos && hyp(o.x - B.lastPos.x, o.y - B.lastPos.y) < 1.5 && B.keys.size) B.stuckT++; else B.stuckT = 0;
      B.lastPos = { x: o.x, y: o.y };
  
      if (escapeMill()) return;
      // standing in fire or poison: step to the nearest clean tile first
      { const w = g.world; if (w.isBurningPx(o.x, o.y) || w.isPoisonPx(o.x, o.y)) {
          const W = w.W, cx = Math.floor(o.x / TILE), cy = Math.floor(o.y / TILE); let bx = 0, by = 0, bd2 = 1e9;
          for (let y = cy - 4; y <= cy + 4; y++) for (let x = cx - 4; x <= cx + 4; x++) { const i = y * W + x; if (B.gridSafe[i]) continue; const px = (x + .5) * TILE, py = (y + .5) * TILE, d = hyp(px - o.x, py - o.y); if (d < bd2 && lineClear(o.x, o.y, px, py, B.gridBare)) { bd2 = d; bx = px; by = py; } }
          if (bd2 === 1e9) for (let y = cy - 4; y <= cy + 4; y++) for (let x = cx - 4; x <= cx + 4; x++) { const px = (x + .5) * TILE, py = (y + .5) * TILE, d = hyp(px - o.x, py - o.y); if (w.walkableAt(x, y) && !w.isBurningPx(px, py) && !w.isPitPx(px, py) && d < bd2) { bd2 = d; bx = px; by = py; } }
          if (bd2 < 1e9) { move(bx - o.x, by - o.y); B.goal = 'leave fire'; if (o.onFire && o.rollCd <= 0 && bd2 > 40) { aim(bx, by); rollE(); } return; } } }
      const enemies = g.enemies.filter(live);
  
      // bullets
      if (o.rollCd <= 0 && o.state !== 'roll' && o.state !== 'lunge') {
        for (const bl of g.bullets || []) {
          if (bl.dead || bl.friendly || bl.fromGoat) continue;
          const dx = o.x - bl.x, dy = o.y - bl.y, d = hyp(dx, dy), vv = hyp(bl.vx || 0, bl.vy || 0);
          if (d < P.bulletDist && vv > 0 && (dx * bl.vx + dy * bl.vy) / (d * vv) > 0.85) { move(-bl.vy, bl.vx); aim(o.x - bl.vy, o.y + bl.vx); if (rollE()) say('roll bullet'); return; }
        }
      }
      // pen at the very start
      if (g.level.def.startCage && !g.penBroken) {
        if (B.t % 8 === 0) butt(o.x + 300, o.y);
        return;
      }
      // fight
      let best = null, bd = 1e9;
      for (const e of enemies) {
        const d = hyp(e.x - o.x, e.y - o.y);
        const engaged = e.aware || e.state === 'chase';
        if (d < P.engage * TILE && (engaged || d < 5 * TILE) && d < bd && (d < 2.5 * TILE ? g.sees(o.x, o.y, e.x, e.y) : lineClear(o.x, o.y, e.x, e.y, B.gridSafe))) { bd = d; best = e; }
      }
      const close = enemies.filter(e => hyp(e.x - o.x, e.y - o.y) < 2.5 * TILE);
      const free = o.state !== 'lunge' && o.state !== 'roll' && o.state !== 'stunned';
      const M = g.mods, scR = (M.screamRadius || TUNING.goat.scream.radius) * TILE;
      // BAAH, in whatever form the boons gave it
      const singing = songAssist();
      if (!singing && o.screamCd <= 0 && free && enemies.length) {
        const inR = enemies.filter(e => hyp(e.x - o.x, e.y - o.y) < scR * 0.9);
        const swingNear = inR.some(e => winding(e) && hyp(e.x - o.x, e.y - o.y) < 90);
        if (M.breath) {
          // fire cone along the run direction: run at the nearest man, then breathe
          const br = TUNING.goat.breath.range * (M.screamReach || 1), sp = hyp(o.vx, o.vy);
          const dir = sp > 40 ? Math.atan2(o.vy, o.vx) : o.facing;
          const hit = enemies.filter(e => { const d = hyp(e.x - o.x, e.y - o.y); return d < br * 0.9 && Math.abs(angDiff(Math.atan2(e.y - o.y, e.x - o.x), dir)) < TUNING.goat.breath.halfAngle * 0.9; });
          // keep fire out of the way ahead: no breath if the cone covers a corridor or a doorway
          const cx = Math.cos(dir), cy = Math.sin(dir);
          const narrow = [64, 96, 128].some(r => { const px = o.x + cx * r, py = o.y + cy * r, tx = Math.floor(px / TILE), ty = Math.floor(py / TILE); let n = 0; for (let y = ty - 1; y <= ty + 1; y++) for (let x = tx - 1; x <= tx + 1; x++) if (g.world.walkableAt(x, y)) n++; return n < 7; })
            || g.props.some(p => p.kind === 'door' && !p.broken && hyp(p.x - o.x, p.y - o.y) < br && Math.abs(angDiff(Math.atan2(p.y - o.y, p.x - o.x), dir)) < 0.8);
          const boss = hit.find(e => (e.boss || e.kind === 'butcher' || e.champion) && !(TUNING[e.kind] && TUNING[e.kind].immune && TUNING[e.kind].immune.fire));
          if (boss) { aim(boss.x, boss.y); tap('Space'); say('breath on boss ' + boss.kind); return; }
          if (hit.length >= 1 && !narrow) { aim(hit[0].x, hit[0].y); tap('Space'); say(`breath on ${hit.length}`); return; }
        } else if (M.spit) {
          const tgt = best && bd > 50 && bd < 7 * TILE && g.sees(o.x, o.y, best.x, best.y) ? best : null;
          if (tgt) { aim(tgt.x, tgt.y); tap('Space'); say('spit at ' + tgt.kind); return; }
        } else if (inR.length >= P.screamAt || swingNear) {
          if (inR[0]) aim(inR[0].x, inR[0].y);
          tap('Space'); say('BAAH stuns ' + inR.length + (M.screamStun ? ' (full throat)' : '')); return;
        }
      }
      // roll: away from a crowd / when nearly dead; with DEAD WEIGHT or LEAPFROG roll through them instead
      if (close.length && o.rollCd <= 0 && free && (close.length >= P.retreatAt || o.hp <= P.retreatHp)) {
        let ax = 0, ay = 0; for (const e of close) { const d = hyp(o.x - e.x, o.y - e.y) || 1; ax += (o.x - e.x) / d; ay += (o.y - e.y) / d; }
        const through = (M.weight || M.leapfrog) && o.hp > P.retreatHp;
        if (through) { ax = -ax; ay = -ay; }
        const W = g.world.W, cands = [[ax, ay], [-ay, ax], [ay, -ax]];
        let bx = ax, by = ay;
        for (const [cx, cy] of cands) { const d = hyp(cx, cy) || 1; const tx = o.x + cx / d * 70, ty = o.y + cy / d * 70; if (!B.gridSafe[Math.floor(ty / TILE) * W + Math.floor(tx / TILE)]) { bx = cx; by = cy; break; } }
        move(bx, by); aim(o.x + bx * 50, o.y + by * 50); rollE(); say(`roll ${through ? 'through' : 'away from'} ${close.length} (hp ${o.hp})`); return;
      }
      // Q item (boomerang / blink / effigy from the shop)
      if (best && o.itemCd <= 0 && (g.mods.boomerang || g.mods.blink || g.mods.effigy) && bd < 6 * TILE) { aim(best.x, best.y); tap('KeyQ'); say('item Q'); }
      // RMB: carry and throw things (and men, with BY THE COLLAR)
      if (o.holding) {
        const h = o.holding, isSword = h.kind === 'weapon' && h.weapon === 'sword', isMan = h instanceof Enemy;
        const charged = !(M.venomjaw || M.charge) || o.holdTimer > 0.7;
        const others = enemies.filter(e => e !== h);
        let tgt = null, td = 1e9; for (const e of others) { const d = hyp(e.x - o.x, e.y - o.y); if (d < td && g.sees(o.x, o.y, e.x, e.y)) { td = d; tgt = e; } }
        if (isSword) { const t2 = others.filter(e => tough(e) && g.sees(o.x, o.y, e.x, e.y) && hyp(e.x - o.x, e.y - o.y) < 10 * TILE).sort((a, b) => hyp(a.x - o.x, a.y - o.y) - hyp(b.x - o.x, b.y - o.y))[0]; if (t2) { tgt = t2; td = hyp(t2.x - o.x, t2.y - o.y); } }
        const limit = isMan ? (o.holdLimit || 8) * 0.8 : 99;
        if (tgt && !isSword && charged && td > P.throwMin && td < P.throwMax && lineClear(o.x, o.y, tgt.x, tgt.y, B.gridSafe)) {
          aim(tgt.x, tgt.y); rmb(false); if (o.autoHeld) { rmb(true, tgt.x, tgt.y); setTimeout(() => rmb(false), 60); }
          say('throw ' + (isMan ? h.kind + ' (man)' : h.kind === 'weapon' ? h.weapon : h.kind) + ' at ' + tgt.kind); return;
        }
        if (isMan && (!tgt || o.holdTimer > limit)) {
          // nobody to hit: smash him into the nearest wall
          let wx = 0, wy = 0, wd = 1e9; const W = g.world.W;
          for (let a = 0; a < 16; a++) { const ang = a / 16 * 2 * Math.PI; for (let r = 32; r < 200; r += 16) { const x = o.x + Math.cos(ang) * r, y = o.y + Math.sin(ang) * r; if (g.world.tiles[Math.floor(y / TILE) * W + Math.floor(x / TILE)] === T.WALL) { if (r < wd) { wd = r; wx = x; wy = y; } break; } } }
          if (wd < 1e9) { aim(wx, wy); rmb(false); say('throw ' + h.kind + ' into wall'); return; }
        }
        if (tgt && isSword) { aim(tgt.x, tgt.y); if (td > 36) { const r = route([{ x: tgt.x, y: tgt.y, what: 'cut' }]); if (r) follow(r); else move(tgt.x - o.x, tgt.y - o.y); } else stop(); B.goal = 'sword ' + tgt.kind; return; }
        if (isMan && tgt) { aim(tgt.x, tgt.y); const r = route([{ x: tgt.x, y: tgt.y, what: 'carry man' }]); if (r) follow(r); B.goal = 'carry man as shield'; return; }
        if (!tgt && !isSword && !isMan && o.holdTimer > 3) rmb(false);
      } else {
        if (B.rmb && !(B.rmbT && performance.now() - B.rmbT < 250)) rmb(false);
        const canGrab = o.grabCd <= 0 && (o.state === 'idle' || !o.state);
        // grab a man only if the game lets him be lifted, at most one try per man every 2 s, and
        // never stand still for it: a failed grab falls through to the normal fight
        B.manTry = B.manTry || new Map();
        const liftable = best && !best.unliftable && !(best.cfg && best.cfg.immune && best.cfg.immune.grab) && best.kind !== 'butcher' && !best.boss && best.state !== 'flung' && !best.held && !(best.shield && best.shieldCovers && best.shieldCovers(o.x, o.y));
        if (canGrab && M.grabMen && liftable && !B.rmb && bd < o.r + best.r + TUNING.goat.grab.reach * 0.55 && !(B.manTry.get(best) > performance.now())) {
          B.manTry.set(best, performance.now() + 2000);
          aim(best.x, best.y); rmb(true, best.x, best.y); B.rmbT = performance.now(); setTimeout(() => { if (!g.goat.holding) rmb(false); }, 200); say('grab man ' + best.kind); return;
        }
        if (canGrab && best && bd < 8 * TILE) {
          const it = g.props.filter(p => p.item && !p.broken && !p.held && !p.flung && !p.inStand && hyp(p.x - o.x, p.y - o.y) < o.r + p.r + TUNING.goat.grab.reach * 0.55)
            .sort((a, b) => hyp(a.x - o.x, a.y - o.y) - hyp(b.x - o.x, b.y - o.y))[0]
            || g.props.find(p => p.kind === 'weapon' && p.inStand && !p.broken && hyp(p.x - o.x, p.y - o.y) < o.r + p.r + TUNING.goat.grab.reach * 0.55);
          // the game only lets a grab land within 0.6 x reach and roughly ahead; after three misses on
          // the same thing, leave it alone for 15 s
          B.grabMiss = B.grabMiss || new Map();
          const miss = it && B.grabMiss.get(it);
          if (it && bd > 50 && !(miss && miss.n >= 3 && performance.now() < miss.until)) {
            const m = miss && performance.now() < miss.until ? miss : { n: 0, until: performance.now() + 15000 };
            m.n++; B.grabMiss.set(it, m);
            stop(); rmb(true, it.x, it.y); B.rmbT = performance.now(); say('grab ' + (it.kind === 'weapon' ? it.weapon : it.kind)); return;
          }
        }
      }
      // shieldman: the front is spiked, go round him
      if (best && best.shield && best.shieldCovers && best.shieldCovers(o.x, o.y) && bd < 3.5 * TILE) {
        const sx = -(best.y - o.y), sy = best.x - o.x; aim(best.x, best.y);
        move(sx + (o.x - best.x) * (bd < 60 ? 0.6 : -0.2), sy + (o.y - best.y) * (bd < 60 ? 0.6 : -0.2)); B.goal = 'flank shieldman'; return;
      }
      // rifles fire at where we stand when the aim timer runs out (no lead): step across the line
      {
        const now = performance.now();
        for (const e of enemies) {
          if (e.state !== 'aim' || !(e.timer < 0.5) || !g.sees(e.x, e.y, o.x, o.y)) continue;
          const d = hyp(e.x - o.x, e.y - o.y); if (d < 90) continue;
          let px = -(e.y - o.y), py = e.x - o.x; const W = g.world.W;
          const ok = (sx, sy) => { const l = hyp(sx, sy) || 1; return !B.gridSafe[Math.floor((o.y + sy / l * 50) / TILE) * W + Math.floor((o.x + sx / l * 50) / TILE)]; };
          if (!ok(px, py)) { px = -px; py = -py; }
          B.dodge = { until: now + 450, x: px, y: py };
          if (d < 200 && o.rollCd <= 0 && free && e.timer < 0.12) { aim(o.x + px, o.y + py); rollE(); say('roll off the rifle line'); }
          break;
        }
        if (B.dodge && now < B.dodge.until) { move(B.dodge.x, B.dodge.y); B.goal = 'sidestep rifle'; return; }
      }
      // area attacks (butcher slam / leap, ogre and boar hops): get out of the ring, punish the recovery
      for (const e of enemies) {
        const d = hyp(e.x - o.x, e.y - o.y);
        let ring = 0;
        const cfg = TUNING[e.kind] || {}, jump = cfg.hop || cfg.leap;
        if (e.state === 'slamwind' && cfg.slam) ring = cfg.slam.range * TILE + o.r + 14;
        else if ((e.state === 'hopwind' || e.state === 'hop') && jump) ring = (jump.radius || 1.5) * TILE + o.r + 14;
        if (!ring) continue;
        // a leap lands where we were: treat its ring as centred on its target (or on us)
        const slam = e.state === 'slamwind';
        const cx = slam ? e.x : (e.tx != null ? e.tx : o.x), cy = slam ? e.y : (e.ty != null ? e.ty : o.y);
        if (hyp(o.x - cx, o.y - cy) < ring) {
          let ax = o.x - cx, ay = o.y - cy; if (hyp(ax, ay) < 4) { ax = -(e.y - o.y); ay = e.x - o.x; }
          move(ax, ay);
          if (o.rollCd <= 0 && free && (e.timer == null || e.timer < 0.35)) { aim(o.x + ax, o.y + ay); rollE(); say('roll out of ' + e.kind + ' ' + e.state); }
          B.goal = 'dodge ' + e.kind + ' ' + e.state; return;
        }
        if (slam && d < ring + 40) { stop(); aim(e.x, e.y); B.goal = 'wait out slam'; return; }
      }
      // a boss the horns cannot hurt gets swords, bombs and fire instead of headbutts
      { const boss = enemies.filter(e => tough(e) && hyp(e.x - o.x, e.y - o.y) < 12 * TILE && (e.aware || e.state === 'chase')).sort((a, b) => hornproof(b) - hornproof(a))[0];
        const others = enemies.some(e => e !== boss && !tough(e) && (e.aware || e.state === 'chase') && hyp(e.x - o.x, e.y - o.y) < 8 * TILE);
        if (boss && !others && hyp(boss.x - o.x, boss.y - o.y) < 9 * TILE && !/windup|slamwind|hopwind|hop$/.test(boss.state || '') && bossPlan(o, boss)) return; }
      if (tipFire(o, enemies)) return;
      if (fetchBomb(o, enemies)) return;
      if (best && lureToFire(o, best)) return;
      // keep the hearts: low on health, do not take on a group - back away from it
      if (o.hp <= Math.max(2, Math.ceil(o.maxHp / 3))) {
        const near = enemies.filter(e => hyp(e.x - o.x, e.y - o.y) < 4 * TILE && (e.aware || e.state === 'chase'));
        if (near.length >= 2) {
          let ax = 0, ay = 0; for (const e of near) { const dd = hyp(o.x - e.x, o.y - e.y) || 1; ax += (o.x - e.x) / dd; ay += (o.y - e.y) / dd; }
          const W = g.world.W; let bx = ax, by = ay;
          for (const [cx, cy] of [[ax, ay], [ax - ay, ay + ax], [ax + ay, ay - ax], [-ay, ax], [ay, -ax]]) { const l = hyp(cx, cy) || 1; if (!B.gridSafe[Math.floor((o.y + cy / l * 64) / TILE) * W + Math.floor((o.x + cx / l * 64) / TILE)]) { bx = cx; by = cy; break; } }
          move(bx, by); if (near[0]) aim(near[0].x, near[0].y); B.goal = `low hp: back off from ${near.length}`; return;
        }
      }
      if (best && bd < 3.5 * TILE) {
        const e = best, k = P.reach[e.kind] != null ? e.kind : 'default';
        const lead = P.rollLead[e.kind] != null ? P.rollLead[e.kind] : P.rollLead.default;
        if (winding(e) && bd < 80 && o.rollCd <= 0 && o.state !== 'lunge' && (e.timer == null || e.timer < lead)) {
          if (g.mods.leapfrog) { move(e.x - o.x, e.y - o.y); aim(e.x, e.y); rollE(); say('leapfrog over ' + e.kind); return; }
          const ax = o.x - e.x + (e.y - o.y) * 0.8, ay = o.y - e.y + (o.x - e.x) * 0.8;
          move(ax, ay); aim(o.x + ax, o.y + ay); rollE(); say('roll from ' + e.kind + ' ' + e.state); return;
        }
        const tx = e.x + (e.vx || 0) * 0.12, ty = e.y + (e.vy || 0) * 0.12;
        aim(tx, ty);
        // a pit next to him: hit him from the side that sends him over the edge (bosses do not fall)
        if (!e.boss && e.kind !== 'butcher' && bd < 4 * TILE && !winding(e)) {
          const pitDir = (() => { let best = null, bdist = 1e9; for (let a = 0; a < 16; a++) { const ang = a / 16 * 2 * Math.PI, cx = Math.cos(ang), cy = Math.sin(ang); for (let r = 20; r <= 96; r += 12) { if (g.world.isPitPx(e.x + cx * r, e.y + cy * r)) { if (r < bdist) { bdist = r; best = [cx, cy]; } break; } } } return best; })();
          if (pitDir) {
            const sx = e.x - pitDir[0] * 56, sy = e.y - pitDir[1] * 56;
            const ux = (e.x - o.x) / (bd || 1), uy = (e.y - o.y) / (bd || 1);
            if (ux * pitDir[0] + uy * pitDir[1] > 0.7) { /* already lined up: the butt below pushes him in */ }
            else if (!unsafeAt(sx, sy) && hyp(sx - o.x, sy - o.y) < 3 * TILE) { const rr = route([{ x: sx, y: sy, what: 'line up ' + e.kind + ' with the pit' }]); if (rr && rr.len < 6) { follow(rr); B.goal = 'line up ' + e.kind + ' with the pit'; return; } }
          }
        }
        const cfgE = TUNING[e.kind] || {}, theirReach = (cfgE.reach || 30) + o.r + (e.r || 11) + 22;
        if (/windup|swing|bashwind|bash/.test(e.state || '') && bd < theirReach) {
          const W = g.world.W; let ax = o.x - e.x, ay = o.y - e.y;
          for (const [cx, cy] of [[ax, ay], [ax - ay, ay + ax], [ax + ay, ay - ax]]) { const l = hyp(cx, cy) || 1; if (!B.gridSafe[Math.floor((o.y + cy / l * 48) / TILE) * W + Math.floor((o.x + cx / l * 48) / TILE)]) { ax = cx; ay = cy; break; } }
          move(ax, ay); B.goal = 'step out of ' + e.kind + ' reach'; return;
        }
        // don't lunge into a mill
        const lx = o.x + (tx - o.x) / bd * 70, ly = o.y + (ty - o.y) / bd * 70;
        if (bd < P.reach[k] * Math.min(1.5, g.mods.headbuttReach || 1) && !millDanger(lx, ly, 0.4) && !unsafeAt(lx, ly) && (o.state === 'idle' || o.state === 'run' || !o.state) && performance.now() - B.buttT > 250) {
          stop(); butt(tx, ty); B.buttT = performance.now(); return;
        }
        const r = route([{ x: e.x, y: e.y, what: 'fight ' + e.kind }]);
        if (r) follow(r); else move(e.x - o.x, e.y - o.y);
        B.goal = 'fight ' + e.kind;
        return;
      }
      // objectives
      let r = null;
      // anyone who knows about us and can see us (riflemen keep 5-8 tiles away) is dealt with first
      const threats = enemies.filter(e => (e.aware || e.state === 'chase' || e.state === 'aim') && hyp(e.x - o.x, e.y - o.y) < 11 * TILE && g.sees(e.x, e.y, o.x, o.y));
      if (threats.length) {
        threats.sort((a, b) => (b.kind === 'hunter') - (a.kind === 'hunter') || hyp(a.x - o.x, a.y - o.y) - hyp(b.x - o.x, b.y - o.y));
        r = route(threats.map(e => ({ x: e.x, y: e.y, e, what: 'engage ' + e.kind })));
      }
      if (!r && o.hp <= o.maxHp - P.healBelow) {
        const heals = g.props.filter(p => p.kind === 'heal' && !p.broken && !p.dead && !p.taken);
        if (heals.length) { r = route(heals.map(p => ({ x: p.x, y: p.y, what: 'heal' }))); if (r && r.len > (o.hp <= 2 ? 150 : 70)) r = null; }
        // the pile is burning: wait at a safe distance for the fire to die instead of walking on
        if (r) {
          const hp = heals.find(p => hyp(p.x - r.goal.x, p.y - r.goal.y) < 1), w = g.world;
          const hot = hp && [[0, 0], [24, 0], [-24, 0], [0, 24], [0, -24]].some(([dx, dy]) => w.isBurningPx(hp.x + dx, hp.y + dy));
          if (hot) {
            const dh = hyp(hp.x - o.x, hp.y - o.y);
            if (dh < 3.5 * TILE || r.len < 5) { stop(); B.goal = 'wait for the fire on the heal'; return; }
          }
        }
      }
      const souls = (g.souls || []).filter(s => !s.taken);
      if (!r && souls.length) r = route(souls.map(s => ({ x: s.x, y: s.y, what: 'soul' })));
      // clear every reachable man before moving on, so nobody follows us into the next fight;
      // a man we cannot catch for 30 s is left alone for a minute
      if (!r && enemies.length) {
        const now = performance.now(); B.ignore = B.ignore || new Map();
        const pool = enemies.filter(e => !(B.ignore.get(e) > now) && !e.scripted);
        // rooms behind us (and this one) first, so nothing is left at our back
        const here = g.goatRoom != null ? g.goatRoom : 99, behind = pool.filter(e => e.room != null && e.room >= 0 && e.room <= here);
        if (behind.length) r = route(behind.map(e => ({ x: e.x, y: e.y, e, what: 'clear behind: ' + e.kind })));
        if (!r && pool.length) r = route(pool.map(e => ({ x: e.x, y: e.y, e, what: 'hunt ' + e.kind })));
        if (r) {
          if (B.huntE !== r.goal.e) { B.huntE = r.goal.e; B.huntT0 = now; }
  
        }
      }
      if (!r) {
        const cs = coops();
        if (cs.length) {
          const rc = route(cs.map(p => ({ x: p.x, y: p.y, p, what: 'free ' + (p.holds || 'animal') })));
          if (rc) {
            const c = rc.goal.p, dc = hyp(c.x - o.x, c.y - o.y);
            if (dc < 75 && (o.state === 'idle' || o.state === 'run' || !o.state)) { if (performance.now() - B.buttT > 350) { stop(); butt(c.x, c.y); B.buttT = performance.now(); } B.goal = 'free ' + (c.holds || 'animal'); return; }
            r = rc;
          }
        }
      }
      if (!r) {
        // freed animals count only if they are with us at the exit: wait up to 15 s for stragglers
        const ex = g.level.exit, far = freedBeasts().filter(b => hyp(b.x - o.x, b.y - o.y) > 6 * TILE);
        if (far.length && hyp(ex.x - o.x, ex.y - o.y) < 5 * TILE) {
          B.waitBeast0 = B.waitBeast0 || performance.now();
          if (performance.now() - B.waitBeast0 < 15000) { stop(); B.goal = 'wait for ' + far.map(b => b.kind).join('/'); return; }
        } else B.waitBeast0 = 0;
      }
      // lurking wraiths (hidden, ghosted) only show up when the goat comes close: walk up and let them start
      if (!r) {
        const lurk = g.enemies.filter(e => !e.dead && e.kind === 'wraith' && (e.state === 'hidden' || e.ghosted));
        if (lurk.length) {
          const here = g.goatRoom != null ? g.goatRoom : 99, back = lurk.filter(e => e.room != null && e.room <= here);
          const rl = route((back.length ? back : lurk).map(e => ({ x: e.x, y: e.y, e, what: 'flush out wraith' })));
          if (rl) {
            if (hyp(rl.goal.x - o.x, rl.goal.y - o.y) < 1.8 * TILE) { stop(); B.goal = 'wait for the wraith to start'; return; }
            r = rl;
          }
        }
      }
      if (!r) r = route([{ x: g.level.exit.x, y: g.level.exit.y, what: 'exit' }]);
      // a shop gate opens once something is taken from the stall. The stall dialog opens when the
      // goat walks up to the shopkeeper mouse (2.2 tiles); after it was closed the goat has to walk
      // 3.6+ tiles away before it opens again.
      if (!r) {
        const mice = g.props.filter(p => p.kind === 'mouse' && !p.broken && p.shopId >= 0 && !(p.angry > 0)
          && g.props.some(w => w.kind === 'ware' && w.shopId === p.shopId && !w.broken && w.ware));
        if (mice.length) {
          const m = mice[0], d = hyp(m.x - o.x, m.y - o.y), shut = g.shopShut && g.shopShut[m.shopId];
          if (shut) {
            if (d < 4.2 * TILE) { move(o.x - m.x, o.y - m.y); B.goal = 'leave shop to reopen'; return; }
          } else if (d < 1.8 * TILE) { stop(); B.goal = 'at shop'; return; }
          if (!shut) r = route([{ x: m.x, y: m.y, what: 'shopkeeper' }]);
        }
      }
      if (!r) {
        const doors = g.props.filter(p => !p.broken && !p.dead && (p.gate || p.exitGate || p.kind === 'door'));
        doors.sort((a, b) => hyp(a.x - o.x, a.y - o.y) - hyp(b.x - o.x, b.y - o.y));
        if (doors[0]) {
          const p = doors[0]; aim(p.x, p.y);
          if (hyp(p.x - o.x, p.y - o.y) < 80) { if (B.t % 8 === 0) butt(p.x, p.y); } else move(p.x - o.x, p.y - o.y);
          B.goal = 'door'; return;
        }
      }
      // heals are grazed: stand still next to the pile until the hp comes back
      if (r && r.goal.what === 'heal') {
        const hp = g.props.find(p => p.kind === 'heal' && !p.broken && hyp(p.x - r.goal.x, p.y - r.goal.y) < 1);
        const R = TUNING.prop.heal.pickupR + o.r;
        if (hp && hyp(hp.x - o.x, hp.y - o.y) < R - 4) { stop(); B.goal = 'grazing'; return; }
        if (hp && hyp(hp.x - o.x, hp.y - o.y) < 70) { move(hp.x - o.x, hp.y - o.y); B.goal = 'heal'; return; }
      }
      if (r) {
        if (B.goal !== r.goal.what) { say('goal ' + r.goal.what + ' len ' + r.len + (r.viaMill ? ' via mill' : '')); B.goal = r.goal.what; }
        follow(r);
        if (B.goal !== 'wait mill') aim(o.x + (o.vx || 0) * 3, o.y + (o.vy || 0) * 3);
        if (B.stuckT > 20) { say('stuck, butt forward'); const ld = B.lastDir || { x: 1, y: 0 }; if (!unsafeAt(o.x + ld.x * 70, o.y + ld.y * 70)) butt(o.x + ld.x * 50, o.y + ld.y * 50); B.stuckT = 0; }
      } else { stop(); if (B.t % 100 === 0) say('no goal'); }
    }
  
    // ---------- overlay ----------
    let ov = document.getElementById('botov');
    if (!ov) { ov = document.createElement('div'); ov.id = 'botov'; ov.style.cssText = 'position:fixed;left:8px;top:40px;z-index:99;font:11px/1.35 monospace;color:#f3e7c9;background:rgba(0,0,0,.6);padding:6px 8px;max-width:520px;pointer-events:none;white-space:pre-wrap'; document.body.appendChild(ov); }
    B.ovIv && clearInterval(B.ovIv);
    B.ovIv = setInterval(() => {
      // the panel is always on screen; F9 hides it
      if (B.hideOv) { ov.style.display = 'none'; return; }
      ov.style.display = '';
      const H = window.Heaven && Heaven.meta;
      ov.textContent = `DOOMED GOAT BOT ${B.on ? 'ON' : 'OFF'} (F8 on/off, F9 hide)\n` +
        `level ${g.levelIndex + 1}/8, hp ${g.goat ? g.goat.hp + '/' + g.goat.maxHp : '-'}, doing: ${B.goal || '-'}\n` +
        (H ? `heaven souls ${H.sacrifices}, upgrades ${JSON.stringify(H.ranks)}\n` : '') +
        `deaths so far: ${JSON.stringify(mem.deaths)}`;
    }, 500);
    // hotkeys: F8 pauses/resumes the bot (and lets go of every key), F9 hides/shows the panel
    if (!window.__goatBotKeys) {
      window.__goatBotKeys = true;
      window.addEventListener('keydown', ev => {
        if (!ev.isTrusted) return;
        if (ev.code === 'F8') { ev.preventDefault(); const b = window.bot; b.on = !b.on; if (!b.on) b.release(); }
        if (ev.code === 'F9') { ev.preventDefault(); window.bot.hideOv = !window.bot.hideOv; }
      }, true);
    }
  
    B.release = () => { releaseAll(); if (B.rmb) rmb(false); };
    Object.assign(B, { bfs, blockedGrid, lineClear, butt, aim, move, tap, millDanger, endLife, pickBoon, releaseAll });
    // `B.skip` (0..1, tools/bot-lab.js): that share of its looks at the world are skipped, a slower reaction.
    B.iv = setInterval(() => { try { if (B.skip && g.state === 'play' && Math.random() < B.skip) return; tick(); } catch (err) { say('ERR ' + err.message); } }, 50);
    say('doomed goat bot started');
  })();
  
})();
