# Packs the Pixel 2.5 hand-off (output/pixel-mid-2026-09-23) into one atlas the game can carry:
# every selected frame is cropped off its measured source rect, scaled so the unit's own
# `sourceExtent` becomes $Target px (walk frames also by their `relativeScale`, so a stride never
# resizes the body), and shelf-packed. Writes js/pixel-assets.js as a data URI, the way every other
# painted sheet is embedded. Windows PowerShell 5.1 (System.Drawing); no node image library needed.
#   powershell -ExecutionPolicy Bypass -File tools/pack-pixel.ps1
param(
  [string]$Pack = "output/pixel-mid-2026-09-23",
  [int]$Target = 112,
  [int]$Width = 2048
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$root = Split-Path -Parent $PSScriptRoot
$packDir = Join-Path $root $Pack
$m = Get-Content -Raw -Encoding UTF8 (Join-Path $packDir 'manifest.json') | ConvertFrom-Json

# one flat job list: unit, slot ('idle' or 'walk'), direction, phase, source frame
$jobs = @()
foreach ($u in $m.units) {
  $k = $Target / [double]$u.sourceExtent
  for ($d = 0; $d -lt $u.idle.Count; $d++) { $jobs += ,@($u.id, 'idle', $d, 0, $u.idle[$d], $k) }
  if ($u.walk) {
    for ($d = 0; $d -lt $u.walk.Count; $d++) {
      for ($p = 0; $p -lt $u.walk[$d].Count; $p++) { $jobs += ,@($u.id, 'walk', $d, $p, $u.walk[$d][$p], $k) }
    }
  }
}

# shelf pack
$x = 0; $y = 0; $row = 0; $pad = 2; $placed = @()
foreach ($j in $jobs) {
  $f = $j[4]; $s = $j[5] * $(if ($f.relativeScale) { [double]$f.relativeScale } else { 1.0 })
  $w = [int][math]::Ceiling($f.rect[2] * $s); $h = [int][math]::Ceiling($f.rect[3] * $s)
  if ($x + $w + $pad -gt $Width) { $x = 0; $y += $row + $pad; $row = 0 }
  $placed += ,@($j, $x, $y, $w, $h, $s)
  $x += $w + $pad; if ($h -gt $row) { $row = $h }
}
$H = $y + $row

$atlas = New-Object System.Drawing.Bitmap $Width, $H, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($atlas)
$g.Clear([System.Drawing.Color]::Transparent)
$g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
$g.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
$attr = New-Object System.Drawing.Imaging.ImageAttributes
$attr.SetWrapMode([System.Drawing.Drawing2D.WrapMode]::TileFlipXY)
$sources = @{}
$out = @{}
foreach ($pl in $placed) {
  $j = $pl[0]; $f = $j[4]; $s = $pl[5]
  if (-not $sources.ContainsKey($f.file)) { $sources[$f.file] = [System.Drawing.Image]::FromFile((Join-Path $packDir $f.file)) }
  $src = $sources[$f.file]
  $dst = New-Object System.Drawing.Rectangle $pl[1], $pl[2], $pl[3], $pl[4]
  $g.DrawImage($src, $dst, [int]$f.rect[0], [int]$f.rect[1], [int]$f.rect[2], [int]$f.rect[3], [System.Drawing.GraphicsUnit]::Pixel, $attr)
  # anchor is the foot point measured off the source, in baked px relative to the frame's own corner
  $entry = @($pl[1], $pl[2], $pl[3], $pl[4], [math]::Round($f.sourceAnchor[0] * $s, 1), [math]::Round($f.sourceAnchor[1] * $s, 1))
  $id = $j[0]
  if (-not $out.ContainsKey($id)) { $out[$id] = @{ idle = @(); walk = @() } }
  if ($j[1] -eq 'idle') { $out[$id].idle += ,$entry }
  else {
    while ($out[$id].walk.Count -le $j[2]) { $out[$id].walk += ,@() }
    $out[$id].walk[$j[2]] += ,$entry
  }
}
$g.Dispose(); foreach ($s in $sources.Values) { $s.Dispose() }
$ms = New-Object System.IO.MemoryStream
$atlas.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png); $atlas.Dispose()
$b64 = [Convert]::ToBase64String($ms.ToArray())

# hand-built JSON: ConvertTo-Json in 5.1 flattens nested one-element arrays
function Arr($a) { '[' + (($a | ForEach-Object { [string]::Join(',', ($_ | ForEach-Object { [string]::Format([Globalization.CultureInfo]::InvariantCulture, '{0}', $_) })) } | ForEach-Object { "[$_]" }) -join ',') + ']' }
$units = @()
foreach ($id in $out.Keys) {
  $u = $out[$id]
  $walk = if ($u.walk.Count) { '[' + (($u.walk | ForEach-Object { Arr $_ }) -join ',') + ']' } else { 'null' }
  $units += "`"$id`":{`"idle`":$(Arr $u.idle),`"walk`":$walk}"
}
$js = "// Generated by tools/pack-pixel.ps1 from $Pack. Do not edit by hand.`n" +
  "// Each frame is [x, y, w, h, footX, footY] in atlas px; a unit's sourceExtent is $Target px.`n" +
  "const PIXEL_ASSETS = {`"target`":$Target,`"directions`":[`"S`",`"SW`",`"W`",`"NW`",`"N`",`"NE`",`"E`",`"SE`"],`"units`":{" + ($units -join ',') + "},`"src`":`"data:image/png;base64,$b64`"};`n"
[IO.File]::WriteAllText((Join-Path $root 'js/pixel-assets.js'), $js)
Write-Output ("atlas {0}x{1}, {2} frames, {3} KB" -f $Width, $H, $placed.Count, [int]($js.Length / 1024))
